### ISSUE TITLE
 interface conversion: interface {} is float64, not int

### ISSUE THREAD

**Issue by wujianqiangwjq** [nats-io/nats.go#1014]
publish: 
    data := map[string]interface{}{
		    "id":  int(1),
		    "msg": "test",
	    }
    res, _ := json.Marshal(data)
    nc.PublishRequest("jobs", "jobs.reply", res)
sub:
   data := make(map[string]interface{})
   json.Unmarshal(msg.Data, &data)
  id := data["id"].(int)
panic: interface conversion: interface {} is float64, not int
why?

**Comment by wallyqs** [comment]
That is because in JSON there is no `int` type, so when you unmarshal it becomes a float64.
