### ISSUE TITLE
Attempting to ACK ordered consumer messages may fail forever

### ISSUE THREAD

**Issue by mprimi** [nats-io/nats.go#1027]
## Ordered consumer may get stuck forever trying to ACK

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included nats.go version
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats.go` and the `nats-server` if one was involved:
nats-server: 2.9.0-beta.17
nats.go: v1.16.0

#### OS/Container environment:
Not relevant, but reproduces on macOS and Linux

#### Steps or code to reproduce the issue:

At high level:
 - Create stream with R=3, and publish some data
 - Create an Ordered consumer
 - Attempt to ACK every message delivered
 - Restart the whole cluster while consuming

Test that reproduces is available here: https://github.com/nats-io/nats-server/pull/3292

#### Expected result:

ACKs are not required in this case, but the client lets me attempt to do them anyway.
A few ideas of how this could be improved:

 - Return an error when trying to ACK an ordered consumer message
 - Ignore (noop) ACKs for ordered consumer messages
 - Document clearly that application using ordered consumer should not ACK

#### Actual result:
Under normal circumstances, everything works fine.
However if the ephemeral consumer under the Ordered consumer gets destroyed, then the client will forever try to ACK using a request topic that nobody is listening to (and get `503` in response).

If an application is trying to be strict and always ACK before moving to the next message, then this application will be stuck forever

**Comment by mprimi** [comment]
Thank you @kozlovic for your help understanding this. Tagging you in case you want to add something.

**Comment by kozlovic** [comment]
The OrderedConsumer is internally configured with MaxDeliver of 1 and AckPolicy of none, so indeed, the user should not try to Ack the message. We could at very least mark the message passed to a "AckNone" subscription as already acked, which would cause user calling Ack() (or AckSync, etc..) to get an error, but not really telling ("nats: message was already acknowledged"), or really capture the fact that this subscription is no ack, so add something to the message's internal state that causes Ack() to return a new specific error.

Given that now you know that the user should not Ack a message for an ordered consumer, I believe that the "Actual result" section is moot. Really what it should say is that user should get an error (or be a no-op) if dealing with a AckNone consumer (regardless of ordered consumer by the way, any consumer with ack none policy).
