### ISSUE TITLE
how to use gob or json encoders with jetstream PublishAsync

### ISSUE THREAD

**Issue by jaredmcqueen** [nats-io/nats.go#1034]
My goal is to `PublishAsync` gob-encoded structs.  I know that in [gob_enc.go](https://github.com/nats-io/nats.go/blob/main/encoders/builtin/gob_enc.go) there is a `GobEncoder` but I don't know how to access it for use.

From the readme:

```go
// Simple Async Stream Publisher
for i := 0; i < 500; i++ {
	js.PublishAsync("ORDERS.scratch", []byte("hello"))
}
```
From the [Encoded Connections section of the readme](https://github.com/nats-io/nats.go#encoded-connections), how can I encode the `person` struct into a slice of bytes without having to copy and paste all the code from the [gob_enc.go](https://github.com/nats-io/nats.go/blob/main/encoders/builtin/gob_enc.go) file?

**Comment by derekcollison** [comment]
Best to just encode directly prior to the PublishAsync call. Encoders are still supported but considered deprecated. With Go 1.18 and generics we will be looking to improve this in an upcoming client release.
