### ISSUE TITLE
[question] consumer config conflict with push subscriber

### ISSUE THREAD

**Issue by SpareShade** [nats-io/nats.go#1035]
Hello,

just trying out the library... and I am getting the following error:

```configuration requests max deliver to be 5, but consumer's value is -1```

with the following subscriber

```go
	_, err := h.jetstream.Subscribe("subject", func(msg *nats.Msg) {		
		// ... do something ...
		msg.NakWithDelay(10 * time.Second)

	}, nats.Durable("subsDurableName"), nats.MaxDeliver(5))
```

```ConsumerInfo``` shows the config settings for the subscriber, but I just cannot figure out how I can modify it.

```json
{
...
	"config": {
		"durable_name": "subsDurableName",
		"deliver_policy": "all",
		"ack_policy": "explicit",
		"ack_wait": 30000000000,
		"max_deliver": -1,
		"filter_subject": "someEvent",
		"replay_policy": "instant",
		"max_ack_pending": 1000,
		"deliver_subject": "_INBOX.z1C6zp2p8dWhLS4zfjJoo4",
		"num_replicas": 0
	}
...
}
```
Am I doing something wrong? Any help is much appreciated.

**Comment by derekcollison** [comment]
That durable was created before with unlimited redeliveries, and the code above is trying to bind to it but there is a mismatch. You can use the nats cli to delete the consumer and then run your code and I believe that will clear it.

**Comment by kozlovic** [comment]
@SpareShade Starting with the upcoming release v2.9.0 (or from main/nightly if you can use that), it will be possible to update the maximum delivery setting, however, this will still be an update of the consumer (either through CLI or API), but if you call js.Subscribe() with properties that to do match what is in the JetStream consumer in the server, it is normal to get this kind of error.

**Comment by SpareShade** [comment]
@derekcollison and @kozlovic thank you! ... and thank you for building this great tool!

I read the docs, and at least at first, grasping the consumer (in relation to subscribers) is not the most intuitive. 
But after tinkering with them for a bit, things do start to make sense.
Thanks again...
