### ISSUE TITLE
Stream source info does not expose all fields sent by the server

### ISSUE THREAD

**Issue by matthiashanel** [nats-io/nats.go#1038]
https://github.com/nats-io/nats.go/blob/c157d64783d91fd2084064bd5c07a10dc4bba2d7/jsm.go#L726-L730

does not expose all the fields available

https://github.com/nats-io/nats-server/blob/a4bf4e87f670643540d1d28d1645242234d714d6/server/stream.go#L152-L158

**Comment by wallyqs** [comment]
fyi @matthiashanel the original snippet is from the nats.go/jsm.go that is being used by the nats cli, not from nats.go though that is being updated in #1039
