### ISSUE TITLE
Publish will miss message

### ISSUE THREAD

**Issue by owem0410** [nats-io/nats.go#1108]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included nats.go version
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats.go` and the `nats-server` if one was involved:
nats-server Version:  2.9.3
github.com/nats-io/nats.go v1.18.0 
#### OS/Container environment:
mac 12.6
docker Desktop 4.12.0
#### Steps or code to reproduce the issue:
```
func main() {
	nc, err := nats.Connect(nats.DefaultURL)
	if err != nil {
		panic(err)
	}
	a := 0
	for a < 10 {

		fmt.Printf("Hello World!%d\n", a)
		msg := []byte(fmt.Sprintf("Hello World!%d", a))
		err := nc.Publish("cli.hello", msg)
		if err != nil {
			fmt.Println(err)
		}
		a++
	}
}
```
#### Expected result:
when i use "nats sub cli.hello" , i will receive "Hello World!0" to "Hello World!9"
#### Actual result:
I can't get the receive all "Hello World!0" to "Hello World!9"
always lost "Hello World!7" to "Hello World!9" or more.

**Comment by wallyqs** [comment]
you need to call nc.Flush or nc.Close to send the internal buffer before the process exits

**Comment by owem0410** [comment]
Thank you,  i add nc.Flush. it work well.
