### ISSUE TITLE
Documentation for RetryOnFailedConnect does not match behavior

### ISSUE THREAD

**Issue by svenfoo** [nats-io/nats.go#1109]
#### Versions of `nats.go` and the `nats-server` if one was involved:
nats.go version: 1.18.0
nats-server version:  2.9.2

#### OS/Container environment:
Linux Fedora 36

#### Steps or code to reproduce the issue:
```
package main

import (
	"fmt"
	nats "github.com/nats-io/nats.go"
)

func main() {
	nc, err := nats.Connect(nats.DefaultURL,
		nats.RetryOnFailedConnect(true),
		nats.DisconnectErrHandler(
			func(nc *nats.Conn, err error) {
				fmt.Printf("Disconnected: %q\n", err)
			}),
		nats.ReconnectHandler(
			func(nc *nats.Conn) {
				fmt.Printf("Reconnected to %v\n", nc.ConnectedUrl())
			}),
	)
	if err != nil {
		fmt.Printf("Configuration error: %v\n", err)
	}
	if nc.IsConnected() {
		fmt.Printf("Initially connected to %v\n", nc.ConnectedUrl())
	} else {
		fmt.Printf("Not yet connected\n")
	}

	for {
		select {}
	}
}
```
Compile above code, make sure a NATS server is reachable at `localhost:4222`, and run the resulting binary.

#### Expected result:
According to the [documentation](https://docs.nats.io/using-nats/developer/connecting/reconnect#reconnection-attributes)

> RetryOnFailedConnect sets the connection in reconnecting state right away if it can't connect to a server in the initial set. The MaxReconnect and ReconnectWait options are used for this process, similarly to when an established connection is disconnected. **If a ReconnectHandler is set, it will be invoked when the connection is established**, and if a ClosedHandler is set, it will be invoked if it fails to connect (after exhausting the MaxReconnect attempts). Default is false

I would expect the `ReconnectHandler` to be called for the initial connection. So the expected output would be:
```
Reconnected to nats://127.0.0.1:4222
Initially connected to nats://127.0.0.1:4222
```

#### Actual result:

The `ReconnectHandler` is not called for the initial connection and the output is
```
Initially connected to nats://127.0.0.1:4222
```

IMO this behavior is completely acceptable, but the documentation could be more clear here. On https://github.com/nats-io/nats.go/blob/main/README.md there is a very useful hint already:

```
    nats.ReconnectHandler(func(_ *nats.Conn) {
        // Note that this will be invoked for the first asynchronous connect.
    }
```

It would be nice if https://docs.nats.io/using-nats/developer/connecting/reconnect#reconnection-attributes could also state this more clearly. To me this looked like a bug at first and I only came across the hint about _asynchronous connect_ while writing this bug report.

**Comment by piotrpio** [comment]
Both comment on `RetryOnFailedConnect` and documentation are fixed.

**Comment by svenfoo** [comment]
Awesome, thanks a lot!
