### ISSUE TITLE
Nats request reply issue : multiple subscribers not working as expected

### ISSUE THREAD

**Issue by lisablack1** [nats-io/nats.go#1117]
Versions of nats.go and the nats-server :
nats.go version: 1.18.7
nats-server version: 2.6.5

I am new to  nats , tried request-reply with cli and trying request reply model using golang

In terminal ,running the two subscribers , the request is reaching to one subscriber and fetching the response 

But when I am trying the same , using code , running  two subscribers then two subscribers are having  all the messages but getting the response from one subscriber 

Code  for Reply (running the same code two times as two subscribers)

func main() {

	url := nats.DefaultURL
	nc, _ := nats.Connect(url)
	defer nc.Drain()

	sub, _ := nc.Subscribe("test", func(msg *nats.Msg) {
		log.Println("from 2") // changing the log to identify  to check from subscriber 1 or 2
		name := msg.Subject
		msg.Respond([]byte("hello ," + name))
	})
	signalChannel := make(chan os.Signal, 1) //signalChannel ... holds the signal when user interrupts
	signal.Notify(signalChannel, os.Interrupt, syscall.SIGTERM)

	<-signalChannel
	sub.Unsubscribe()
	nc.Close()

}
Code for request : 

        subjectName := "test" 
	for i := 0; i < 10; i++ {
		msg, err := nc.Request(subjectName, []byte(fmt.Sprintf("Hi from index:%d", i)), 2*time.Second)
		if err == nats.ErrNoResponders {
			log.Println("no listeners are available , closing the requesting")
			break
		}
		log.Printf("%+v", string(msg.Data))
		time.Sleep(time.Second * 1)
	}

**Question** :   Why two subscribers are having the 10 messages , the message should reach to only one subscriber(any of the subscribers) and get the response , same like in the terminal nats cli

Am i missing anything , or do i need to update my code , Any suggestions are appreciated.

**Comment by ripienaar** [comment]
You need to use QueueSubscribe that will cause one in the queue group to get the message. 

https://docs.nats.io/using-nats/developer/receiving/queues

**Comment by lisablack1** [comment]
Hi @ripienaar  Thanks for the reply , yes QueueSubscribe is working as expected, 

I have more question ,

what will happen if the **subscriber 1** is not responded to the given message with in the time then the messages will be lost right  (will get time out from **subscriber 1** ), it wont move to  the **subscriber 2** , 

Is there any way , that we  move the message from **subscriber 1**  to other subscribers, to achieve data loss here , 

Any suggestions are appreciated.

**Comment by ripienaar** [comment]
The message will not move no, your requestor will have retry. Think of it as the same as HTTP. If your remote server is down and you get timeout or 5xx you have to handle that in an appropriate way 

The other option is to look at JetStream where you can store the message and it will do retries for you but inherently this is for decoupled processing, work queues etc. One can imagine schemes for request-reply across JetStream but it’s awkward and not really it’s strong point.

**Comment by lisablack1** [comment]
Hi @ripienaar Thanks for the suggestions and I will try work on the suggestions you mentioned.

**Comment by lisablack1** [comment]
@ R.I.Pienaar ,

When i am trying to add more than 20000 subjects in local its giving me
error message  *nats: maximum payload exceeded ,  * for 20000 subjects i
didn't get any issue

Is there any way that I can add more subjects to  streams?

**Comment by ripienaar** [comment]
Do you mean wirh jetstream? You probsbly certainly don’t need to list that many subjects you should design subjects so you can use wildcards

**Comment by lisablack1** [comment]
Yes, with jet streams , I just want to check , till how many subjects it
will accept , is there any limitation to a certain number of subjects only
it will accept?

**Comment by ripienaar** [comment]
I am sure there is a limit - in this case it was about NATS not letting you send over 1MB message not about the subjects. 

But this is the wrong question as a design putting that many distinct subjects on a stream is a bad design and indicating you should think more ahout the design

**Comment by lisablack1** [comment]
Hi @ripienaar  , Thanks for the info, I  will use wild cards ,

Is there any Nats Jet streaming Web console (like RabbitMQ UI)  , 

Can u please suggest any **GUI** for **Nats jet streaming Monitoring Console ** , so that I can get a clear picture how many subjects and messages and how much amount of memory its taking .

Any suggestions would be appreciated

**Comment by ripienaar** [comment]
Nearest we have it’s NATS surveyor. 

The best place for this kind of question is our public slack.

**Comment by lisablack1** [comment]
Hi    @ R.I.Pienaar ,

When i am working with pull subscribe under the same stream  published to
different subjects ,

stream - sample_stream
subject - sub.1, sub.2
consumer - sample_consumer

and when i am trying to consume the messages using one subject  sub.1 ,
getting all the messages (messages of  sub.2)

How to read only specific subject related msgs without filter subject ,

 why we are using subject under pull subscribe ,

	PullSubscribe(subj, durable string
<https://pkg.go.dev/builtin#string>, opts ...SubOpt
<https://pkg.go.dev/github.com/nats-io/nats.go#SubOpt>) (*Subscription
<https://pkg.go.dev/github.com/nats-io/nats.go#Subscription>, error
<https://pkg.go.dev/builtin#error>)

**Comment by ripienaar** [comment]
This should work, assuming the durable didnt already exist - if it exists you get whatever the durable is configured for before.

Please either ask these questions on slack or open new questions under discussions when its not specifically a bug report or feature request.

**Comment by lisablack1** [comment]
yeah , i have asked in discussion 
thank you
