### ISSUE TITLE
JetStreamContext AddConsumer calls ConsumerInfo without passing context

### ISSUE THREAD

**Issue by arthurzam** [nats-io/nats.go#1161]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included nats.go version
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats.go` and the `nats-server` if one was involved:

`nats.go 1.21.0`
`nats-server 2.9.9`

#### OS/Container environment:

server is running using `nats:2.9.9-alpine` docker

#### Steps or code to reproduce the issue:

When using the `AddConsumer` with a custom context (by passing `nats.Context(...)` as jsOpts), with a durable name, which means it needs to check it's config against the server. This can be seen at this code:
https://github.com/nats-io/nats.go/blob/6c6add8d63597f84bee75d37bb1520e01552a02d/jsm.go#L312-L326

But the call to `js.ConsumerInfo` isn't passed the context, which results in it using the defaults of the configured jetstream. As a result, I can't control manually the context and cancel it, even thought the function call looks like it should do it.

```go
	consumer, err := js.AddConsumer("A", &nats.ConsumerConfig{
		Durable:        consumerName,
		FilterSubject:  subject,
	}, nats.Context(ctx))
```

#### Expected result:

As long as I don't cancel the context, the client should error with `context deadline reached`.

#### Actual result:

If for 5 seconds (the default timeout interval) the server didn't respond, the context is cancel and `AddConsumer` fails.

**Comment by piotrpio** [comment]
Hello @arthurzam, thank you for reporting the issue! I created a PR fixing the bug: #1176
