### ISSUE TITLE
[question] Does nats provide a way to do stateful stream processing?

### ISSUE THREAD

**Issue by devcorpio** [nats-io/nats.go#1194]
Hi 👋 ,

Does nats provide a way to do stateful stream processing?  Something like [Kafka streams](https://kafka.apache.org/documentation/streams/) or [goka](https://github.com/lovoo/goka) but for nats

Thanks,
Alberto

**Comment by jnmoyne** [comment]
Take a look at Benthos (https://github.com/benthosdev/benthos)

**Comment by codegangsta** [comment]
Like @jnmoyne mentioned, we will be investing more in supporting https://github.com/benthosdev/benthos, I'm currently in the process of adding KV and Object Store functionality, and recently updated our NATS and JetStream components for Benthos

**Comment by devcorpio** [comment]
thank you both for this recommendation!
