### ISSUE TITLE
Prevent host lookup on websocket connection

### ISSUE THREAD

**Issue by chen-shmilovich-sysdig** [nats-io/nats.go#1205]
I'm having an issue with a websocket NATS client running behind a proxy server. The proxy server only allows connections to a specific FQDN, but NATS resolves the host's IP address before creating a connection, causing the proxy to block the request. To overcome this, I commented out the following code in the nats.go file:
```
    if net.ParseIP(u.Hostname()) == nil {
        addrs, _ := net.LookupHost(u.Hostname())
        for _, addr := range addrs {
            hosts = append(hosts, net.JoinHostPort(addr, u.Port()))
        }
    }
```
From my understanding, there's no need to resolve the IP in websocket connections because the websocket protocol operates at a higher level of abstraction than traditional network connections and uses a URL, not an IP address, to establish a connection.

I opened the following PR to prevent IP lookup when using websocket:
https://github.com/nats-io/nats.go/pull/1204

**Comment by derekcollison** [comment]
We resolve such that if multiple A records are associated with the name we can randomize them.

If you use the specific FQDN in the connect call does that work?

**Comment by lior-alafi-work** [comment]
another reason for this change is some customers create a whitelists and blacklists this allow nats to connect using that host and trigger that whitelist, if you DNS resolve, you cannot be whitelisted w/o providing FQDN to user's configurations

**Comment by derekcollison** [comment]
Could you give some more details here?

So you use one hostname to connect but want the system to actually use a different one?

**Comment by lior-alafi-work** [comment]
our customer goes through proxy then the data is propagated to NATS,
since customers might whitelist/blacklist by DNS we suggest that we'll be able to pass a flag in the configuration (or env variable) 
to allow us to skip dns resolve.

i'm not sure that this type of scenario requires us to provide FQDN

**Comment by ripienaar** [comment]
How does your client set the proxy to use? Indeed when using a proxy we need to connect to the name but unless I am missing something I am not sure how you'd tell it to use a proxy?

**Comment by chen-shmilovich-sysdig** [comment]
We implemented a custom dialer to establish a connection to our backend through a proxy, however, that's not the source of the problem.
I have confirmed that I am able to establish a connection using a websocket client without the part of the code that resolves IP address. (Calling the `Connect` function with `wss://example.url.com:443`)

**Comment by ripienaar** [comment]
Then since it’s a scenario that isn’t hit by the main code I would suggest adding an option to disable the lookup rather than a blanket change. Or alternatively to prevent the lookup here when a custom dialer is given. 

I get why proxies will require a name and not an IP - but there are good reasons for the lookup being done in NATS ecosystem

**Comment by chen-shmilovich-sysdig** [comment]
Got it @ripienaar, I'll update the PR and give the option to skip the lookup. Thanks for pointing that out.

**Comment by chen-shmilovich-sysdig** [comment]
I changed the PR to keep the default behavior and added an option to skip the host lookup:
https://github.com/nats-io/nats.go/pull/1204
