### ISSUE TITLE
Service example 

### ISSUE THREAD

**Issue by gedw99** [nats-io/nats.go#1207]
Anything on golang that is same as this ? 

https://github.com/nats-io/nats.deno/blob/main/services.md

**Comment by gedw99** [comment]
https://github.com/nats-io/nats.go/blob/main/micro/example_package_test.go seems to be it

**Comment by piotrpio** [comment]
Hello @gedw99, sorry for the late response - you are right, right now what we have are several files with examples:
- https://github.com/nats-io/nats.go/blob/main/micro/example_package_test.go  - whole package, simple example
- https://github.com/nats-io/nats.go/blob/main/micro/example_handler_test.go - example using custom handler implementation
- https://github.com/nats-io/nats.go/blob/main/micro/example_test.go - simple examples for all functions/methods

I'll be adding either a separate README for `micro` package or expand on the existing `README.md` soon.

**Comment by gedw99** [comment]
Cool thanks
