### ISSUE TITLE
Nats JS client returns the wrong error type?

### ISSUE THREAD

**Issue by PatrLind** [nats-io/nats.go#1245]
## Nats JS client returns the wrong error type?

When I was trying to create a stream using the JS GO client, i didn't receive the expected error type back.

#### Versions of `nats.go` and the `nats-server` if one was involved:
nats-server: v2.2.6
github.com/nats-io/nats.go v1.25.0

#### OS/Container environment:
Linux 5.15.0-69-generic

#### Steps or code to reproduce the issue:
* Create a stream
* Create the same stream again with different options, this should generate an error.
* The error is returned, but the type is not what I expect

```go
package main

import (
	"errors"
	"fmt"
	"os"
	"reflect"

	"github.com/nats-io/nats.go"
)

func main() {
	nc, _ := nats.Connect(nats.DefaultURL)
	js, err := nc.JetStream()
	if err != nil {
		panic(err)
	}
	_, err = js.AddStream(&nats.StreamConfig{Name: "TEST-STREAM", Retention: nats.InterestPolicy})
	if err != nil {
		panic(err)
	}

	_, err = js.AddStream(&nats.StreamConfig{Name: "TEST-STREAM", Retention: nats.WorkQueuePolicy})
	if err != nil {
		fmt.Printf("Error message: %#v\n", err)
		if errors.Is(err, nats.ErrStreamNameAlreadyInUse) {
			fmt.Println("Expected error type returned")
			os.Exit(0)
		}

		fmt.Println("Unexpected error type returned:", reflect.TypeOf(err))
		os.Exit(1)
	}
	panic("expected a failed request")
}

```

Output:
```
$ go run ./cmd/test-nats-err/
Error message: &nats.APIError{Code:500, ErrorCode:0x0, Description:"stream name already in use"}
Unexpected error type returned: *nats.APIError
exit status 1
```

#### Expected result:
I expect the returned error to be of one of the predefined types.

#### Actual result:
I get an APIError object.

![image](https://user-images.githubusercontent.com/4456415/229544789-47102920-1482-4096-bfa0-6ea194b8e43d.png)

**Comment by PatrLind** [comment]
Downgrading to version v1.16.0 seems to make the problems go away

**Comment by piotrpio** [comment]
Hey @PatrLind 

Upgrading your server version would probably be the best solution - v2.2.6 is almost 2 years old, and since then JetStream error codes were introduced. Starting with v1.17.0, the nats.go client also uses error codes instead of comparing error messages.

**Comment by PatrLind** [comment]
Thanks for your reply! I had installed the latest version, but I accidentally had an older version run because it was also installed in my system.
Perhaps the client library should return an error when connecting to an old server since it seems to not be fully compatible.

**Comment by piotrpio** [comment]
@PatrLind we aim to be backwards-compatible  with the server, and for the most part instances of such breaking changes should be rare - but if it happens, it is not clear how to determine which server version is "old" from the client perspective.
