### ISSUE TITLE
kvstore WatchAll not worked since v1.26.0

### ISSUE THREAD

**Issue by puper** [nats-io/nats.go#1275]
## Defect
- when nats.go upgrade from 1.25.0 to 1.26.0, kv store watch not worked.

#### Versions of `nats.go` and the `nats-server` if one was involved:
nats.go: v1.26.0
nats-server: 2.6.6

#### Steps or code to reproduce the issue:
```
package main

import (
	"context"
	"log"
	"time"

	"github.com/nats-io/nats.go"
	"github.com/pkg/errors"
)

func main() {
	c, err := nats.Connect(
		"nats://127.0.0.1:4222",
		nats.MaxReconnects(-1),
		nats.ReconnectWait(time.Second*3),
	)
	if err != nil {
		panic(errors.Wrap(err, "nats connect error"))
	}
	js, err := c.JetStream()
	if err != nil {
		panic(errors.Wrap(err, "JetStream error"))
	}
	_, err = js.CreateKeyValue(&nats.KeyValueConfig{
		Bucket: "test",
		//Storage: nats.MemoryStorage,
		//TTL:     time.Second * 10,
	})
	if err != nil {
		panic(errors.Wrap(err, "create key value error"))
	}
	kv, err := js.KeyValue("test")
	if err != nil {
		panic(errors.Wrap(err, "get key value error"))
	}
	ctx := context.Background()

	_, err = kv.WatchAll(nats.Context(ctx))
	if err != nil {
		panic(errors.Wrap(err, "watch all key value error"))
	}
}

```
#### Expected result:

no error returns.

#### Actual result:

panic with error: watch all key value error: nats: consumer expected to be durable but a durable name was not set

**Comment by derekcollison** [comment]
Please upgrade the server to the latest, 2.9.17 and let us know if the issues resolves.
Server version 2.6 is no longer supported.

**Comment by puper** [comment]
It works well after updgraded.
