### ISSUE TITLE
Restarting Ordered Consumer by Start Time

### ISSUE THREAD

**Issue by aldiesel** [nats-io/nats.go#1281]
https://github.com/nats-io/nats.go/blob/7c684685694621ba5e98b2471b3a11618d03da6f/js.go#L1983

If we are using an ordered consumer with a particular start time. On the consumer restarting I think it tries to resume at the sequence it last left off at, but this is in conflict with the start time. If the consumer was already successfully running with the deliver policy `DeliverByStartTime` then it should clear the start time option when resuming with `DeliverByStartSequence`

**Comment by aldiesel** [comment]
For reference this is the error we see.
```
nats: consumer delivery policy is deliver by start sequence, but optional start time is also set: recreating ordered consumer
```

**Comment by bruth** [comment]
Hi @aldiesel. Ordered consumers are ephemeral, so once the client disconnects or subscription closed, the state of that consumer is gone. This means that "re-starting" an ordered consumer will resort in creating a new ephemeral consumer with an optional start sequence or timestamp. See [this block of code](https://github.com/nats-io/nats.go/blob/v1.27.0/js.go#L1491-L1493) which does checks when the `nats.OrderedConsumer()` subscription option is passed.

**Comment by aldiesel** [comment]
I guess what I want to verify is if the consumer is resuming at the correct sequence number when the client reconnects.
It seems like when reconnecting this error is being thrown because the start time option was not cleared when resuming, since this is in conflict with the start sequence option that is set.

The line I linked above is showing that the start time option is not cleared on reset.

**Comment by bruth** [comment]
Ah ok, sorry for the confusion. I interpreted restart as _recreate_, but this is during gap detection. Indeed if it started with the start time and then attempted to "start by sequence" the time needs to be cleared.
