### ISSUE TITLE
JetStream ephemeral consumer doesn't deliver messages with sequence specified (OptStartSeq option)

### ISSUE THREAD

**Issue by ramory-l** [nats-io/nats.go#1296]
## Defect

After publishing message, ephemeral consumer doesn't deliever messages with sequence specified. Works only with Durable option in consumer config.

**Also you can try reproduce with example here:** https://natsbyexample.com/examples/jetstream/pull-consumer/go

#### Versions of `nats.go` and the `nats-server` if one was involved:
nats.go v1.26.0 && nats-server v2.9.16

#### OS/Container environment:
MacOS Ventura 13.2.1 (M1 Max)

#### Steps or code to reproduce the issue:

```
msgsToPush := make([]Msg, 0, 10)
expected := make([]string, 0, 10)
for i := 0; i < 10; i++ {
	mockData := fmt.Sprintf("{\"test_msg\": %d}", i)
	msg := types.Any{
		Value: []byte(mockData),
	}
	b, _ := msg.Marshal()
	msgsToPush = append(msgsToPush, publisher_core.Msg{
		BatchedData: [][]byte{b},
	})
	expected = append(expected, mockData)
}
err := pub.Publish(msgsToPush, "test")
if err != nil {
	t.Error(err)
	return
}

c, err := r.js.AddConsumer(streamName, &nats.ConsumerConfig{
		DeliverPolicy: nats.DeliverByStartSequencePolicy,
		AckPolicy:     nats.AckNonePolicy,
		OptStartSeq:   offset,
	})
sub, err := r.js.PullSubscribe(subjectName, "", nats.BindStream(streamName))
if err != nil {
	logrus.Errorf("failed to create pull sub for subject name %s, err: %v", subjectName, err)
	continue
}

msgs, err := sub.Fetch(maxRequestBatch, nats.MaxWait(r.jsFetchTimeout))
if err != nil {
	logrus.Errorf("failed to get msgs from subject: %s, err: %v", subjectName, err)
	err = sub.Unsubscribe()
	if err != nil {
		logrus.Errorf("failed to unsubscribe from subject: %s, err: %v", subjectName, err)
	}
	continue
}
```

#### Expected result:
Expected to see first message "{\"test_msg\":  4}"

#### Actual result:
Actual first message "{\"test_msg\":  0}"

Consumer with Durable option works as expected, but I need ephemeral one.

**Comment by piotrpio** [comment]
Hey @ramory-l, thanks for submitting the issue!

Note that when you create an ephemeral consumer with `js.AddConsumer()` and later call `PullSubscribe()`, you're actually not using the consumer you just created, but rather a brand new ephemeral consumer created with `PullSubscribe()`, thus it is using a default consumer configuration (with `DeliverAll` policy). If you want to use ephemeral consumer created in your `PullSubscribe()`, you can drop the `AddConsumer` call entirely and just do:

```go
sub, err := js.PullSubscribe(subjectName, "", nats.StartSequence(4))
```

So what you end up with your current approach is:
1. Create an ephemeral consumer with `AddConsumer()`, which binds to stream with `streamName` and has all the configuration you want
2. Call `PullSubscribe` which creates a **different** ephemeral consumer, with default configuration.
3. Messages are delivered to the new consumer, the one created with `AddConsumer` goes away after some time.

This is unfortunately part of the magic happening under the cover when using `Subscribe()` in JetStream API and is the number one reason we created a new, simplified JetStream API (beta now): https://nats.io/blog/preview-release-new-jetstream-client-api/ - I recommend to try it out.

**Comment by ramory-l** [comment]
Hi @piotrpio, thank you very much! Is't it possible to configure DeliveryPolicy and other options like AckPolicy for ephemeral consumer?

**Comment by piotrpio** [comment]
Yes, those are options supplied in `Subscribe()` (or `PullSubscribe` and all other variants). You can set most of the fields configurable for the consumer using those options, e.g. `nats.StartSequence(4)` will set `DeliverPolicy` to `DeliverByStartSequencePolicy` and `OptStartSeq` to 4. Similarly, you can use other options to set ack policy (e.g. `nats.AckNone()`).

You can take a look at all the available options in [go doc](https://pkg.go.dev/github.com/nats-io/nats.go#SubOpt)

**Comment by ramory-l** [comment]
Ok, thanks a lot!
