### ISSUE TITLE
New jetstream interface expect old interface *nats.Msg for PublishMsg, this cannot be as intended?

### ISSUE THREAD

**Issue by tpihl** [nats-io/nats.go#1302]
see jetstream package, sourcefile jetstream.go line 133. Reference to old jetstream interface as argument in new interface??

I would expect a jetstream.NewMsg that retuirn a jetstream.Msg and be able to use that in PublishMsg

/T

**Comment by Jarema** [comment]
`nats.Msg` is not an old JetStream interface, but a Core Nats interface.

There is no point in having `jetstream.Msg` in JetStream Publish, as it's only relevant when **receiving** Jetstream message (to acknowledge for example).

We are aware that Core NATS `nats.Msg` does have those methods too that might or might not work depending on context, but changing that would be a huge breaking change that we cannot have at this moment.

**Comment by tpihl** [comment]
@Jarema Thank again for a clarifying answer.

I assumed (incorrectly) that the move of jetstream to it's own package intended to separate the jetstream api from the nats api (while still allowing them to naturally overlap) to reduce/remove some of the added complexity that was put on the nats connection and nats Msg by jetstream. 

My apoligies

/T

**Comment by Jarema** [comment]
Happy to help!

I fully understand that.
What will probably make it easier to grasp is the fact that JetStream utilises Core NATS API. It's built on top of it.
That's why Core NATS API does not need to know about JetStream, but JetStream API leverages Core NATS API all over the  place.
