### ISSUE TITLE
New jetstream interface unclear how now to do something similar to Unsubscribe an ephemeral consumer

### ISSUE THREAD

**Issue by tpihl** [nats-io/nats.go#1304]
Whats the suggested way to do a clean shutdown of an ephemeral consumer?
Do I really need to disconnect my nats-connection to trigger disinterest and GC? Or literally delete the ephemeral consumer?

If I should delete it, why don't we have it's name in the returned consumer from AddConsumer, Feels clunky to call consumer.Info(ctx) that may return error to find the name to delete to shutdown cleanly.

Really appreciating any advice

**Comment by jnmoyne** [comment]
Ephemerals (as the name suggest) clean themselves up automatically after a small period of time of innactivity (i.e. no application using the consumer).

**Comment by derekcollison** [comment]
Going forward we expect all consumers to be named, and hence you can delete them, and the user can pick replication factor, storage backend, and inactivity threshold as needed.

We will have the ability in 2.10 for the stream to dictate some of these as min or max limits, e.g. inactivity threshold could be set as a maximum that all consumers will inherit if not set or will error if set but out of bounds.

**Comment by tpihl** [comment]
@jnmoyne no application using the consumer for a small period is not an sure indication that they lost interest, it may indicate that they are busy processing a chunk from some other consumer or just busy.

@derekcollison, that makes sense as the factual server perspective. However, I am afraid that the simplified/better client needs to offer some addition simplification. I think the OrderedConsumer is a brilliant example of this. Behind the scene it combined many server-features to server an ensured complete/100% in order flow of messages by hiding the complexity of gaining bulk speed transfer and some compensatory patterns instead of MaxInFlight(1). 

So my question is how i can write code that is easy to read and understand while also be well behaved and resource effective. A "defer xxx.Close()" is beautifully clean compared to several calls with contexts, error checks and possible race conditions.

/T

**Comment by Jarema** [comment]
Thanks for your feedback @tpihl ! It's really valuable for us.

@tpihl being busy or working with other consumers should not mark the consumer on the server as inactive.

There is a `Stop()` method that should be called:
https://pkg.go.dev/github.com/nats-io/nats.go@v1.26.0/jetstream#ConsumeContext

It will, however, not actively delete a Consumer, but mark it as inactive and close all behind-the-curtain operations. That was part of the old API and it was a big source of issues and confusion, as in many cases, it's only that single client loosing the interest. There might be dozens other clients/apps using this Consumer.

As @derekcollison mentioned, all consumers are going to be named, so it's pretty easy to delete them.
Even now you can call 
```
stream.DeleteConsumer(ctx, cons.CachedInfo().Name)
```
One API call, with single error.

https://pkg.go.dev/github.com/nats-io/nats.go@v1.26.0/jetstream#section-readme gives a lot of ideas how to work with new API.

**Comment by tpihl** [comment]
@Jarema thank you for answer. I've read that page many times now but it made me believe that this cons.CachedInfo() only was valid with a prior call to cons.Info() with error-check. Will try it out

/T
