### ISSUE TITLE
New jetstream interface, consumer.Info() returns error consumer instance not yet created

### ISSUE THREAD

**Issue by tpihl** [nats-io/nats.go#1305]
## Defect

There is no way to know when the consumer actually is created to successfully get info from it. Regardless, calling Info(ctx) on the returned consumer should wait until the consumer is created and then return the info. Returning the error as currently may be factually correct but not useful. An error that it was deleted, thats fine. But the nil error and returned consumer from the OrderedConsumer cannot be used must be a bug.

#### Versions of `nats.go` and the `nats-server` if one was involved:
nats.go v1.26.0
nats-server v2.9.17

#### OS/Container environment:
linux

#### Steps or code to reproduce the issue:
	con, err := str.OrderedConsumer(
		ctx,
		jetstream.OrderedConsumerConfig{
			FilterSubjects: []string{
				"a.b.1",
			},
		},
	)
	if err != nil {
		panic(err)
	}

	ci, err := con.Info(otherctx)
	if err != nil {
		panic(err)
	}

the call con.Info() returned error;
nats: consumer instance not yet created

#### Expected result:

Information about the consumer and a nil errror

#### Actual result:

No information about consumer and an error that the consumer returned by the previous call cannot be used and no way except iterative re-try  to continue (and iterative retry is a mess for readable code)

**Comment by Jarema** [comment]
Thanks for the explanation!

We changed the code to not return until consumer is created.
This is more sensible and solves  your issue too.

When it comes to performance, Ordered Consumer is the fasted one.
You should not need to tweak much - it does optimise throughput and usage of resources under the hood.
I would stick to one consumer, work with it, count messages from first info and handle your logic in that way. 

New API goal was to make simple things simple, and hard, possible with clean and nice API. Without magic under the hood that was confusing (like the `Subscribe` method that did a lot, including creating and deleting consumers). This explicit code sometimes means a line or two more, but without any neckbreaking unexpected behaviors. Your early feedback is invaluable, thank you for that!

Hope that clears things out.

Ah, and yes, `Info` is pretty resource heavy on the server side, hence @piotrpio suggestion to use message metadata, but now knowing your reason for wanting it, we can suggest using `CachedInfo`, which will give you the initial info we got from the server while creating the consumer, so it's free too.

**Comment by tpihl** [comment]
Tried with CachedInfo(), works fine. Maybe some updates to the doc+

**Comment by tpihl** [comment]
This is not working (testing with nats.go ver v1.27.1

**Comment by piotrpio** [comment]
@tpihl could you elaborate? Which part is not working, are you trying with `CachedInfo()` or `Info()`?

**Comment by tpihl** [comment]
I tried both, CachedInfo() is nil and Info() returns the error.

**Comment by piotrpio** [comment]
While that was surprising at first, the reason is pretty simple. #1317 was not part of release v1.27.1! So you'll have to be a bit more patient with this, the next release is coming very soon. You can run your test on against `main` just to be sure it's working fine.
