### ISSUE TITLE
New jetstream interface: Problem using private inbox (was: How to get subjects in a stream?)

### ISSUE THREAD

**Issue by oderwat** [nats-io/nats.go#1307]
How would I replace this when using the new API?

```
sInfo, _ := js.StreamInfo(streamName, &nats.StreamInfoRequest{SubjectsFilter: subject})
_, found := sInfo.State.Subjects[subject]
if !found {
	if listen == 0 {
		return nil, os.ErrNotExist
	}
}
```

**Comment by piotrpio** [comment]
Hello @oderwat 

What you would need to do is use `WithSubjectFilter()` option on `Info` call on stream:
```go
stream, _ := js.Stream(ctx, streamName)
sInfo, _ := stream.Info(ctx, jetstream.WithSubjectFilter(subject))
_, found := sInfo.State.Subjects[subject]
```

**Comment by oderwat** [comment]
@piotrpio Thank you. Somehow I missed that.

**Comment by oderwat** [comment]
Hum. Nothing works. I can't even get the list of stream info or names. The documentation seems already outdated, there is no ListStreams() even. I guess this is just `Streams()` but for some reason I do not get any streams listed. Is the nats-cli getting rewritten to the new interface too? I would love to see some samples.

**Comment by piotrpio** [comment]
In case of your code, it does not work because you're never going into the for loop since it's `for err != nil`. I suppose it should be:
```go
	fmt.Println("Using new interface:")
	streams := jsNew.StreamNames(context.Background())
	for err == nil {
		select {
		case name := <-streams.Name():
			fmt.Println(name)
		case err = <-streams.Err():
			fmt.Println(err)
		}
	}
```

But I get your point about the api for listing streams and stream names being cumbersome. I think it may be better to be able to simply loop over a channel which will be closed after reaching end of data, so you weld end up with something like this:
```go
	streams := jsNew.StreamNames(context.Background())
	for name := range streams.Name() {
		fmt.Println(name)
	}
	if streams.Err() != nil {
		fmt.Println(streams.Err())
	}
```

Right now this will not work but it's a simple change. I will also add options for subject listing to `ListStreams()`.

**Comment by oderwat** [comment]
@piotrpio OMG... `for err != nil`  I need to throw me out of the company :) But, as I always said in 40 years of coding: The computer does what you tell him. If it is not what you expected, you told it something wrong.

**Comment by oderwat** [comment]
I have most stuff working, but now I am again at a roadblock.

It seems to me that the consumers in the new interface do not use the custom inbox prefix on the NATS connection. I run into permission errors because it uses `_INBOX.>` which is not allowed to be subscribed by our clients as this would be a huge security problem.

We also seem to need to update all client JWTs because `$JS.API.CONSUMER.MSG.NEXT.>` pub permission is now needed too. We have very selective permissions like this for the clients `userClaims.Permissions.Pub.Allow.Add("$JS.API.CONSUMER.CREATE." + microx_tspwa.AccountsStreamBase + accountID + ".>")` to limit what streams they can access.

**Comment by oderwat** [comment]
BTW: I still believe that a function like `jsNew.StreamNames(context.Background())` should not return streams that the user has no publish permissions for. I think this is giving out information that a non-trusted client should not be able to get. As is, every client that is using JetStream can discover all existing streams in the account. Which, in our example, lets a user get the number of total user accounts in the system. It also exposes the account IDs of everybody, which I also would like to avoid.

**Comment by piotrpio** [comment]
@oderwat thanks for the PR, it looks great, I merged it. As to `$JS.API.CONSUMER.MSG.NEXT.>` - I am not sure that's feasible, as this either requires a breaking change on the server or adding a new subject to the API, which in turn would make all clients have to support both ways of doing the same thing depending on server version. I am not certain this is worth the added complexity.

**Comment by piotrpio** [comment]
@oderwat no, it's been used to get messages in pull consumers for years now.

**Comment by piotrpio** [comment]
The reason you did not have to give permissions for this subject means that you probably did not use `js.PullSubscribe()` in your applications.

**Comment by oderwat** [comment]
@piotrpio Yes, I just found that it was added 3 years ago, I wonder why this was not needed in my code before I rewrite it for the new API. I need to check that (it uses a pull-consumer too, but I am 100% sure, that we needed to have this permission for the client)

**Comment by piotrpio** [comment]
Yes, only `js.PullSubscribe()` in the old API uses pull consumers (you can request messages with `sub.Fetch()`). `SubscribeSync()` works on push consumers, internally client fills a channel with messages and `NextMsg` simply grabs the next message from this channel. Since you had no control over how fast the message come in, it was really easy to throttle the client if your application would not process the messages fast enough (then you would start getting "slow consumer" errors).
