### ISSUE TITLE
PullSubscribe does not recover on sleep/wake

### ISSUE THREAD

**Issue by biskit** [nats-io/nats.go#1310]
nats.go version: `v1.27.0` observed in earlier version `v1.12.3`

if my computer (mac os `10.15.7`) goes sleep wake even when connected to power, `PullSubscribe`/ `Fetch` does not seem to continue. however other functions like `PublishAsync` etc seem to work

I have not checked if `QueueSubscribe` has same issues

The process runs `nats-server` as a thread in this case

I have set my `SetPendingLimits` to `1024` if it matters...

**Comment by Jarema** [comment]
Is the nats-server running on the same machine?

**Comment by biskit** [comment]
it's same process (as a routine). i have updated nats-server/v2 to latest (v2.9.17) and monitoring

**Comment by Jarema** [comment]
2.6.1 was a very old and not supported version.
Glad that the newer version is working fine!
Closing the issue.
