### ISSUE TITLE
Projects depending on nats.go are also pulling in nats-server as a dependency

### ISSUE THREAD

**Issue by mkocher** [nats-io/nats.go#1311]
## Defect

Projects depending on `nats.go` are pulling `nats-server` into their go.mod file. From what I can tell this is a bug, as the go_test.mod and go_test.sum files are intended as a way to prevent library consumers from pulling in test dependencies. 

This is stemming from a few test files like [js_test.go](https://github.com/nats-io/nats.go/blob/b2d067b4ce6ddf4b1a8c5b4b7b16cb8bd09bbda0/js_test.go) which are part of the `nats` package instead of `nats_test`. The tests use nats-server and seem to need access to private variables in the `nats` package. Because of these references `go mod tidy` seems to notice the missing `nats-server` dependency and helpfully finds one that will work.

#### Versions of `nats.go`
* `nats.go` v1.27.0
* `go` version go1.20.4 linux/amd64
 
#### Steps or code to reproduce the issue:

We discovered this in [various](https://github.com/cloudfoundry/routing-release/blob/508f625b799f509a81414407a8ff88cf163ddaff/src/code.cloudfoundry.org/go.mod#LL42C21-L42C32) [Cloud Foundry](https://github.com/cloudfoundry/routing-release/blob/508f625b799f509a81414407a8ff88cf163ddaff/src/code.cloudfoundry.org/go.mod#LL42C21-L42C32) [projects](https://github.com/cloudfoundry/diego-release/blob/cbd7cf6167335ffe1b1c4b5a7b77ac51d797f992/src/code.cloudfoundry.org/go.mod#L68), but it's easily reproducible by creating a main.go that looks like this:
```
package main

import (
        "github.com/nats-io/nats.go"
)

func main() {
        // Connect to a serverV
        nc, _ := nats.Connect(nats.DefaultURL)

        // Simple Publisher
        nc.Publish("foo", []byte("Hello World"))
}
```
and doing a `go mod init example.com/example && go mod tidy` 

#### Expected result:
```bash
$ cat go.mod | grep nats-server
$
```

#### Actual result:
```bash
$ cat go.mod | grep nats-server
        github.com/nats-io/nats-server/v2 v2.9.17 // indirect
```

## Impact:
This causes `nats-server` to appear in our SBOM's, however `go get -u ./...` doesn't pick up updates to `nats-server` so we get warnings about vulnerable dependencies that aren't there and that aren't updated automatically by our tooling.

**Comment by derekcollison** [comment]
@piotrpio lets get this fixed asap. Client should not pull in server sans for tests.

**Comment by piotrpio** [comment]
@mkocher @AlexCuse The issue is fixed and released in `nats.go@v1.31.0`.
