### ISSUE TITLE
net jetstream interface; A consumer will get stuck when the call to Consume occurs after AckWait timed out

### ISSUE THREAD

**Issue by tpihl** [nats-io/nats.go#1318]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included nats.go version
 - [ ] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats.go` and the `nats-server` if one was involved:
v1.27.0 and v2.9.17

#### OS/Container environment:
Linux

#### Steps or code to reproduce the issue:
Create a (named) consumer with AckWait(5*time.Second on a stream that will return atleast one msg
Sleep for 6 seconds
call con.Consume(...)

It will not error and it will not consume anything

#### Expected result:
msgs

#### Actual result:
no error, no msgs

**Comment by piotrpio** [comment]
@tpihl from what I see, this is not tied to `AckWait`. When we're using pull consumers, messages are not sent from a stream to consumer when you create the consumer, only when you actually send the pull request (e.g. call `Consume()`). `AckWait` is the window between when the server sends the message (you send the pull request) and the server receives ACK for the message. If server does not receive `Ack()` (or `InProgress()`), it will redeliver the message.

What you encountered (I think) is the default `InactiveThreshold` kicking in - the default is 5 seconds and that means that if your consumer is inactive for more than that (meaning it does not actively query or receive messages), it will get removed. Unfortunately there is not easy way to tell that it happened (server will simply time out on pull requests, which may as well indicate there are no messages), other than the fact that you should receive `ErrNoHeartbeat`. You can verify if that's the case by adding `jetstream.ConsumeErrHandler` option to `Consume()` and print the error.

**Comment by tpihl** [comment]
When explained, it makes sense. But I will argue that this is not intuitive and the solution to cover for this would require the same solution that was deemed a not enough obvious solution for the iterator. 

IMHO it will be easier to use if it always uses ConsumeErrHandler than if that's only for some specific corner-cases that otherwise fail silent (and have no good way of recover without catching the missing heartbeat).

I will close this since it's not a  bug, but @piotrpio, i hope it will be considered when evaluating if the new interface fulfill the non-magic part or if there need to be some more compensatory actions in the interface.
