### ISSUE TITLE
Jetstream K/V bucket fails due to consumer name not being durable

### ISSUE THREAD

**Issue by alecholmez** [nats-io/nats.go#1321]
## Defect
Provided these code snippets:
```go
	kv, err := jetstream.KeyValue("foo")
	switch {
	case errors.Is(err, nats.ErrBucketNotFound):
		return jetstream.CreateKeyValue(&nats.KeyValueConfig{
			Bucket:      "foo",
			Description: "foobar",
		})

	stuff, err := s.kv.Keys()
	switch {
	// If we find that theres no keys then init is a no-op
	case errors.Is(err, nats.ErrNoKeysFound):
		return nil
	case err != nil:
		return err
	}
```
I receive the following error:
```
nats: consumer expected to be durable but a durable name was not set
```

#### Versions of `nats.go` and the `nats-server` if one was involved:

Client library version: `v1.26.0+`. This bug does NOT exist in `v1.25.0`.

#### Expected result:

No errors when creating accessing k/v buckets.

#### Actual result:

The below error:
```
nats: consumer expected to be durable but a durable name was not set
```

**Comment by piotrpio** [comment]
I assume the version of nats-server you're using is lower than 2.9.0? If so, there was indeed a bug which caused us to use invalid subject to create the consumer on older server versions when durable was not set. I created a PR to solve this issue - #1325 

In the meantime, I would encourage you to switch to newer server release (current is 2.9.18) - there were really a lot of new features and improvements throughout 2.9.x releases!

**Comment by gudron** [comment]
same problem @ github.com/nats-io/nats.go v1.27.0
on v1.25.0 bucket watching works fine
