### ISSUE TITLE
new jetstream interface does not allow an OrderedConsumer to be HeadersOnly. Why?

### ISSUE THREAD

**Issue by tpihl** [nats-io/nats.go#1323]
Sometimes headers is enough, why force OrderedConsumer to bring body when normal consumer can be HeadersOnly? I think it makes sense to add HeadersOnly to the OrderedConsumerConfig.

/T

**Comment by piotrpio** [comment]
You are correct, `HeadersOnly` should be a part of `OrderedConsumerConfig` - I will add it.
