### ISSUE TITLE
Typographical Error in Variable Name `ErrHistoryToLarge`

### ISSUE THREAD

**Issue by YukiBobier** [nats-io/nats.go#1335]
I've noticed a minor typographical error in one of the error variable names within the codebase. The variable `ErrHistoryToLarge` appears to be a typographical error and should likely be `ErrHistoryTooLarge`, considering the context in which it's used.

You can find the issue at this location:
https://github.com/nats-io/nats.go/blob/e9480bf4aaabb9d0630b2f57d370a5b36833b654/kv.go#L296

Even though this typo doesn't impact the functionality of the code, it's essential for us to maintain a clear and accurate error name. They play a significant role in effective debugging and facilitate understanding of the code behavior.

If there's consensus on addressing this issue, I'm more than willing to create and submit a pull request to rectify this typo, ensuring that it does not break existing dependencies on `ErrHistoryToLarge`.

**Comment by piotrpio** [comment]
Hey @YukiBobier , thanks for filing the issue.

While you're right about the typo, I do not think we should change it at this point - this is public API and this would be a breaking change unfortunately.

**Comment by YukiBobier** [comment]
Hi @piotrpio ,

Thank you for your prompt response and for considering my suggestion. I understand your concerns about causing a breaking change to the public API.

I agree that maintaining stability is crucial, even if it comes at the cost of a small typographical error. Maybe, in the future, if a major version update happens, we could consider this minor correction.

Again, thanks for your time and clarification on the matter.
