### ISSUE TITLE
KV Store is not included in the new JetStream API

### ISSUE THREAD

**Issue by mdawar** [nats-io/nats.go#1342]
Hey,

The new JetStream API doesn't mention the KV store at all, are there any plans to add it later?

Using the KV store now requires a JetStream context (using the old API):

```go
nc, _ := nats.Connect(url)
defer nc.Drain()

js, _ := jetstream.New(nc) // New API without the KV store API

oldJS, _ := nc.JetStream() // Required to use the KV store API

kv, _ := oldJS.CreateKeyValue(&nats.KeyValueConfig{
	Bucket: "profiles",
})
```

**Comment by piotrpio** [comment]
Hey @mdawar,
Sorry for the inconvenience - yes, we are planning to add KV to the new API, hopefully soon.

**Comment by mdawar** [comment]
@piotrpio OK thanks.
