### ISSUE TITLE
Consumers losing subscription to topics after rolling deployment (JetStream).

### ISSUE THREAD

**Issue by GrzW** [nats-io/nats.go#1358]
### Defect:
We are experiencing an issue in one of our environments after migrating from NATS STAN to NATS JetStream. During a simultaneous rolling deployment of all services, some topics are left with no consumers, even though all consumers report successful subscription at startup. This problem is leading to unprocessed messages in the affected topics. Details and steps to reproduce the issue are provided below.

### Versions of NATS.Client and nats-server:
NATS Client (github.com/nats-io/nats.go): v1.23.0
NATS Server (JetStream-enabled cluster): v2.9.19, 3 nodes
### OS/Container environment:
Go version: 1.18.10
Kubernetes with Helm charts (0.19.16)

### Steps or code to reproduce the issue:

- Connect 8 different services to the NATS cluster; each service starts 1 to 3 consumers for different queue groups, each consumer subscribes to several topics. In some cases, multiple consumers within one service subscribe the same topics (with different queue groups).
- Perform a rolling deployment of all services simultaneously.
- During startup, all consumers report successful subscription to all specified topics.
- Observe that messages are not handled, as some topics are left with no consumers, although publishers report no errors when sending messages to those topics.

Note: This issue does not occur in our development environment, occurs only on staging environment, which technically runs the same code on the same infrastructure. The problem is rectified when deploying services one by one.

### Expected result:
All consumers should continue to connect to their respective topics after a simultaneous rolling deployment, with no loss of messages or disconnection.

### Actual result:
After deployment, some topics are left without consumers, leading to unprocessed messages in those topics. Publishers do not report errors when sending messages to those topics.

### helm.tf:
```
resource "helm_release" "nats" {
  name       = local.nats_name_override
  repository = "https://nats-io.github.io/k8s/helm/charts"
  chart      = "nats"
  version    = "0.19.16"

  namespace        = local.nats_namespace
  create_namespace = true
  atomic           = true
  set {
    name  = "fullnameOverride"
    value = local.nats_name_override
  }
  set {
    name  = "nats.jetstream.enabled"
    value = "true"
  }
  set {
    name = "nats.jetstream.fileStorage.enabled"
    value = "true"
  }
  set {
    name = "nats.jetstream.fileStorage.storageClassName"
    value = "gp2"
  }
  set {
    name = "cluster.enabled"
    value = "true"
  }
  set {
    name = "cluster.replicas"
    value = local.nats_replicas # 3
  }
  set {
    name = "cluster.noAdvertise"
    value = "true"
  }
  set {
    name  = "nodeSelector.<redacted>\\.com/node-type"
    value = "nats"
  }
  set {
    name = "exporter.enabled"
    value = "true"
  }
}
```

### A sample stream, with no consumers, looks like this:
```{
  "config": {
    "name": "ScoreBoard",
    "subjects": [
      "ScoreBoard"
    ],
    "retention": "limits",
    "max_consumers": -1,
    "max_msgs": -1,
    "max_bytes": -1,
    "discard": "old",
    "max_age": 0,
    "max_msgs_per_subject": -1,
    "max_msg_size": -1,
    "storage": "file",
    "num_replicas": 1,
    "duplicate_window": 120000000000,
    "allow_direct": false,
    "mirror_direct": false
  },
  "created": "2023-07-28T08:11:01.537882463Z",
  "state": {
    "messages": 1434,
    "bytes": 714887,
    "first_seq": 1,
    "first_ts": "2023-07-28T08:12:22.628606086Z",
    "last_seq": 1434,
    "last_ts": "2023-08-02T11:46:19.450030899Z",
    "consumer_count": 0,
    "deleted": null,
    "num_deleted": 0,
    "num_subjects": 1,
    "subjects": null
  },
  "cluster": {
    "name": "nats",
    "leader": "nats-0"
  }
}
```

### Edit:
After further investigation and experimentation, we found a temporary workaround for the described issue. By inserting a short sleep command before starting the CQRS router and subscribing, we've been able to mitigate the problem in our environment.

Our monitoring tool shows that during the deployment there are streams with no consumers, but after a few moments they show subscribers again.

**Comment by scottf** [comment]
@GrzW I transferred this issue to the go client.

**Comment by Jarema** [comment]
Hey!

First, let's clarify few things:
* Consumer are created on the cluster, and it's the cluster that holds their state
* Clients / apps subscribe to those consumers to get messages

My guess is that your consumers might have an `inactivity threshold` set, and the consumers might get cleaned up if the upgrade takes too much time.

We need some code snippets to see how you use consumers in code.

**Comment by GrzW** [comment]
Hey @Jarema!

Thank you for your insights and clarification regarding the consumers' state within the cluster. We considered your observation about the inactivity threshold and looked into that possibility as well.

However, upon further investigation, we've identified the root of the problem elsewhere. It appears to be within the library we are using to handle CQRS. This library comes with its own driver, which is exhibiting erratic behaviour when closing subscriptions, leading to the observed issues with consumers.

We will continue to explore solutions for this issue within our own/library's codebase. Thank you very much for your engagement and insights into the issue!
