### ISSUE TITLE
stream.CreateOrUpdateConsumer with FilterSubjects error

### ISSUE THREAD

**Issue by elkmi** [nats-io/nats.go#1369]
nats.go version v1.28.0
  nats-server version  2.9.21-beta

code :
	cons, err := stream.CreateOrUpdateConsumer(ctx, jetstream.ConsumerConfig{
		Durable:           durable,
		AckPolicy:         jetstream.AckExplicitPolicy,
		FilterSubjects: []string{"foo.p1.p2"}, // has erro. get foo.u1 subject messags
		// FilterSubject:    "foo.p1.p2", // this works ok

	})

cmd: nats pub foo.u1 msg1

use FilterSubjects: []string{"foo.p1.p2"} for subject, I get foo.u1 messags.
but use FilterSubject:    "foo.p1.p2", It works ok, not get foo.u1 messags.

**Comment by piotrpio** [comment]
Hey @elkmi , thanks for submitting the issue. Unfortunately `FilterSubjects` will only be available as an option in nats-server v2.10.0. This field was already added in `nats.go`, but for now you will have to use `FilterSubject`.
