### ISSUE TITLE
nc.processConnectInit() does not call errorHandler, if it fails

### ISSUE THREAD

**Issue by tamalsaha** [nats-io/nats.go#1388]
### What version were you using?

2.9.21

### What environment was the server running in?

Mac M1

### Is this defect reproducible?

Yes

### Given the capability you are leveraging, describe your expectation?

I expected the error handler to be called to report error on reconnection.

### Given the expectation, what is the defect you are observing?

https://github.com/nats-io/nats.go/blob/9153b83ed1141cfbef65bd8d7b4fe2e477edd1e5/nats.go#L2733

When `nc.processConnectInit()` fails, it does not call the errorHandler. We had a bug in our code, where we deleted the nats.cred file after initial connection. When nats server will restart, nats client will not be able to reconnect (because we have deleted the creds file).

The issue is that this was not reported in the error handler. Ultimately, we had to debug using breakpoint to find the issue. It be very helpful to the users when `nc.processConnectInit()` fails, report the error using error Handler.

**Comment by piotrpio** [comment]
Hey @tamalsaha , thanks for creating the issue. The callbacks are invoked inside `nc.processConnectInit()` for some of the errors, but were missing when connection string (with credentials) is prepared, I'll be fixing that.
