### ISSUE TITLE
Subscribe callback can be triggered after close is called

### ISSUE THREAD

**Issue by lalexgap** [nats-io/nats.go#1396]
### What version were you using?

We're currently using `	github.com/nats-io/nats.go v1.21 .

### What environment was the server running in?

This was detected on a linux CI machine.

### Is this defect reproducible?

 I've copied the following snippets from our full [codebase](https://github.com/statechannels/go-nitro/blob/3dc13590424864a16e3b58a28a30ec275085335f/rpc/transport/nats/client.go#L50) to illustrate the issue.

We have a function where we subscribe to messages and send those messages on an internal chan `notificationChan` 
```
func (c *natsTransportClient) Subscribe() (<-chan []byte, error) {

	c.notificationChan = make(chan []byte)
	subscription, err := c.nc.Subscribe(nitroNotificationTopic, func(msg *nats.Msg) {
		c.notificationChan <- msg.Data
	})
	c.natsSubscriptions = append(c.natsSubscriptions, subscription)

	return c.notificationChan, err
}
```

In our close we first close our `natsTransport` ([which closes the underlying NATS connection](https://github.com/statechannels/go-nitro/blob/3dc13590424864a16e3b58a28a30ec275085335f/rpc/transport/nats/server.go#L46)) and then we close the `notificationChan`
```
func (c *natsTransportClient) Close() error {
	err := c.natsTransport.Close()
	if err != nil {
		return err
	}
	close(c.notificationChan)
	return nil
```

Occasionally(maybe once a week I) though on CI we see failures like this:
```
=== RUN   TestRpcWithNats/2_clients
    rpc_test.go:205: Ledger channels queried
    rpc_test.go:262: Payment channels queried
    rpc_test.go:293: Vouchers sent/received
    rpc_test.go:308: Ledger/virtual channels closed
panic: send on closed channel

goroutine 17946 [running]:
github.com/statechannels/go-nitro/rpc/transport/nats.(*natsTransportClient).Subscribe.func1(0x0?)
	/home/runner/work/go-nitro/go-nitro/rpc/transport/nats/client.go:56 +0x25
github.com/nats-io/nats%2ego.(*Conn).waitForMsgs(0xc002343800, 0xc0045895f0)
	/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.21.0/nats.go:2884 +0x3f2
created by github.com/nats-io/nats%2ego.(*Conn).subscribeLocked in goroutine 17695
	/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.21.0/nats.go:4114 +0x3c8
FAIL	github.com/statechannels/go-nitro/node_test	9.077s
```

This indicates that the callback function we pass into `c.nc.Subscribe` to handle a message is being triggered **after** we've closed down the nats connection.

### Given the capability you are leveraging, describe your expectation?

I would expect that once we close the underlying NATS connection we could be guaranteed that the callback function we be provided will not be called.

### Given the expectation, what is the defect you are observing?

It looks like it's possible (if you get unlucky with timing) that the `Subscribe` callback can be triggered even after the connection has been closed.

**Comment by wallyqs** [comment]
When you are calling `Close()` the callback might already be executing since it is running in its own goroutine so not a lot that we can do to preempt it from running, one approximation that you could do is to call `Unsubscribe()` first on the subscriptions before calling `Close`.  `Drain()` does something similar by calling `Unsubscribe` but it will wait for any buffered messages to be processed before calling `Close`.

**Comment by lalexgap** [comment]
> When you are calling Close() the callback might already be executing since it is running in its own goroutine so not a lot that we can do to preempt it from running

In our codebase we address this using waitgroups. A `Close` function uses a waitgroup to wait until all go-routines have been completed before returning, guaranteeing that no go functions execute beyond when `Close` is called. 

> one approximation that you could do is to call Unsubscribe() first on the subscriptions before calling Close. Drain() does something similar by calling Unsubscribe but it will wait for any buffered messages to be processed before calling Close.

This sounds like it will solve the issue for us, thanks! 👍
