### ISSUE TITLE
deliverGroup option is not present in jetstream consumer configuration

### ISSUE THREAD

**Issue by emile-tawfik** [nats-io/nats.go#1415]
### What motivated this proposal?

I was trying to create a consumer with the `CreateOrUpdateConsumer` method and I didn't find the deliverGroup option in https://github.com/nats-io/nats.go/blob/v1.30.0/jetstream/consumer_config.go#L40

### What is the proposed change?

Add the `deliverGroup` option in the `ConsumerConfig` structure.

### Who benefits from this change?

Anybody who wants to create a consumer throught code with this option.

### What alternatives have you evaluated?

I actually need to use nack to create the consumers.
Here is the option missing https://github.com/nats-io/nack/blob/v0.12.0/deploy/crds.yml#L512

**Comment by ripienaar** [comment]
The new jetstream APi is entirely pull based and pull consumers don’t need or support queue groups.

**Comment by emile-tawfik** [comment]
Ok the issue solved by the deliverGroup option was due to a miss configured ackWait. (way to low)
