### ISSUE TITLE
Jetstream Object Store: Calculate hash

### ISSUE THREAD

**Issue by udf2457** [nats-io/nats.go#1424]
### What motivated this proposal?

A cursory glance at the NATS code suggests that nothing is presently done in terms of ensuring end-to-end integrity of blobs.

AWS S3 (and S3 compatible software such as MinIO) offer the ability to submit a `Content-MD5` header on upload.  If the client sends `Content-MD5` then the server will also calculate an MD5 and if there is a mismatch, it returns an error.

### What is the proposed change?

1. Provide the option to submit a pre-calculated MD5 (or maybe a more modern algorithm such as Blake) for uploads.
2. Implement server-side logic to calculate and compare

### Who benefits from this change?

Everyone who cares about data integrity. ;-)

**Comment by Jarema** [comment]
Hey.

We are [calculating](https://github.com/nats-io/nats.go/blob/main/object.go#L446) sha256 for every blob and store it in

```
Digest  string    `json:"digest,omitempty"`
```

We also check it when reading the data back: 	https://github.com/nats-io/nats.go/blob/main/object.go#L1264

**Comment by udf2457** [comment]
Super. thanks for the clarification @Jarema 

I was doing some work on integrating NATS with Powerdns/simpleblob (https://github.com/PowerDNS/simpleblob/issues/55). 

It all started because their SS3 calls were not using `Content-MD5` and so that got me thinking about NATS and whether NATS did it or I had to explicitly call some function/header like you do with SS3.

**Comment by Jarema** [comment]
Thanks for doing this!
Feel free to ask for help around this integration (probably easiest to do on our slack channel).

I'm closing this issue.
