### ISSUE TITLE
Conflict with Prometheus version v0.47.0 while using nats lib

### ISSUE THREAD

**Issue by 26tanishabanik** [nats-io/nats.go#1427]
### What version were you using?

github.com/nats-io/nats-server/v2 v2.10.1 
github.com/nats-io/nats.go v1.30.2 
github.com/nats-io/nkeys v0.4.5
github.com/nats-io/nuid v1.0.1

### What environment was the server running in?

Darwin 
RELEASE_ARM64_T6000 x86_64

### Is this defect reproducible?

Yes

Steps to reproduce:

- Clone the [opentelemetry-contrib-repo](https://github.com/open-telemetry/opentelemetry-collector-contrib)
- Import the nats lib in the kafka-exporter `factory.go` file
- Compile the code with a `otelcol-builder.yaml` file with the changes made, `~/go/bin/builder --config=/Users/tanishabanik/Desktop/projects/project1/project2/project3/otelcol-builder.yaml`

### Given the capability you are leveraging, describe your expectation?

Expectation:
That the conflict is resolved and helps with successful compilation

### Given the expectation, what is the defect you are observing?

<img width="1263" alt="Screenshot 2023-10-03 at 12 39 56 PM" src="https://github.com/nats-io/nats.go/assets/50806654/80fd98a2-9bd9-453f-b496-d408e4a78890">

**Comment by 26tanishabanik** [comment]
@piotrpio Do you have any update on this blocking issue?

**Comment by ripienaar** [comment]
@26tanishabanik I dont think there is information here we can help you with, it does not appear nats related at all.  We dont support prometheus, otel or however you say you are importing it into some `factory.go` file.

We can try to help you if you show us some examples of what you are doing but this seems, with the information here, entirely unrelated.

**Comment by piotrpio** [comment]
@26tanishabanik as @ripienaar mentioned, this does not seem to be related to nats.go.

I'll be closing the issue. Feel free to reopen it if you feel otherwise or have some additional questions.
