### ISSUE TITLE
Auto reconnect durable pull consumer

### ISSUE THREAD

**Issue by tamalsaha** [nats-io/nats.go#1429]
### What motivated this proposal?

It seems to me that durable pull consumers do not auto reconnect, if nats server is re-started or there is temporary disconnected network. Is that correct? If yes, how to auto reconnect the durable consumer?

I am using the new jetstream package.

### What is the proposed change?

How to auto reconnect the durable consumer?

**Comment by piotrpio** [comment]
Hello @tamalsaha, thanks for reporting the issue. It is definitely a bug introduced in previous releases. I have a fix ready here: https://github.com/nats-io/nats.go/pull/1428

Once it' merged it will be included in the next release.

**Comment by piotrpio** [comment]
The PR was merged, it's available in `nats.go@v1.31.0`
