### ISSUE TITLE
CreateStreamIfAbsent or CreateOrUpdateStream api

### ISSUE THREAD

**Issue by tamalsaha** [nats-io/nats.go#1430]
### What motivated this proposal?

Please add an api that will create a Stream is not exists and return it if exists.  Hence the `CreateStreamIfAbsent` api. This api is needed to auto create the stream from my application. It was surprising to not have this api.

`CreateOrUpdateStream` might nice to keeping in sync with the `CreateOrUpdateConsumer` api. Though, I have not felt th need for this api.

### What is the proposed change?

Something like this is what I am doing.

```
func ensureStream(stream string, jsOpts ...jetstream.JetStreamOpt) (jetstream.Stream, error) {
	js, err := jetstream.New(mgr.nc, jsOpts...)
	if err != nil {
		return nil, err
	}

	s, err := js.Stream(context.TODO(), stream)
	if errors.Is(err, jetstream.ErrStreamNotFound) {
		s, err = js.CreateStream(context.TODO(), jetstream.StreamConfig{
			Name:     stream,
			Subjects: []string{stream + ".*"},
		})
	}
	return s, err
}
```

**Comment by piotrpio** [comment]
Hey @tamalsaha, thanks for submitting the issue. `CreateOrUpdateStream` function was merged a momento ago: https://github.com/nats-io/nats.go/pull/1395

It will be included in the next release.
