### ISSUE TITLE
Add stream compression option for KV

### ISSUE THREAD

**Issue by aldiesel** [nats-io/nats.go#1434]
### What motivated this proposal?

If the KV store is storing similar objects that are repeated compression can save a lot of disk space.
The stream config exposes the compression, but the KV config does not.
Saving disk space and less IO to disk.
Ideally the objects could also be sent over the wire as compressed objects if it is on a per key basis instead of the whole block, but not sure of the implementation. This could be a separate feature request.

### What is the proposed change?

Expose the stream compression option in the KV config.

### Who benefits from this change?

Everyone using KV store

**Comment by piotrpio** [comment]
Hey @aldiesel, thanks for creating the issue. This looks interesting, let us discuss that and get back to you.

**Comment by piotrpio** [comment]
We've accepted the proposal. We'll also be updaing object sotre with similar behavior: https://github.com/nats-io/nats-architecture-and-design/issues/253

I'll update the go client soon, this should make it into the next release.

**Comment by piotrpio** [comment]
KV compression in available in [nats.go@v1.32.0](https://github.com/nats-io/nats.go/releases/tag/v1.32.0)
