### ISSUE TITLE
`JetStreamManager` list methods swallow error response

### ISSUE THREAD

**Issue by maciej-karas-form3** [nats-io/nats.go#1438]
### What version were you using?

v1.30.2

### What environment was the server running in?

This API design problem, not related to environment

### Is this defect reproducible?

This API design problem

### Given the capability you are leveraging, describe your expectation?

The API for `JetStreamManager` should return encountered errors in subsequent calls to server. This is important for distinguishing error response from 0 element response. At the moment there is no way to do it.

### Given the expectation, what is the defect you are observing?

`StreamsInfo`, `Streams`, `StreamNames`, `ConsumersInfo`, `Consumers` and `ConsumersNames` all are returning only channel with positive response i.e.

```go
// Streams can be used to retrieve a list of StreamInfo objects.
Streams(opts ...JSOpt) <-chan *StreamInfo

// StreamNames is used to retrieve a list of Stream names.
StreamNames(opts ...JSOpt) <-chan string
```

Underlying `streamLister.Err()` method is not called and so when any error happens we just close the channel.

**Comment by piotrpio** [comment]
Helllo @maciej-karas-form3, thank you for creating the issue. You're right, the design here is flawed. In the new JetStream API APIs for listing streams and consumers were modified to enable checking for errors: https://github.com/nats-io/nats.go/blob/main/jetstream/jetstream.go#L643C84-L643C84

E.g. `ListStreams()` returns `StreamInfoLister`:
```go
StreamInfoLister interface {
	Info() <-chan *StreamInfo
	Err() error
}
```

I'm not sure we're able to change the legacy API to enable this without introducing breaking change though.

**Comment by jnmoyne** [comment]
I think the proper solution here is simply to use the new API, which is much better and easier to use anyways so worth the small migration effort IMHO.

**Comment by maciej-karas-form3** [comment]
@piotrpio and @jnmoyne thanks for response. We will try to integrate with the new API then. This issue can be closed now
