### ISSUE TITLE
No heartbeat on MessagesContext is not instance of `ErrNoHeartbeat`

### ISSUE THREAD

**Issue by olpie101** [nats-io/nats.go#1467]
### Observed behavior

When calling `Next` on a `jetstream.MessagesContext`, if it returns a `nats: no heartbeat received` it does not return `true` for `errors.Is(err, nats.ErrNoHeartbeat)`.

```go
// .... create consumer
it, err := consumer.Messages(jetstream.PullExpiry(expTime))
if err != nil {
	return err
}
defer it.Stop()

for {
	msg, err := it.Next()
	if err != nil {
                  // This always returns false even if the error matches "nats: no heartbeat received"
		 if errors.Is(err, nats.ErrNoHeartbeat) {
                     fmt.Println("next msg heartbeat error")
                 }
		return err
	}
}

```

### Expected behavior

If the error returned is a heartbeat error it should validate as true when checking if the error is a `nats.ErrNoHeartbeat`

### Server and client version

server: 2.10.3
client: github.com/nats-io/nats.go 1.31.0

### Host environment

**Server**
Managed Kubernetes (AKS) 1.25.11
OS: Ubuntu 22.04
Container runtime: containerd 202307.12.0
Architecture: amd64

**Client**
MacOS 12.5.1
CPU: M1 Pro
Go version: 1.21.3

### Steps to reproduce

- create consumer
- call `consumer.Messages` with `PullExpiry` set to `time.Millisecond`
- call `Next` on the `MessagesContext`
- an error should be returned. check `errors.Is(err, nats.ErrNoHeartbeat)`, it will be false

Using the example in observed behaviour section set `expTime` to `time.Millisecond`

**Comment by olpie101** [comment]
Look through `jetstream/options.go` I notice that the check for `configureMessages` on the `PullExpiry` Option, the potential error message doesn't match the codified behavior.

```go
func (exp PullExpiry) configureMessages(opts *consumeOpts) error {
	expiry := time.Duration(exp)
	if expiry < 0 {
		return fmt.Errorf("%w: expires value must be at least 1s", ErrInvalidOption)
	}
	opts.Expires = expiry
	return nil
}
```

based on the error message it appears that pull expiry should be at least 1 second by the if check allows anything larger than 0. Is this the expected behaviour?

**Comment by piotrpio** [comment]
Hey @olpie101, thanks for submitting the issue:
1. About `ErrNoHeartbeat` Since the new `jetstream` package aims to replace the JetStream implementation from `nats` package, you should be comparing errors to the error variables from `jetstream`, not `nats`. So instead of:
```go
errors.Is(err, nats.ErrNoHeartbeat)
```
you should have:
```go
errors.Is(err, jetstream.ErrNoHeartbeat) {
```

2. About the PullExpiry validation - you are right, this is a bug. Expiry should be larger than 1s. I'll create a fix for that.

**Comment by olpie101** [comment]
@piotrpio thank you for the clarification. Changing to the jetstream instance of the error worked.
