### ISSUE TITLE
Provide TLS example code

### ISSUE THREAD

**Issue by glycerine** [nats-io/nats.go#147]
Learning nats, it took alot of research and slack chat to nail down TLS connection configuration. It would be great if there were runnable example code in the examples/ directory.

**Comment by derekcollison** [comment]
We can always do better of course, but this section in the README was not helpful?

https://github.com/nats-io/nats#tls

**Comment by glycerine** [comment]
Yes, that certainly was helpful. It took a while to discover it though.

**Comment by derekcollison** [comment]
Good feedback, thanks.

**Comment by mcqueary** [comment]
It would probably be easy enough to adapt something from the unit tests.

**Comment by glycerine** [comment]
https://github.com/glycerine/tmframe/blob/master/archiver/tls.go  is my standard re-used tls-code-for-nats these days. Feel free to copy it; it is MIT licensed.

**Comment by derekcollison** [comment]
```go
nc, err := nats.Connect("tls://demo.nats.io:4443")
```
