### ISSUE TITLE
Data Race in Jetstream Consume

### ISSUE THREAD

**Issue by princjef** [nats-io/nats.go#1470]
### Observed behavior

When upgrading from nats.go 1.30.2 to 1.31.0, we are starting to see consistent races detected in tests when calling the `Consume()` API on a `jetstream.Consumer`. The race stack is included below:

```
Write at 0x00c000a81110 by goroutine 102:
  runtime.mapdelete_faststr()
      /opt/hostedtoolcache/go/1.20.3/x64/src/runtime/map_faststr.go:301 +0x0
  github.com/nats-io/nats.go/jetstream.(*pullSubscription).cleanup()
      /home/cloudtest/go/pkg/mod/github.com/nats-io/nats.go@v1.31.0/jetstream/pull.go:846 +0x228
  github.com/nats-io/nats.go/jetstream.(*pullSubscription).pullMessages()
      /home/cloudtest/go/pkg/mod/github.com/nats-io/nats.go@v1.31.0/jetstream/pull.go:810 +0x224
  github.com/nats-io/nats.go/jetstream.(*pullConsumer).Consume.func3()
      /home/cloudtest/go/pkg/mod/github.com/nats-io/nats.go@v1.31.0/jetstream/pull.go:359 +0x58

Previous read at 0x00c000a81110 by goroutine 103:
  runtime.mapaccess1_faststr()
      /opt/hostedtoolcache/go/1.20.3/x64/src/runtime/map_faststr.go:13 +0x0
  github.com/nats-io/nats.go/jetstream.(*orderedConsumer).Consume.func2()
      /home/cloudtest/go/pkg/mod/github.com/nats-io/nats.go@v1.31.0/jetstream/ordered.go:144 +0x304

Goroutine 102 (running) created at:
  github.com/nats-io/nats.go/jetstream.(*pullConsumer).Consume()
      /home/cloudtest/go/pkg/mod/github.com/nats-io/nats.go@v1.31.0/jetstream/pull.go:359 +0x10ea
  github.com/nats-io/nats.go/jetstream.(*orderedConsumer).Consume()
      /home/cloudtest/go/pkg/mod/github.com/nats-io/nats.go@v1.31.0/jetstream/ordered.go:124 +0xa70
  <product code>

Goroutine 103 (running) created at:
  github.com/nats-io/nats.go/jetstream.(*orderedConsumer).Consume()
      /home/cloudtest/go/pkg/mod/github.com/nats-io/nats.go@v1.31.0/jetstream/ordered.go:129 +0xbe5
  <product code>
```

The race appears to be in the `subscriptions` map. The ordered consumer makes a side call to the underlying pull consumer [here](https://github.com/nats-io/nats.go/blob/main/jetstream/ordered.go#L124) and then starts a goroutine that accesses the `subscriptions` map on that consumer [here](https://github.com/nats-io/nats.go/blob/main/jetstream/ordered.go#L144C29-L144C64). However, the underlying pull consumer spins off a background goroutine [here](https://github.com/nats-io/nats.go/blob/main/jetstream/pull.go#L359) that does a cleanup internally, which deletes an entry in the `subscriptions` map [here](https://github.com/nats-io/nats.go/blob/main/jetstream/pull.go#L846). The map should probably have a mutex if it is going to be used in this way.

### Expected behavior

No data races are observed

### Server and client version

nats.go 1.31.0

### Host environment

- 64-bit Ubuntu Linux
- go 1.20.3

### Steps to reproduce

1. Enable golang race detector
2. Create a new `JetStream` with [`New`](https://pkg.go.dev/github.com/nats-io/nats.go@v1.31.0/jetstream#New)
3. Call [`Stream()`](https://pkg.go.dev/github.com/nats-io/nats.go@v1.31.0/jetstream#StreamManager) on that `JetStream`
4. Call [`OrderedConsumer()`](https://pkg.go.dev/github.com/nats-io/nats.go@v1.31.0/jetstream#StreamManager) on that `Stream`
5. Call [`Consume`](https://pkg.go.dev/github.com/nats-io/nats.go@v1.31.0/jetstream#Consumer) on that ordered consumer

**Comment by Jarema** [comment]
Hey.
I'm taking a look into this.
Thanks for the report.

**Comment by piotrpio** [comment]
Fixed in https://github.com/nats-io/nats.go/pull/1497 and available in latest release ([nats.go@v1.32.0](https://github.com/nats-io/nats.go/releases/tag/v1.32.0))
