### ISSUE TITLE
Provide script (or documentation) to generate TLS client and server certs

### ISSUE THREAD

**Issue by glycerine** [nats-io/nats.go#149]
It took about a day to do this on my own. If folks needing to secure their nats cloud traffic with TLS for the first time had a script to generate the Certificate Authority as well as the server and client side certs and keys, that would be a huge boon to usability.

**Comment by andrewtw** [comment]
I believe this procedure is extremely standard for Golang developers and no need to build this function in the package.

**Comment by mcqueary** [comment]
Hi folks, please vote this if you're interested. Meanwhile we are happy to review a PR for this if someone wants to contribute an example.

**Comment by glycerine** [comment]
Suggestion: cockroach db is open source under an Apache2 license, written in Go, and already implements functionality to generate certs. I would borrow the cert generating code from them and fashioning a little standalone utility; it's already tested, known to work, and most significantly, already written. See for example

https://github.com/cockroachdb/cockroach/blob/master/security/certs_test.go#L32

**Comment by derekcollison** [comment]
https://github.com/FiloSottile/mkcert
