### ISSUE TITLE
ClosedHandler not called on channel based subscriptions

### ISSUE THREAD

**Issue by twoism** [nats-io/nats.go#1506]
### Observed behavior

This might be by design but I could not find any code comments or docs around this behavior. It seems that the code path for calling the `done` handler as it is named internally, only happens when subscriptions with a handler are used. 

At first I thought this might be because on channel based subscriptions, the user is in control of the channel's lifecycle. Then I found it puzzling that `Subscription.IsValid()` works in both channel and handler versions, as that means the internals are aware of the subscription state.

If this is by design, I think it may warrant some documentation, and if not, here are a couple test cases that demonstrate the behavior :)

### Expected behavior

That the `ClosedHandler` be called when `Drain` or `Unsubscribe` is called on the `Subscription`.

### Server and client version

Latest

### Host environment

Apple Silicon 

### Steps to reproduce

```go
func TestSubscribeClosedHandler(t *testing.T) {
	t.Parallel()
	topic := "test.topic"
	s, nc := setupConn(t, 4223)
	defer s.Shutdown()

	sub, err := nc.Subscribe(topic, func(msg *nats.Msg) {})
	assert.NoError(t, err)
	closed := make(chan bool, 1)
	sub.SetClosedHandler(func(sub string) {
		closed <- true
	})

	assert.NoError(t, sub.Unsubscribe())
	assert.False(t, sub.IsValid())
	assert.True(t, <-closed)
}

func TestChanSubscribeClosedHandler(t *testing.T) {
	t.Parallel()
	topic := "test.topic"
	s, nc := setupConn(t, 4224)
	defer s.Shutdown()
	rc := make(chan *nats.Msg)

	sub, err := nc.ChanSubscribe(topic, rc)
	assert.NoError(t, err)
	closed := make(chan bool, 1)
	sub.SetClosedHandler(func(sub string) {
		closed <- true
	})

	assert.NoError(t, sub.Unsubscribe())
	assert.False(t, sub.IsValid())
	close(rc)                // attempt to see if this triggers the closed handler
	assert.True(t, <-closed) // never received, blocks forever
}
```

**Comment by piotrpio** [comment]
Hello @twoism, thank you for creating the issue. This was now fixed as part of another PR and will be available in the next release.

**Comment by piotrpio** [comment]
Fixed in [nats.go@v1.32.0](https://github.com/nats-io/nats.go/releases/tag/v1.32.0)
