### ISSUE TITLE
Why Jetstream domain is not exposed to the client?

### ISSUE THREAD

**Issue by dpotapov** [nats-io/nats.go#1510]
### Proposed change

extend the serverInfo struct with the `Domain` field and provide an accessor:

```
// The INFO block received from the server.
type serverInfo struct {
    ...
    Domain            string   `json:"domain,omitempty"`
}

// GetJetstreamDomain returns the Jetstream domain provided by the server in the INFO message.
func (nc *Conn) GetJetstreamDomain() string {
	nc.mu.RLock()
	defer nc.mu.RUnlock()
	return nc.info.Domain
}
```

### Use case

Allows the application to be aware of the Jetstream topology.

### Contribution

I may contribute

**Comment by derekcollison** [comment]
I think it is in AccountInfo()

<img width="726" alt="image" src="https://github.com/nats-io/nats.go/assets/90097/4e2269d7-7844-4870-97b5-a73478b02065">

**Comment by dpotapov** [comment]
Ah, ok, I thought accounts are not bound to a single domain... not clear from the documentation...

**Comment by derekcollison** [comment]
When you connect directly to a NATS system, domains do not need to really be known. They only come into play when you connect multiple NATS systems via leafnodes. Then domains are used to interact with remote JetStream assets.
