### ISSUE TITLE
invalid jetstream publish response

### ISSUE THREAD

**Issue by yeqown** [nats-io/nats.go#1512]
### Observed behavior

if _, err = p.js.PublishMsg(msg); err != nil {
	return err
}

then it returns the above error, I found this error message from nats.go and found it was defined as `ErrInvalidJSAck`, and used here: 
![image](https://github.com/nats-io/nats.go/assets/27146233/24166c99-816a-4613-8b96-82bb59f29e15)

These two code blocks return the error but without the root cause, it's uncertain while locating the error, what's worse the error is not stable enough to reproduce locally.

I'm using the remote nats-server to eliminate differences, the client is using the same code to reproduce, but it's not reproduced yet.

### Expected behavior

I wonder dose this error will take any effect. Can I ignore this error directly, if not what could I do to locate the error cause and fix it?

### Server and client version

server = 2.10.5
client = 1.28.0 / 1.27.1

### Steps to reproduce

I could not reproduce it on my local yet

**Comment by Jarema** [comment]
Thanks for filling the issue!

While it's always nice to know what caused this error, I don't think its necessary to improve the error handling and wrapping the `Unmarshal` error.

Are you interested in contribution here?

**Comment by yeqown** [comment]
> Thanks for filling the issue!
> 
> While it's always nice to know what caused this error, I don't think its necessary to improve the error handling and wrapping the `Unmarshal` error.
> 
> Are you interested in contribution here?

Thanks for replying.

I do not mean to wrap error here, I just wonder what caused this error. Actually, I want to figure out why,  and any information to resolve this error. Now, It happens so frequently in my code.

Of course, I'd love to contribute here if it's really necessary.

**Comment by yeqown** [comment]
@Jarema I log the detail of the `ackResp` and got this:
![image](https://github.com/nats-io/nats.go/assets/27146233/6c8f09fc-1ac8-4261-8026-50c71cd04f07)

Can you help me to analyze this deeply?

all changes here, checkout from v1.31: https://github.com/nats-io/nats.go/compare/main...yeqown:nats.go:feat/debug

**Comment by piotrpio** [comment]
Doubled response from the server definitely looks suspicious. Could you give us some more details so we may try and reproduce? It would be nice to have:
- debug/trace server logs from when the publish and duplicated ack happen
- stream config (mainly around policies)
- are you using plain `js.Publish()` or do you use any additional options?

**Comment by yeqown** [comment]
> Doubled response from the server definitely looks suspicious. Could you give us some more details so we may try and reproduce? It would be nice to have:
> 
> * debug/trace server logs from when the publish and duplicated ack happen
> * stream config (mainly around policies)
> * are you using plain `js.Publish()` or do you use any additional options?

@piotrpio 

1.  logs with inbox filtered
![image](https://github.com/nats-io/nats.go/assets/27146233/3e48cd61-0e32-432c-b1c7-a323e3ff1914)

2. Output of `nats str info`:
```bash
Information for Stream local_account created 2023-09-11 18:22:57

              Subjects: local_account.>
              Replicas: 1
               Storage: File

Options:

             Retention: Limits
       Acknowledgments: true
        Discard Policy: Old
      Duplicate Window: 2m0s
     Allows Msg Delete: true
          Allows Purge: true
        Allows Rollups: false

Limits:

      Maximum Messages: unlimited
   Maximum Per Subject: unlimited
         Maximum Bytes: unlimited
           Maximum Age: unlimited
  Maximum Message Size: unlimited
     Maximum Consumers: unlimited

State:

              Messages: 84,468
                 Bytes: 28 MiB
        First Sequence: 1 @ 2023-09-12 14:57:25 UTC
         Last Sequence: 84,468 @ 2024-01-09 09:28:46 UTC
      Active Consumers: 37
    Number of Subjects: 8
```

3. yes, it's pure
![image](https://github.com/nats-io/nats.go/assets/27146233/299fb5bf-e5d2-4143-8c07-88e5261fdd0d)
![image](https://github.com/nats-io/nats.go/assets/27146233/eee804f2-4dc0-4900-b940-3b673f67403a)

**Comment by yeqown** [comment]
😂😂😂 I thought I have figured out:

The message published was `Respond` at another subscribing client. It called `msg.Respond`

```go
// Respond allows a convenient way to respond to requests in service based subscriptions.
func (m *Msg) Respond(data []byte) error {
	if m == nil || m.Sub == nil {
		return ErrMsgNotBound
	}
	if m.Reply == "" {
		return ErrMsgNoReply
	}
	m.Sub.mu.Lock()
	nc := m.Sub.conn
	m.Sub.mu.Unlock()
	// No need to check the connection here since the call to publish will do all the checking.
	return nc.Publish(m.Reply, data)
}
```

**Comment by yeqown** [comment]
@Jarema I have make a PR to wrapping JS publish error, would you mind to push it going on 👏?
