### ISSUE TITLE
JetStreamContext not go routine safe?

### ISSUE THREAD

**Issue by justinrush** [nats-io/nats.go#1520]
### Observed behavior

`JetStreamContext` doesn't seem to be go routine safe. I was storing it on a struct and then using it in multiple go routines and go race finds issues in the js code. I suspect this is by design, but I dug through go doc on the structs and interfaces and nothing mentions this.

### Expected behavior

I expected the go doc on the `JetStreamContext` (such as [here](https://pkg.go.dev/github.com/nats-io/nats.go@v1.31.0#JetStreamContext) to mention that this is not go routine safe and needs to be protected by a mutex if its needed to be passed between funcs that may execute in parallel. Ideally you could also document the cost of creating the `JetStreamContext` by calling the `nats.Conn.JetStream` method. I assumed, perhaps incorrectly, that this was expensive and thus called it once and stored the result as a struct member.

### Server and client version

```
	github.com/nats-io/nats-server/v2 v2.10.9
	github.com/nats-io/nats.go v1.31.0
```

### Host environment

Go 1.21

### Steps to reproduce

I can provide an example if needed, but I suspect this will be clear to maintainers, LMK.

**Comment by Jarema** [comment]
Thanks for filling the issue.

We're checking it right now, as it should be concurrent safe, but did you consider using the new [JetStream API](https://github.com/nats-io/nats.go/blob/main/jetstream/README.md) ? 
As it seems you're mentioning the old API here.

**Comment by piotrpio** [comment]
Hello @justinrush - could you provide an example which causes the data races?

**Comment by justinrush** [comment]
I just tracked this down to an issue in my test code - sorry for that.

However, thanks for pointing out we should be using the new lib - a drop in replacement but I like how the funcs take contexts.
