### ISSUE TITLE
Add stream compression option for object store buckets

### ISSUE THREAD

**Issue by johbar** [nats-io/nats.go#1536]
### Proposed change

An S2 compression option is available for Jetstream streams and KV buckets. However, it is still missing for the object store. We should add it.

### Use case

Storing compressible content in the object store.

### Contribution

The change seems very simple as  #1451 can be used as blueprint. I can do that.

**Comment by Jarema** [comment]
We agree that this proposal is a good idea. 
Thank you for that, and for the PR!

We will take a look shortly, as we need to also update ADR spec.
