### ISSUE TITLE
With a NATS server with JetStream disabled `jetstream` package functions always returns `context deadline exceeded`

### ISSUE THREAD

**Issue by johbar** [nats-io/nats.go#1565]
### Observed behavior

When starting a NATS server with JetStream _disabled_, the `jetstream` package client operations always seem to return `context.deadlineExceededError` instead of specialized errors.

### Expected behavior

Functions like `AccountInfo(ctx context.Context)` should return `ErrJetStreamNotEnabled`.

### Server and client version

github.com/nats-io/nats.go v1.33.1
server version 2.10.11

### Host environment

go version go1.22.0 linux/amd64
Server running on Podman v4.8.3

### Steps to reproduce

Start Server with `podman run --rm -it -p 4222:4222 nats:latest`.

Quick and dirty client code:

```go
package main

import (
	"context"
	"testing"

	"github.com/nats-io/nats.go"
	"github.com/nats-io/nats.go/jetstream"
)

func TestNatsClient(t *testing.T) {
	nc, _ := nats.Connect("nats://localhost:4222")
	js, _ := jetstream.New(nc)
	_, err := js.AccountInfo(context.TODO())
	t.Error(err)
}
```

Output:

```text
--- FAIL: TestNatsClient (5.00s)
    .../client_test.go:15: context deadline exceeded
```

I also tried to unwrap and convert the error with no success.

**Comment by piotrpio** [comment]
Hello @johbar , thank you for submitting the issue. I'll take a look at this.

**Comment by johbar** [comment]
Hi @piotrpio, thank you for that investigation.

I considered opening another issue requesting something like a `IsJetStreamEnabled` method I could call on a `NatsConnection` object. But then I realized: Due to the dynamic distributed nature of NATS it is not possible to say if JetStream is "enabled in the cluster". At any point of time JetStream-enabled nodes can join or leave the cluster. So this is exactly the issue here.

Nevertheless, it is a bit unsatisfying if we only get a timeout, especially in a rather static clustered setup, that could, for whatever reason, be misconfigured. But if it is not possible to return a more specific error, I think at least some docs should be revised. Like [ErrJetStreamNotEnabled](https://github.com/nats-io/nats.go/blob/main/jetstream/errors.go#L74) should have a hint when _not_ to expect that error. Also the [AccountInfo](https://github.com/nats-io/nats.go/blob/main/jetstream/jetstream.go#L44C2-L49C15) comment should be clear about that.

**Comment by piotrpio** [comment]
You're right, I'll update the docs to make it clear 👍
