### ISSUE TITLE
undefined: errors.Join

### ISSUE THREAD

**Issue by 780662833** [nats-io/nats.go#1580]
### Observed behavior

![image](https://github.com/nats-io/nats.go/assets/26198054/eea6c844-11dc-4af4-8ce6-ad81d31040bb)

### Expected behavior

go1.18 测试 nats 报错

### Server and client version

go1.18  github.com/nats-io/nats.go v1.33.0

**Comment by wallyqs** [comment]
recommend to bump Go runtime to at least Go 1.19

**Comment by Jarema** [comment]
nats.go module requires Go 1.20.
Please bump your Go version.
Closing the issue.
