### ISSUE TITLE
Listing an Object Store after deleting all objects inside it hangs

### ISSUE THREAD

**Issue by robinkb** [nats-io/nats.go#1610]
### Observed behavior

After deleting all of the files in an Object Store, attempting to list the objects inside the store hangs.

### Expected behavior

I expect listing an object store with only deleted objects to return an empty array, just like listing a fresh empty store.

### Server and client version

nats-server v2.10.12
nats.go v1.34.1

### Host environment

Linux conswole 6.8.4-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC GNU/Linux

### Steps to reproduce

I have created a repository with a file that you can `go run` to reproduce the problem.
https://github.com/robinkb/nats-go-bug-unending-list

**Comment by robinkb** [comment]
Interestingly, as long as the store has a single object, listing objects always works. For my use-case, I'm creating a zero-length dummy object in every object store that I create. The rest of the code ignores the dummy object. Annoying, but it works for now.

**Comment by Jarema** [comment]
Thanks for the report. We will take a look into this.

**Comment by piotrpio** [comment]
@robinkb Thanks again for reporting the issue. It turned out to be a bug in nats-server, fixed here: https://github.com/nats-io/nats-server/pull/5339

The fix will be included in the next server release.
