### ISSUE TITLE
kv is created with OLD discard policy using jetstream pkg while with nats pkg it gets NEW

### ISSUE THREAD

**Issue by nitzan-entro** [nats-io/nats.go#1615]
### Observed behavior

kv is created with OLD discard policy using jetstream pkg while with nats pkg it gets NEW

### Expected behavior

both pkgs shall have the same resolution

### Server and client version

2.10.9
1.34.1

**Comment by piotrpio** [comment]
Hey @nitzan-entro, thank you for finding this I created a PR fixing the problem.
