### ISSUE TITLE
add new encoder interface with less allocations

### ISSUE THREAD

**Issue by costela** [nats-io/nats.go#1649]
### Proposed change

Add an additional interface for use with `nats.EncodedConn` that allows better allocation control than `nats.Encoder`'s `Encode()`.

### Use case

The `nats.Encoder` interface, in particular the `Encode()` method, makes it very difficult to amortize allocation costs by returning a new byte slice for every call.

Using something like
```go
type AnotherEncoder interface {
  Decode(subject string, io.Reader, vPtr any) error
  Encode(subject string, v any, io.Writer) error
}
```
would allow the encoder implementation to use a bufferpool when encoding.

Am I overlooking something obvious here? :thinking: 

### Contribution

I'd be willing to give this a try if the approach sounds acceptable :+1:

**Comment by ripienaar** [comment]
We are working on replacing the encoded connections feature with the more commonly used middleware pattern

Some early draft work here but we are still refining 

https://github.com/nats-io/nats-architecture-and-design/pull/272

**Comment by costela** [comment]
@ripienaar thanks for the pointer! I overlooked that repo when searching for prior issues. Can we leave this open until that design is finalized?

**Comment by ripienaar** [comment]
We'd probbly forget to close this one and it becomes just one of the pile :) Rest assured we are working on it

**Comment by costela** [comment]
gotcha!
