### ISSUE TITLE
Publish RetryAttempt and RetryWait not working as expected

### ISSUE THREAD

**Issue by sourabhaggrawal** [nats-io/nats.go#1664]
### Observed behavior

 js.Publish("test", []byte("hi"), nats.RetryWait(5*time.Second), nats.RetryAttempts(10))
It gives up at first attempt itself after waiting for 5 second.

### Expected behavior

This supposed to retry 10 times if there is "no responder" error and should retry 5 times before it gives up. So after 50 seconds it should give up if there is "no responder" error on every attempt.

### Server and client version

nats-server 2.10.3
nats-client 1.35.0

### Host environment

Mac OS

### Steps to reproduce

Publish a message to subject which is not associated to stream, configure retry attempt and retrywait.

 js.Publish("test", []byte("hi"), nats.RetryWait(5*time.Second), nats.RetryAttempts(10))

**Comment by souravagrawal** [comment]
Raised a PR for same here https://github.com/nats-io/nats.go/pull/1667

**Comment by Jarema** [comment]
The current bahavior is restrained by `TTL` that can be set by `nats.AckWait()`.
The number of retries defines the upper bound for number of retries. `TTL` still applies.

**Comment by souravagrawal** [comment]
Any specific reason why it only retries in case of "No Responder" case. There can be many other cases too where user expect nats to retry publish.
Also this retry is not there in AsyncPublish method of go, however it is there in .net client https://github.com/nats-io/nats.net.v2/blob/ccc212f764508f11a3154ade8d29bfdbb772de02/src/NATS.Client.JetStream/NatsJSContext.cs#L120

**Comment by Jarema** [comment]
Only retrying on `no responders` is safe.
Retrying on `Timeout` can lead to duplicate messages in the stream, as the operation can finish after client timeout window.

.net `async publish` is a publish that waits for the ack. The `async` part comes from the idiom in .net, meaning that it's async operation from .net perspective, not NATS idioms perspective.

We're trying to find a better name for async publish, meaning - a publish that does not wait for ack, but returnes a future of a kind ;).

**Comment by sourabhaggrawal** [comment]
@Jarema Currently async publish does not support retry, is there any plan to fix/add later.

**Comment by Jarema** [comment]
@sourabhaggrawal at least the new `jetstream` package does support retries on async publish. Not sure about the legacy one.
Will defer that one to @piotrpio

**Comment by sourabhaggrawal** [comment]
Great, can you share some example for async Publish using new jetstream api ? 
TIA

**Comment by piotrpio** [comment]
Hello @sourabhaggrawal, sorry for taking so long with this. Please see my reply [here](https://github.com/nats-io/nats.go/issues/1678#issuecomment-2265427018) for an example using new JetStream API.

We'll also be adding the retries to the old API, but I'm not yet sure it'll make it to the next release.

**Comment by joe-urciuoli** [comment]
>Only retrying on no responders is safe.
Retrying on Timeout can lead to duplicate messages in the stream, as the operation can finish after client timeout window.

So what is the recommendation if the publish times out? It seems we either could possibly get a duplicate message, or possibly no message at all. I'd prefer a duplicate for my use case.

In my case, I'm tracking edits on an object, and publishing messages as it's edited with the updated info. Say I had something like:
12:00:00 edit1 publish times out
12:00:01 edit2 publish, success

Could edit1 later overwrite edit2 if it's somehow processed after the timeout?

I'm setting `MaxMsgsPerSubject=1` and each message has the ID of the object in the subject ID.

**Comment by piotrpio** [comment]
Hello @joe-urciuoli. For your use case I think you could use message deduplication: https://docs.nats.io/using-nats/developer/develop_jetstream/model_deep_dive#message-deduplication

When publishing, you can use the `MsgId` option (when using legacy JetStream API) or `WithMsgID` to set the ID for messages. If multiple publishes for the same message ID are received by the stream within deduplication window (`StreamConfig.Duplicates`, defaults to 2 minutes), only the first one will be stored, rest will be discarded.

**Comment by joe-urciuoli** [comment]
Thanks @piotrpio , I don't think that actually helps for my use case. In my case, I'm only keeping the last message received due to `MaxMsgsPerSubject=1`. If edit1 gets processed _after_ edit2 (since edit1 timed out, we have no way of knowing if/when it might be processed), I'd still wind up replacing edit2 with the older edit.

Upon startup, I'm also resyncing all data with `DeliverPolicy: jetstream.DeliverLastPerSubjectPolicy`, so even if I upped `MaxMsgsPerSubject`, I'd still have a problem where I'm not actually syncing the _latest_ data.

This seems like it would be a common problem, but struggling to find a solution.

**Comment by joe-urciuoli** [comment]
I suppose if I use `MsgId` and set `StreamConfig.Duplicates` to a large enough value, and ensure I'm forming a queue in my service and waiting until I get each edit Ack'd before publishing the next edit, it should _almost_ be guaranteed to work. That seems excessive. I wish there was a way the stream client could specify a `seqNo` and Jetstream would drop any messages if the seqNo is lower than the seqNo Jetstream currently knows about.

**Comment by joe-urciuoli** [comment]
https://github.com/nats-io/nats.go/blob/50e615333dbe1cb7ccf8141ba94d4375bd050de9/jetstream/publish.go#L46-L47

specifying `id` and `lastMessageID` seems like it would solve this problem. However, this is at the stream level. That's probably OK.
