### ISSUE TITLE
Client logs unmarshal errors

### ISSUE THREAD

**Issue by sammy007** [nats-io/nats.go#1668]
### Observed behavior

nats.go logs unmarshal errors using built in log

```
nats: Got an error trying to unmarshal: json: cannot unmarshal object into Go struct field
```

### Expected behavior

It should not log itself, return error instead which caller will log the way it prefers.

### Server and client version

1.36

**Comment by wallyqs** [comment]
How did you run into this error? Using JetStream in some way?

**Comment by sammy007** [comment]
> How did you run into this error? Using JetStream in some way?

I am using stream in my app and normal messages as well, currently I am trying to find where the bug in my app is :)

**Comment by Jarema** [comment]
It would be really helpful to know which API call causes this, and see some snippet.

**Comment by wallyqs** [comment]
can you share the stream info of the stream?

**Comment by wallyqs** [comment]
you can also setup your own nats.ErrorHandler to override the default one to try to peek further at the json error

**Comment by sammy007** [comment]
Well, it is not a stream. In a json encoded connection `Publish` where I put a struct which contains [][]*SomeStruct as a field.

The struct is:

```
type A struct {
        .. SKIPPED ...
	B      [][]*C
}
```

```
json: cannot unmarshal object into Go struct field A.B of type []*mypackage.C on connection [193] for subscription on "mySub"
```

The receiver is:

```
_, err = s.nec.BindRecvChan("mySub", mySubCh)
```

**Comment by sammy007** [comment]
```
mySubCh chan A
_, err = s.nec.BindRecvChan("mySub", mySubCh)
```

So this is the issue. No idea why it can't deserialize such structure. The structure is nothing special and serializes correctly.

**Comment by sammy007** [comment]
Simlar to #245 it seems, but in my case I am just using normal two dimensional array.

**Comment by sammy007** [comment]
Well, should be a separate issue anyway.
