### ISSUE TITLE
Make JS Consumer deletion on Unsubscribe() / Drain() optional

### ISSUE THREAD

**Issue by itsofirblink** [nats-io/nats.go#1670]
### Proposed change

```
sub.jsi.dc = true
```
change `true` based on an input provided (can be another `SubOpt`, another input parameter, configuration of JS connection on its own) or any other way

### Use case

When running on multiple containers that consume from the same worker stream, the first container always creates the **consumer** by subscribing and going into the `upsertConsumer` flow.

if this container happens to scale down the consumer will be deleted as the `sub.jsi.dc` is `true` and all of the other containers are left without the option to consume messages from this consumer (as its deleted).

### Contribution

I can contribute a PR with a possible solution

**Comment by Jarema** [comment]
Thank you for filling the issue.

This is a known problem of the legacy JetStream API.
We suggest using the new one, in [jetstream](https://github.com/nats-io/nats.go/blob/main/jetstream/README.md) package instead.
