### ISSUE TITLE
packets lost: subscribe to more topics and get message packets quickly. The first message packet of some topics is lost.

### ISSUE THREAD

**Issue by chgz** [nats-io/nats.go#1680]
### Observed behavior

![20240719105700](https://github.com/user-attachments/assets/339a1c54-da7a-4b34-a8d6-b0b7b408d1f1)

In my test scenario, service A received 2,000 connections, and each connection completed the request and response through these two topics.
During the test, there was no waiting time, and the message was responded to immediately. In each test, the first packet of dozens of connections was lost, and the other packets were fine.

All processes, including NATS, are in the same host, so the possibility of network problems can be ruled out.
Since only the first packet is lost, we don't need to consider the configuration of buffer or queue size.

### Expected behavior

When used correctly, there will be no packet loss.

### Server and client version

nats server  v2.10.11
test code:
github.com/nats-io/nats-server/v2 v2.10.16
github.com/nats-io/nats.go v1.35.0

**Comment by chgz** [comment]
![20240719110853](https://github.com/user-attachments/assets/3ae3526c-b074-4adc-b3ca-88c7f405ed08)
I counted and output the message packets and found that at position 1 in the figure, all packets were sent, but at position 2, fewer packets were received.

**Comment by chgz** [comment]
![20240719111302](https://github.com/user-attachments/assets/72a83465-b954-414e-8cc7-cc7fa6244ca8)
Finally,  add sleep 500ms after Subscribe, and the first packet loss will not occur.
Is there any critical condition problem?

**Comment by chgz** [comment]
Sorry, I submitted to the wrong place.

**Comment by wallyqs** [comment]
is the chansubscribe channel unbuffered?
