### ISSUE TITLE
Explicit support for auth change during reconnect

### ISSUE THREAD

**Issue by tommyjcarpenter** [nats-io/nats.go#1694]
### Proposed change

I am experiencing "fuzzy" behavior regarding the following. Fuzzy as in, the code works when the NATS client is connected to a single URL, but it doesnt work when connected to multiple URLs. 

We are using the NATS Auth Callout, but client side, the Password field needs to change each time the disconnect callback is called, which happens when the auth callout JWTs expire (eg hourly). Specifically, our autth callout backend is interpreting a "password" specific to our in house IAM stack, and those *also* expire. 

Because our auth callout tokens expire every hour, our `disconnectedCB` is called every hour. And in that, we want to change `conn.Opts.Password` so that it uses the new password (the client has to regenerate one at this time) on the reconnection attempt (see below, the actual auth call is made after the reconnected callback, so "hook wise", we already have a hook at the right spot.)

My functions currently looks like this:

```go
func (gb *Base) tokenAndConnect(ctx context.Context) (*nats.Conn, error) {
	iamCreds, err := gb.iamRuntime.GetAccessToken(ctx, &identity.GetAccessTokenRequest{})
	if err != nil {
		gb.Logger.Fatalf("failed to get access token: %v", err)
	}

	// For the auth callout, we have a sentinel and we also need an Identity token as our password
	return nats.Connect(
		gb.config.Nats.URL,
		nats.UserCredentials(gb.config.Nats.SentinelCredsFile),
		nats.UserInfo(gb.config.MsName, iamCreds.Token),
	)
}


func (gb *Base) AddNATSConn(ctx context.Context) *Base {
	nc, err := gb.tokenAndConnect(ctx)
	if err != nil {
		gb.Logger.Fatalf("failed to create Initial NATS connection: %v", err)
	}

	/*
		    Disconnect Callbacks are called when the function reconnects....
			https://github.com/nats-io/nats.go/blob/370bc4fc4cac2de8d5dbbddbb98739f9cb2d7f8b/nats.go#L2779-L2787
			The purpose of this is to get a new identityJWT before the reconnect happens

			We cant use the reconnectCB (misleading name here)
			ReconnectCB is called *after* the reconnection happens. In order to refresh the token before the reconnect,
			Doc strings for variouis callbacks:
			ReconnectedCB sets the reconnected handler called whenever the connection is successfully reconnected.
			ConnectedCB sets the connected handler called when the initial connection is established. It is not invoked on successful reconnects - for reconnections, use ReconnectedCB
			DisconnectedErrCB sets the disconnected error handler that is called whenever the connection is disconnected.
			ClosedCB sets the closed handler that is called when a client will no longer be connected.
	*/

	nc.SetDisconnectErrHandler(func(conn *nats.Conn, err error) {
		gb.Logger.Infof("NATS connection disconnected: %v. Generating new Identity JWT", err)
		iamCreds, err := gb.iamRuntime.GetAccessToken(ctx, &identity.GetAccessTokenRequest{})
		if err != nil {
			gb.Logger.Fatalf("Failed to get access token: %w", err)
		}
		
                 // *********************************!!!
                 // doesnt work in multi URL case but works fine when you seed the client with a single NATS server
		conn.Opts.Password = iamCreds.Token
	})

	nc.SetReconnectHandler(func(conn *nats.Conn) {
		gb.Logger.Infof("NATS connection reconnected. Reconnect count %d", conn.Reconnects)
	})

	gb.NatsConn = nc
	return gb
}
```

I think it has something to do with this warning which I just saw..
https://github.com/nats-io/nats.go/blob/e3df53d7fa82d1d60335c53b66b43d9be90a8881/nats.go#L537-L538

It works in the case where the client only was given one cluster URL but not multiple. 

I eventually tracked down this call chain on reconnects:
1. the disconnect handler is called first: https://github.com/nats-io/nats.go/blob/e3df53d7fa82d1d60335c53b66b43d9be90a8881/nats.go#L2781-L2787
2. later in that function, createConn is called though I dont think this is the problematic one: https://github.com/nats-io/nats.go/blob/e3df53d7fa82d1d60335c53b66b43d9be90a8881/nats.go#L2873 
3. then later down in that function, nc.processConnectInit() is called: https://github.com/nats-io/nats.go/blob/e3df53d7fa82d1d60335c53b66b43d9be90a8881/nats.go#L2886
4. that calls sendConnect(): https://github.com/nats-io/nats.go/blob/e3df53d7fa82d1d60335c53b66b43d9be90a8881/nats.go#L2380
5. that calls connectProto https://github.com/nats-io/nats.go/blob/e3df53d7fa82d1d60335c53b66b43d9be90a8881/nats.go#L2644
6. that contains: https://github.com/nats-io/nats.go/blob/e3df53d7fa82d1d60335c53b66b43d9be90a8881/nats.go#L2551-L2566

that code makes it unclear when this `Password` change is going to be reflected. 

My fear/suspicion is that, in the multiple URL case, that `User` is populated; triggering the `if`, which is why it sends the old token, which is why it breaks. In the single URL case, that is not populated, thus triggering the `else`

I am trying to see how I can explicitly force  it to use a new password, either via setting some variable sure to be picked up, or via a callback. Maybe a flag that says "always override the auth from the connection options". 

This block might be related, I was trying to find anywhere where `nc.current.url` is set: https://github.com/nats-io/nats.go/blob/e3df53d7fa82d1d60335c53b66b43d9be90a8881/nats.go#L1821-L1827

### Use case

We are using the NATS Auth Callout, but client side, the Password field needs to change each time the disconnect callback is called, which happens when the auth callout JWTs expire (eg hourly). Specifically, our autth callout backend is interpreting a "password" specific to our in house IAM stack.

**Comment by tommyjcarpenter** [comment]
Good morning - I'd like to follow up here, as this issue is basically preventing several applications to adopt NATS in our organization.

**Comment by derekcollison** [comment]
Looping in @Jarema and @piotrpio here. This sounds reasonable especially with auth callouts growing popularity and the desire for lower bounded authN timeframes.

**Comment by piotrpio** [comment]
Hey @tommyjcarpenter. While I don't think manually changing `Opts` in `DisconnectedCb` is a good idea (it's racy as you pointed out and would set precedent for modifying other options dynamically, which we really suggest not to), there may be another straightforward solution. 

We could expose a callback options similar to `TokenHandler` option (`func TokenHandler(cb AuthTokenHandler) Option`). This callback would be called each time the client attempts to reconnect and in this callback you could easily generate the new token. The signature would look something like this (names could probably be better):
```go
func UserInfoHandler(cb AuthUserInfoHandler) Option {}
```

`AuthUserInfoHandler` would be a function returning `(string, string)` where you would generate the new password. 

Would you be satisfied with such solution?

**Comment by tommyjcarpenter** [comment]
@piotrpio I would be thrilled with that. As long as its called on each reconnect, which can happen either due to auth callout expiry, or just a connection drop. Our internal JWTs expire every few minutes, so this CB could be needed even on a normal drop. 

Thank you so much, this will unblock a large part of our org from adopting this - given how our organization's IAM stack works, with expiring passwords, and given we'd like to set the auth callout JWTs to expire (IDK, Daily maybe), this is needed to bring it all together.

**Comment by tommyjcarpenter** [comment]
Just curious: implementation wise, where would this AuthUserInfoHandler "plug into" that isn't a race in the same way that changing `connopts.password` is?

**Comment by piotrpio** [comment]
There is a race because you are potentially changing `Opts` in `DisconnectedCB` while the reconnect is already triggered. Since `DisconnectedCB` is asynchronous and called in its own goroutine, when the client is reading the options during reconnect you have a read write contention. I'm not sure why it's only detected when using more than one server, but it should not be done either way.

With callback, the option is set once and executed in the same routine as the reconnect process (synchronously), so there is no risk of that. It'll be called somewhere [here](https://github.com/nats-io/nats.go/blob/a06b6a92ee7d6c70e7348bcfdb719691ba1b4b63/nats.go#L2552) and the resulting user/password will be used in `CONNECT` protocol message directly.

**Comment by tommyjcarpenter** [comment]
Awesome. Let me know if I can help with reviews or anything in any way.

**Comment by tommyjcarpenter** [comment]
Great! When will a release be cut for this?

**Comment by piotrpio** [comment]
We have a few more things to add for the next release so I would say early net month is viable.

**Comment by tommyjcarpenter** [comment]
@piotrpio im going to `go get` off this commit in the meantime, is this feature considered done/ready?

**Comment by tommyjcarpenter** [comment]
@piotrpio it worked beautifully 😭 thanks again

**Comment by piotrpio** [comment]
Hey! Yes, we'll be releasing the client this week.
