### ISSUE TITLE
Watch on multiple kv patterns in one call

### ISSUE THREAD

**Issue by telemac** [nats-io/nats.go#1708]
### Proposed change

It is possible to subscribe to multiple subjects on jetstream streams by passing an array or strings. kv.Watch takes only one string. It would be nice to be able to subscribe to multiple keys/patterns in one call.

### Use case

Allow to watch a set of keys without having to create multiple coroutines.

**Comment by telemac** [comment]
Absolutely.
Thx

**Comment by piotrpio** [comment]
Thanks for reporting the issue @telemac. As mentioned my @nickchomey, this feature is incoming and will be a part of the next client release. I'll be closing this issue, please track https://github.com/nats-io/nats-architecture-and-design/issues/277 for updates.
