### ISSUE TITLE
Invalid $SRV.INFO example in README.md

### ISSUE THREAD

**Issue by Aggtaa** [nats-io/nats.go#1710]
### Observed behavior

As of commit 1eafa27812eea44d7cfc0c5aeab970d660b83b75, README.md in `main` branch at https://github.com/nats-io/nats.go/blob/1eafa27812eea44d7cfc0c5aeab970d660b83b75/micro/README.md gives an example of $SRV.INFO response, which lists an apparently invalid field `subjects`:

```
nats req '$SRV.INFO.EchoService.tNoopzL5Sp1M4qJZdhdxqC' ''

19:40:06 Sending request on "$SRV.INFO.EchoService.tNoopzL5Sp1M4qJZdhdxqC"
19:40:06 Received with rtt 282.375µs
{"name":"EchoService","id":"tNoopzL5Sp1M4qJZdhdxqC","version":"1.0.0","metadata":{},"type":"io.nats.micro.v1.info_response","description":"","subjects":["svc.echo"]}
```

### Expected behavior

According to specs at
https://github.com/nats-io/nats-architecture-and-design/blob/main/adr/ADR-32.md#INFO the response example should use `endpoints` field, not `subjects`

### Server and client version

https://github.com/nats-io/nats.go/blob/1eafa27812eea44d7cfc0c5aeab970d660b83b75/micro/README.md

**Comment by piotrpio** [comment]
Hello @Aggtaa, thanks for creating the issue! I created a [PR](#1720) fixing response schema in `micro/README.md`, good catch!
