### ISSUE TITLE
Endless 'no heartbeat received'-loop

### ISSUE THREAD

**Issue by smirnovp** [nats-io/nats.go#1726]
### Observed behavior

Using method Consume() with slow handler i get 'no heartbeat received' error. It is expected. But it never stops after that. And i continue get 'no heartbeat received' error without any chance to get back to pulling messages.

### Expected behavior

after getting 'no heartbeat received' error i want back to consuming messages after slow handler finishes.

### Server and client version

nats --version
v0.1.5

### Steps to reproduce

```
package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/signal"
	"sync/atomic"
	"syscall"
	"time"

	"github.com/nats-io/nats.go"
	"github.com/nats-io/nats.go/jetstream"
)

var count atomic.Int32

func main() {
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGINT, syscall.SIGQUIT, syscall.SIGTERM)

	conn, err := nats.Connect(
		"nats://127.0.0.1:4222",
	)
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()

	js, err := jetstream.New(conn)
	if err != nil {
		log.Fatal(err)
	}

	cons, err := js.CreateOrUpdateConsumer(context.Background(), "test", jetstream.ConsumerConfig{
		Name:              "consumer3",
		DeliverPolicy:     jetstream.DeliverNewPolicy,
		AckPolicy:         jetstream.AckExplicitPolicy,
		FilterSubject:     "test.ack",
		MaxAckPending:     1,
		InactiveThreshold: 5 * time.Second,
	})
	if err != nil {
		log.Fatal(err)
	}

	conctx, err := cons.Consume(handle, jetstream.PullExpiry(1*time.Second), jetstream.ConsumeErrHandler(ConsumeErrHandler))
	if err != nil {
		log.Fatal("failed CreateOrUpdateConsumer: ", err)
	}
	defer conctx.Drain()

	_, err = js.Publish(context.Background(), "test.ack", []byte("msg1"))
	if err != nil {
		log.Fatal(err)
	}
	_, err = js.Publish(context.Background(), "test.ack", []byte("msg2"))
	if err != nil {
		log.Fatal(err)
	}
	_, err = js.Publish(context.Background(), "test.ack", []byte("msg3"))
	if err != nil {
		log.Fatal(err)
	}

	<-sig
}

func handle(msg jetstream.Msg) {

	fmt.Printf("%v\n", string(msg.Data()))

	if count.Load() == 1 {
		time.Sleep(6 * time.Second)
	}
	fmt.Println(".")

	err := msg.Ack()
	if err != nil {
		fmt.Println("failed ACK():", err)
	}
	count.Store(1)
}

func ConsumeErrHandler(consumeCtx jetstream.ConsumeContext, err error) {
	fmt.Printf("consumeError: %s\n", err)
}

```

and output:

```
msg1
.
msg2
.
consumeError: nats: no heartbeat received
consumeError: nats: no heartbeat received
consumeError: nats: no heartbeat received
consumeError: nats: no heartbeat received
consumeError: nats: no heartbeat received
consumeError: nats: no heartbeat received
consumeError: nats: no heartbeat received
consumeError: nats: no heartbeat received
consumeError: nats: no heartbeat received
consumeError: nats: no heartbeat received
consumeError: nats: no heartbeat received
```

upd:
I am using `jetstream.PullExpiry(1*time.Second)` just for speeding up.

**Comment by smirnovp** [comment]
Thank you so much for the detailed explanations. I will review the settings with more understanding now and clarify the questions if they remain

**Comment by Jarema** [comment]
@smirnovp Just do not set InactivityThreshold at all. If it's a consumer with `Durable`, it will never be deleted (automatically)

I'm not sure why you set the `PullExpiry` to 1 second. That puts a lot of pressure on the server without any benefits for you.
You can leave it at default, or explicitly set it to 30 seconds. Messages will be delivered to you anyway as soon as they are availabe, not after the fetch expiry time is completed. 

`Consume` will make sure that there always are pending  pull requests on the server, meaning you will get messages as soon as they are present at the stream (assuming you do not have outstanding acks surpassing `max ack pending`).

**Comment by smirnovp** [comment]
@Jarema , Hi, I set `PullExpiry` to 1 second just for not waiting 30 sec while testing the issue. :)  I'm sorry for confusing you.

Now it became clear why this is happening and what can be done about it. Thanks guys for helping!
