### ISSUE TITLE
How to Properly Wait for Results in MessageBatch from consumer.Fetch()?

### ISSUE THREAD

**Issue by RbPyer** [nats-io/nats.go#1732]
### Observed behavior

I have been struggling for the past three days with the fact that the `fetch()` method of the NATS JetStream consumer in Go is non-blocking. I am calling it in a loop, and since it is non-blocking, my code does not have time to wait for messages to appear in the resulting batch without resorting to a sleep-like solution.

Initially, I wrote my own batching logic, but then I reconsidered and slightly modified my code by adding a blocking function with `ContextWithTimeout`, which waits for messages to appear in the batch during the timeout period. If there are no messages, it exits.

However, I would like to understand the most valid way to achieve this. I found a similar issue, but the code from there did not resolve my problem: [Issue #1590](https://github.com/nats-io/nats.go/issues/1590).

My goal is to read batches from the consumer and then pass these batches for transactions to the database. Here is my current code:

```go
func handleBatches(ctx context.Context, consumer jetstream.Consumer, log *slog.Logger, ytAdapter *ytsaurus.YTAdapter,
	stream, tablePath string, dataStruct reflect.Type) error {

	const op = "nats.ytConsumer.handleBatches"

	for {
		batch, err := consumer.FetchNoWait(batchSize)
		if err != nil {
			return fmt.Errorf("%s: %w", op, err)
		}

		msgs := make(chan jetstream.Msg, batchSize)

		tryToReadBatch(ctx, batch.Messages(), msgs)

		if len(msgs) < 1 {
			continue
		}
		log.Info("new messages are available")

		if err = parseAndWriteToYT(ctx, msgs, ytAdapter, stream, tablePath, dataStruct); err != nil {
			return fmt.Errorf("%s: %w", op, err)
		}
	}
}

func tryToReadBatch(ctx context.Context, batch <-chan jetstream.Msg, msgs chan<- jetstream.Msg) {
	ctx, cancel := context.WithTimeout(ctx, 1*time.Second)
	defer cancel()

	select {
	case <-ctx.Done():
		close(msgs)
		return
	case msg := <-batch:
		if msg != nil {
			msgs <- msg
		}
	}
}
```

I would appreciate any guidance on how to handle this situation more effectively.

### Expected behavior

I would like either to make fetch() blocking or to have some mechanism that notifies me when new messages arrive, avoiding sleep-like solutions.

### Server and client version

nats-server: v2.10.21
(devel)

### Host environment

Linux (EndevaourOS)

**Comment by Jarema** [comment]
Why not just call range over the returnred channel?

**extract from test:**
```go
msgs := make([]jetstream.Msg, 0)
msgs, err := c.FetchNoWait(5)
if err != nil {
	t.Fatalf("Unexpected error: %v", err)
}
msg := <-msgs.Messages()
if msg != nil {
	t.Fatalf("Expected no messages; got: %s", string(msg.Data()))
}
for msg := range res.Messages() {
        // gather the messages if that is what you need
	msgs = append(msgs, msg)
}
if res.Error() != nil {
	t.Fatalf("Unexpected error: %s", err)
}

```

**Comment by RbPyer** [comment]
> Why not just call range over the returnred channel?
> 
> **extract from test:**
> 
> ```go
> msgs := make([]jetstream.Msg, 0)
> msgs, err := c.FetchNoWait(5)
> if err != nil {
> 	t.Fatalf("Unexpected error: %v", err)
> }
> msg := <-msgs.Messages()
> if msg != nil {
> 	t.Fatalf("Expected no messages; got: %s", string(msg.Data()))
> }
> for msg := range res.Messages() {
>         // gather the messages if that is what you need
> 	msgs = append(msgs, msg)
> }
> if res.Error() != nil {
> 	t.Fatalf("Unexpected error: %s", err)
> }
> ```

Thank you for your comment, it really works!
At the moment, I don't quite understand what I was doing wrong before and why your version didn't work for me, although I wrote about the same way, since the code has already changed several times. As far as I understand, in the previous code I passed the consumer object to another function and already did Fetch() there, perhaps there are some subtleties when transferring the consumer to other functions (although I already doubt this).
