### ISSUE TITLE
Error handling documentation lacking

### ISSUE THREAD

**Issue by ohler55** [nats-io/nats.go#1755]
### Observed behavior

Documentation references error codes such as `ErrConsumerDoesNotExist` yet no such error exists. An ErrorCode exists that includes that name as `JSErrConsumerDoesNotExist` but to determine that an error must first be asserted as a `JetStreamError` then `APIError()` function called on that `JetStreamError` before then checking the `ErrorCode` member of the `APIError`. No where in the documentation is this explained. Since the API does not follow the go convention of using `errors.Is()` to check and error type, it would be helpful to explain that somewhere.

### Expected behavior

Explain the APIs approach to errors.

### Server and client version

https://pkg.go.dev/github.com/nats-io/nats.go/jetstream v1.37.0

### Host environment

Web browser on any platform.

### Steps to reproduce

Open the page at https://pkg.go.dev/github.com/nats-io/nats.go/jetstream

**Comment by piotrpio** [comment]
Hello @ohler55, thanks for creating the issue. `ErrConsumerDoesNotExist` exists and is here: https://github.com/nats-io/nats.go/blob/main/jetstream/errors.go#L127

Also, the client does allow using `errors.Is()` to check the errors thanks to the custom `Is()` implementation - you can simply take the error returned from a `jetstream` method and do `errors.Is(err, ErrConsumerDoesNotExist)` - no need for assertions. However, I agree that this behavior is not well documented - I will add it to the docs.

**Comment by ohler55** [comment]
My appologies.
