### ISSUE TITLE
Add a way to directly reply to a message from within a handler

### ISSUE THREAD

**Issue by nussjustin** [nats-io/nats.go#323]
Currently [MsgHandler](https://godoc.org/github.com/nats-io/go-nats#MsgHandler)'s need to manually keep a reference to the [Conn](https://godoc.org/github.com/nats-io/go-nats#Conn) a message was received on (e.g. by closing over it using a closure or through a struct for handler methods) if they want to send a reply, since the [Msg](https://godoc.org/github.com/nats-io/go-nats#Msg) struct exposes nur API to get the connection or send a reply.

Although probably a rare case, this also means that users need multiple handlers if they have multiple [Conn](https://godoc.org/github.com/nats-io/go-nats#Conn)'s.

This is especially inconvenient for packages like [go-kit](https://github.com/go-kit/kit/) which try to avoid keeping reference to the underlying transport in it's handlers. In fact I noticed this when doing a quick review of a [pull request](https://github.com/go-kit/kit/pull/623) that adds a NATS transport to [go-kit](https://github.com/go-kit/kit/).

To solve this I propose to add a method to the [Msg](https://godoc.org/github.com/nats-io/go-nats#Msg) struct that allows replying directly to the topic in the [Reply](https://godoc.org/github.com/nats-io/go-nats#Msg.Reply) field.

The method could look like this:

```go
// PublishReply publishes the given data to the subject set in m.Reply.
// If len(m.Reply) == 0, PublishReply is a no-op.
func (m *Msg) PublishReply(data []byte) error
```

The same problem exists for [EncodedConn](https://godoc.org/github.com/nats-io/go-nats#EncodedConn)'s, but their [Handler](https://godoc.org/github.com/nats-io/go-nats#Handler)'s don't receive the [Msg](https://godoc.org/github.com/nats-io/go-nats#Msg) in most cases.  This could be solved by checking for a return value on the Handler function and using the return value for the reply. The functions would then look as follows:

```go
handler := func(p *person) *response
handler := func(subject string, o *obj) *response
handler := func(subject, reply string, o *obj) *response
```

There are 2 problems with the naive approach though:

1. How to handle multiple return values. 
2. Just publishing the return value(s) as reply can break existing handlers that return values knowing  that the are discarded.

Alternatively 2 new methods SubscribeRequest and QueueSubscribeRequest could be added to [EncodedConn](https://godoc.org/github.com/nats-io/go-nats#EncodedConn), which would handle the return values and existing uses wouldn't be affected. In this case problem 1 could be avoided by failing when a handler return more or less than 1 value.

**Comment by ColinSullivan1** [comment]
@nussjustin , Thank you for raising this issue.  While this is a good idea, one of the tenets of NATS is simplicity, and to that end we are very hesitant to add new APIs.  Since there is a workaround (as you mentioned by closing over it, or via struct), we're closing this for now.  One option could be to expose make the the connection in the subscription; we'll think about this further.

**Comment by derekcollison** [comment]
https://github.com/nats-io/nats.go/commit/8416e7f0b24b6923a0708a4a8981c39c6477937b

Also EncodedConn can take a func that has subject and reply already.

https://github.com/nats-io/nats.go/blob/master/enc_test.go#L192
