### ISSUE TITLE
consider calling nc.Flush() in nc.Close()

### ISSUE THREAD

**Issue by ripienaar** [nats-io/nats.go#333]
It appears that calling `Close()` doesn't flush the pending messages before closing.

It's debatable if this is desired but for me the expectation was that `Close()` would ensure any pending data is sent (within the flush timeout).

Specifically calling `Flush()` resolved it for me reliably.

**Comment by ColinSullivan1** [comment]
@ripienaar, thank you for the suggestion, this makes sense.  I'd think you'd want to check the connection status, then if OK flush with a reasonable timeout (if there's an error condition, the flush may block).  

Would you like to submit a PR?

**Comment by ripienaar** [comment]
Thanks - I am a bit snowed under atm for making a patch, race against the change freeze :)

Appears Flush() already has a 60 second timeout: https://github.com/nats-io/go-nats/blob/f0d9c5988d4c2a17ad466fcdffe010165c46434e/nats.go#L2701

And the FlushTimeout() already checks the connection https://github.com/nats-io/go-nats/blob/f0d9c5988d4c2a17ad466fcdffe010165c46434e/nats.go#L2670

So I suspect this is safe to just be a single call to Flush() during the normal Close() method? 

If you agree I can certainly do that since its like a one liner patch but more than that I'll have to pass on for now

**Comment by tylertreat** [comment]
I took a look at this and it's actually a bit more involved due to the locking involved. You could do the `Flush` before calling `close` inside of `Close`, but each of these internal calls would be locking separately, so if you have concurrent publishes going on, they might not get flushed properly.

**Comment by wallyqs** [comment]
Think this one can be closed now that the client supports drain mode to gracefully disconnect (https://github.com/nats-io/go-nats/pull/378), it does call `Flush` and ensures pending data is processed before closing.

**Comment by derekcollison** [comment]
I can take a look at this. Seems like regular close should try to send any pending data. At least give it one try.

**Comment by derekcollison** [comment]
This functions that way now.
