### ISSUE TITLE
Integer variable number format unmarshal error

### ISSUE THREAD

**Issue by baba2k** [nats-io/nats.go#363]
I use go-nats lib on server and client side to sendening int numbers via JSON over nats. I got sometimes (e.g 1475043 -> 1.474043e+06)  from a JSON in number format e+00. It is a valid number JSON representation but get an unmarshal error.

json: cannot unmarshal number 1.474043e+06 into Go struct field Transaction.amount of type int

What's my fault or is it a bug?

Thanks a lot!

**Comment by aricart** [comment]
From the error it looks like you are serializing a struct - if you are publishing/subscribing to the struct on the same go stack version it should work correctly. Could you create a subscriber that is not encoded that subscribes to the same subject and inspect the JSON you are getting.

Just to be clear:

a) The struct was published using an encoded connection.
b) The struct is received using an encoded connection with a callback matching the signature of the type from the publisher.

**Comment by derekcollison** [comment]
If you would be willing to share your code we are happy to take a look.
