### ISSUE TITLE
how to reply request using chan ?

### ISSUE THREAD

**Issue by PengjuDuan** [nats-io/nats.go#403]
nc, _ := nats.Connect(nats.DefaultURL)
ec, _ := nats.NewEncodedConn(nc, nats.JSON_ENCODER)
defer ec.Close()

type person struct {
     Name     string
     Address  string
     Age      int
}

recvCh := make(chan *person)
ec.BindRecvChan("hello", recvCh)

sendCh := make(chan *person)
ec.BindSendChan("hello", sendCh)

me := &person{Name: "derek", Age: 22, Address: "140 New Montgomery Street"}

// Send via Go channels
sendCh <- me

// Receive via Go channels
who := <- recvCh

when recvCh revice new message, reply string is missing how to reply?

**Comment by derekcollison** [comment]
In this example the replySubject is not available since only the person struct pointer is placed on the channel. In this example you could play a reply inside the person struct, or wrap the person struct with a simple msg struct such as follows.

```go
type msg struct {
  Subject string
  Reply string
  Person *person
}
```

**Comment by PengjuDuan** [comment]
> In this example the replySubject is not available since only the person struct pointer is placed on the channel. In this example you could place the subject and reply inside the person struct, or wrap the person struct with a simple msg struct such as follows and update the chan definition.
> 
> ```go
> type msg struct {
>   Subject string
>   Reply string
>   Person *person
> }
> ```

type person struct {
  Name string
  Address string
  Age int
  Subject string
  Reply string
}

in nodejs, i send one message like JSON.stringify({ name: 'jack' })

in go, i cannot get Subject and Reply by get Name correctly

**Comment by derekcollison** [comment]
You would have to put the ReplySubject in the JSON for the node.js sender. The Go client encoder is only dealing with msg.Data under the covers, not the nats.Msg.

**Comment by jqiris** [comment]
BindRecvChan function,how can i reply the msg

**Comment by derekcollison** [comment]
Your encoder and decoder should take that into account so whatever is delivered on the chan has access to the reply subject.
