### ISSUE TITLE
NextMsgWithContext() returns ErrConnectionClosed, but underlying connection is fine.

### ISSUE THREAD

**Issue by ekle** [nats-io/nats.go#404]
`NextMsgWithContext()` returns a different error, depending when Unsubscribe() is called:

`ErrConnectionClosed` is returned if `NextMsgWithContext()` waits while `Unsubscribe()` is called.
`ErrBadSubscription` is returned if `Unsubscribe()` is called before `NextMsgWithContext()`.

`ErrConnectionClosed` seems wrong here, as it hint to an underlying connection problem, but instead it was just a normal `Unsubscribe()`.

example:
```
sub, _ := natsCon.SubscribeSync("topic")
// func() { // results in ErrBadSubscription
go func() { // results in ErrConnectionClosed
          time.Sleep(time.Second)
          sub.Unsubscribe()
}()
_, err = sub.NextMsgWithContext(ctx)
log.Print(err)
```
version: github.com/nats-io/go-nats v1.6.0

**Comment by ekle** [comment]
This does still happen here sometime with `github.com/nats-io/nats.go v1.8.2-0.20190711203405-98cd22864ded`

**Comment by derekcollison** [comment]
Can you provide some sample code to demonstrate?

This is the test I wrote to confirm behavior.

https://github.com/nats-io/nats.go/blob/master/test/context_test.go#L1044

**Comment by kozlovic** [comment]
@derekcollison test is wrong since you did not recreate the sub. If you do, I see that we get wrong error:
```
diff --git a/test/context_test.go b/test/context_test.go
index 05ddd7f..c1c789f 100644
--- a/test/context_test.go
+++ b/test/context_test.go
@@ -18,6 +18,7 @@ package test
 import (
        "context"
        "strings"
+       "sync"
        "testing"
        "time"
 
@@ -1060,14 +1061,26 @@ func TestUnsubscribeAndNextMsgWithContext(t *testing.T) {
                t.Fatalf("Expected '%v', but got: '%v'", nats.ErrBadSubscription, err)
        }
 
+       ctx, cancelCB = context.WithCancel(context.Background())
+       defer cancelCB() // should always be called, not discarded, to prevent context leak
+
+       sub, err = nc.SubscribeSync("foo")
+       if err != nil {
+               t.Fatalf("Expected to be able to subscribe: %s", err)
+       }
+
        // Now make sure we get same error when unsubscribing from separate routine
        // while in the call.
+       wg := sync.WaitGroup{}
+       wg.Add(1)
        go func() {
                time.Sleep(100 * time.Millisecond)
                sub.Unsubscribe()
+               wg.Done()
        }()
 
        if _, err = sub.NextMsgWithContext(ctx); err != nats.ErrBadSubscription {
                t.Fatalf("Expected '%v', but got: '%v'", nats.ErrBadSubscription, err)
        }
+       wg.Wait()
 }
```

**Comment by ekle** [comment]
this is the test i use:
```go
func TestSubscribeSync(t *testing.T) {
	ctx, cancel := context.WithCancel(ctx)
	defer cancel()
	sub, err := natsCon.SubscribeSync("testSubj")
	go func() {
		time.Sleep(time.Second)
		sub.Unsubscribe()
	}()
	_, err = sub.NextMsgWithContext(ctx)
	if strings.Contains(err.Error(), "connection closed") {
		t.Fatal(err)
	}
}

```

**Comment by kozlovic** [comment]
@derekcollison This is true even for non context sync sub. When we unsubscribe the subscription while the sub is in NextMsg(), it will cause `mch` channel to be closed and NextMsg() simply returns `ErrConnectionClosed` in that case. When you unsubscribe prior to calling NextMsg(), then `validateNextMsgState()` does check things properly.

**Comment by kozlovic** [comment]
@derekcollison @ekle I will submit a PR shortly that addresses these issues.

**Comment by derekcollison** [comment]
Thanks @kozlovic and @ekle
