### ISSUE TITLE
DisconnectedCB doesn't have err in API

### ISSUE THREAD

**Issue by mkorolyov** [nats-io/nats.go#454]
Hi, `DisconnectedCB` callback API doesn't provide access to error caused disconnection. I wonder if you will accept PR fixing it in a backward compatible way, e.g. adding new callback?
```
// DisconnectErrHandler is used to process disconnect events.
type DisconnectErrHandler func(*Conn, error)

// DisconnectErrHandler is an Option to set the disconnected err handler.
func DisconnectErrHandler(cb DisconnectErrHandler) Option {
	return func(o *Options) error {
		o.DisconnectErrCB = cb
		return nil
	}
}
```
WDYT?

**Comment by kozlovic** [comment]
You should be able to get the last error from `Conn.LastError()`. Something like that:
```
func stanDisconnectedHandler(nc *nats.Conn) {
	if nc.LastError() != nil {
		log.Errorf("connection %q has been disconnected: %v", nc.Opts.Name, nc.LastError())
	}
}
```

**Comment by mkorolyov** [comment]
@kozlovic Hi, thanks for such a fast response!
Unfortunately i got `nil` for actual `nats: state connection`, for example.

**Comment by kozlovic** [comment]
Right.. anyway, the invocation of callbacks is asynchronous, so even if we were to move the reset of `nc.err` (which by the way is not set in your specific example), it could be cleared by the time the callback is actually invoked.
Yes, passing the error from upward down to doReconnect() could work.
My concern is adding a new callback. We would still need to invoke the old one (or decide that if the new handler is set, invoke the new, otherwise, invoke the old).
Will let @derekcollison chime in here.

**Comment by kozlovic** [comment]
That being said, not sure what difference it makes to your application to know what caused the disconnect? that is, not sure how your code would behave differently. If the connection is permanently lost, then you may be able to get the last error..

**Comment by mkorolyov** [comment]
@kozlovic adding such changes helped me to diagnose connection issues via logging what actually happen under the hood.

**Comment by derekcollison** [comment]
I believe you could keep track of the errors in your program by capturing them during the error handler callback.

**Comment by kozlovic** [comment]
@derekcollison Actually, not really in that case. For instance, for a stale connection, the library processes the ERR but do not set it in `nc.err`. Even if we did, the fact that we post the callback (remember they are invoked asynchronously), `nc.err` could have been reset in the reconnect logic. So it may not be possible for user to get the original error that caused a disconnect.

**Comment by derekcollison** [comment]
Will the err handler not be invoked with the correct error?

**Comment by kozlovic** [comment]
We don't invoke the err handler in procesOpErr() it seems..

**Comment by derekcollison** [comment]
ok gotcha. So might be worth looking into.

**Comment by mkorolyov** [comment]
@kozlovic so you guys propose to invoke async err callback in the body of `processOpErr`?

**Comment by mkorolyov** [comment]
Adding async err callback invocation leads to inconsistency in disconnection case when you will receive in unordered way some err and disconnect event and you can only guess that received err in some way connected to disconnected event.
i would change API to notify user on disconnect event with disconnect err inside.

**Comment by mkorolyov** [comment]
@kozlovic @derekcollison Hi guys, any comments?
i would add a PR with err enriched API if you ok with it?

**Comment by derekcollison** [comment]
I will sync with @kozlovic today. Apologies for the delay, pushing on NATS 2.0.

**Comment by mkorolyov** [comment]
@derekcollison Hi, any updates?

**Comment by derekcollison** [comment]
Yes we should add a new handler for this condition, @kozlovic and I have discussed.
