### ISSUE TITLE
how to request/reply when using NewEncodedConn (Go client)

### ISSUE THREAD

**Issue by cesar-devera-movile** [nats-io/nats.go#455]
hi,

I tested the request/reply operation with success by following the provided examples.

but I can't find a way to combine request/reply with encoded connections, because either my subscribe handler is like `func(msg *nats.Msg)` (which receives the raw message, including the reply-to field) or is like `func(s *mystruct)` (which does not receive a reply-to field)

maybe there could be a type of handler like this: `func (s *mystruct, raw *nats.Msg)` so the raw/un-encoded message could be available if necessary.

**Comment by derekcollison** [comment]
https://github.com/nats-io/go-nats/blob/master/enc.go#L113
https://github.com/nats-io/go-nats/blob/master/enc_test.go#L149

**Comment by derekcollison** [comment]
Ah I see what you are asking. You can easily roll your own as well.

**Comment by cesar-devera-movile** [comment]
my point is, when we use:
```
msg, err := nc.Request("help", []byte("help me"), 10*time.Millisecond)
```

nats will automatically create a new response inbox and set it into the message (see https://github.com/nats-io/go-nats/blob/master/nats.go#L2600)

and so, the following code is possible:

```
nc.Subscribe("help", func(m *Msg) {
    nc.Publish(m.Reply, []byte("I can help!"))  // <-- here m.Reply is available because m is of type *Msg
})
``` 

but when we use encoded connections, like in:
```
nc, _ := nats.Connect(nats.DefaultURL)
c, _ := nats.NewEncodedConn(nc, nats.JSON_ENCODER)
// (...)

// msg, err := c.Request(subj, &myStruct, time.Second)  // no way here to use the encoder
```

then:
```
nc.Subscribe("help", func(s *MyStruct) {
    nc.Publish(s.Reply, []byte("there is no s.Reply field available")) 
})
```

I know I could manually generate a response subject, subscribe to it, insert it in a Reply field I should add to `MyStruct (*)`, send the message and sync wait into my new subject... but all this seems too inconvenient when compared to the former way.

`(*)` I could better create my version of Msg like this:
```
type MyMsg struct {
  Reply string
  MyStruct MyStruct // or interface, whatever
}
```
and then use MyMsg in the encoded request....

am I missing something? I mean... is there a way to combine encoded connections AND request/reply?

**Comment by derekcollison** [comment]
I understand your point. I would write a wrapper of my own for your responder. Encoded conns don't directly support that at the moment.

**Comment by derekcollison** [comment]
For the subscriber you can create func that has reply in it but encodes the request properly.

Example here: https://github.com/nats-io/nats.go/blob/master/enc_test.go#L192
