### ISSUE TITLE
Mock NATS server implementation in order to be able to write unit tests

### ISSUE THREAD

**Issue by aaslamin** [nats-io/nats.go#467]
In order for consumers to be able to write unit tests for their subscription logic, they need a way to publish messages. Right now, this is not possible because a mock NATS server implementation has not been provided.

This leaves the consumer with only one option: bring up an actual NATS server in your test suite. Which effectively means you are writing an integration test now. I want to avoid this as I want to test my service logic without bringing up external dependencies. Unit tests should be deterministic and not rely on any kind of network connectivity (e.g. bringing up NATS server locally would imply a port needs to be free on CI).

The other option consumers have is to simply just unit test the message handler they pass in to their call to `Subscribe(subj string, cb MsgHandler)`.

What do you propose? Is there any workaround to this? Ideally, this package would provide some kind of mock NATS server somewhat similar to how opentracing go provides a mocktracer - https://github.com/opentracing/opentracing-go/tree/master/mocktracer so folks can write tests to ensure that their spans are being created as expected.

**Comment by derekcollison** [comment]
Mock server is a waste of time IMO. Since this is the Go client you can embed a server in your test on loopback, that is what we do to test the client and is what I would suggest.

**Comment by primalmotion** [comment]
The issue to me with using a full blown server is that is makes it really hard to test for negative scenario

**Comment by derekcollison** [comment]
I would encourage you to give it a shot. This is what we do and its fairly light in our opinion.

In your test.

```go
import (
	"github.com/nats-io/nats.go"

	natsserver "github.com/nats-io/nats-server/test"
)

const TEST_PORT = 8369

func RunServerOnPort(port int) *server.Server {
	opts := natsserver.DefaultTestOptions
	opts.Port = port
	return RunServerWithOptions(&opts)
}

func RunServerWithOptions(opts *server.Options) *server.Server {
	return natsserver.RunServer(opts)
}

func TestSomething(t *testing.T) {
	s := RunServerOnPort(TEST_PORT)
	defer s.Shutdown()

	sUrl = fmt.Sprintf("nats://127.0.0.1:%d", TEST_PORT)
	nc, err := nats.Connect(sUrl)
	...
	defer nc.Close()
}
```

**Comment by primalmotion** [comment]
yeah that is cool indeed, but we can't introduce latency, random tcp error, Robert who unplugged the ethernet cable from the datacenter and everything :)

It `nats.Client` was an interface instead of a solid pointer to struct, we could mock all of that easily.

**Comment by derekcollison** [comment]
on loopback (127.0.0.1) you have almost 0 latency and no dropped packets and no way to affect it via anything physical like unplugging a cable.

**Comment by derekcollison** [comment]
Mocks are not good long term, they give you a false sense of security. I never use them, and been at this for a very long time. Just my $0.02.

**Comment by primalmotion** [comment]
yeah, but we want to introduce latency, random stream interruption, lost message etc

**Comment by derekcollison** [comment]
Understood, then do your own net.Conn and introduce those things there. You can supply a custom Dialer in Go for NATS IIRC.

**Comment by primalmotion** [comment]
Oh that's interesting. I'll take a deeper look at the test package. thanks

**Comment by derekcollison** [comment]
I think we do that somewhere too, so if I or @kozlovic can locate will paste it here.

**Comment by kozlovic** [comment]
Yes, so you could set a custom dialer (here is an example of one returning an error on Dial: https://github.com/nats-io/nats.go/blob/master/test/conn_test.go#L1303) and set it as an option part of your Connect(). Then during Dial you could create our own mock net.Conn that does slow down, etc..

**Comment by derekcollison** [comment]
Thanks @kozlovic

**Comment by aaslamin** [comment]
Great, thank you so much for looking into this @derekcollison @kozlovic 

I was able to plumb some tests together using your recommendations. Will take a looksy at using a custom Dialer to simulate network latency.

**Comment by danesh-d** [comment]
@derekcollison Delivering updated mock of the server would be extremely useful for unit testing. Running a real instance is never as similar as a mocked version. For instance, you can easily simulate congestion, subscription failure, etc. I was really hopping to see such implementation.

**Comment by derekcollison** [comment]
The server is quite complicated and would be a waste of time to try to mock IMO. We do see a need for fault injection etc and the ability to simulate network conditions such as loss, estimated RTT and throughput.

**Comment by ozzywalsh** [comment]
@derekcollison How would I do something similar from a Node environment?

**Comment by ozzywalsh** [comment]
I was thinking of a wrapper node package that might download and start the NATS server or similar?

**Comment by derekcollison** [comment]
To simply run the server? The node's test package for NATS already does this. Or were you thinking of the fault injections?

**Comment by logrusorgru** [comment]
Just need a custom listener for the server similar to the custom dialer.

**Comment by derekcollison** [comment]
To avoid just using a real server on 127.0.0.1 for tests?

**Comment by DumbMachine** [comment]
In case anyone requires a ready to run example with nats-server/v2
```go
import (
	"fmt"
	"log"
	"testing"

	"github.com/nats-io/nats-server/v2/server"
	natsserver "github.com/nats-io/nats-server/v2/test"
	"github.com/nats-io/nats.go"
)

const TEST_PORT = 4222

func RunServerOnPort(port int) *server.Server {
	opts := natsserver.DefaultTestOptions
	opts.Port = port
	return RunServerWithOptions(&opts)
}

func RunServerWithOptions(opts *server.Options) *server.Server {
	return natsserver.RunServer(opts)
}

func TestServerRestart(t *testing.T) {
	s := RunServerOnPort(TEST_PORT)
        s.EnableJetStream(&server.JetStreamConfig{})
	go func() {
		s.Start()
	}()
	time.Sleep(time.Second * 5)

        // use nats as normal
	sUrl := fmt.Sprintf("nats://127.0.0.1:%d", TEST_PORT)
	if nc, err := nats.Connect(sUrl); err != nil {
		panic(err)
	} else {
		js, err := nc.JetStream()
		if err != nil {
			log.Fatal("error creating jetstream context:", err)
		}
		if _, err = js.AddStream(&nats.StreamConfig{
			Name:     "natss",
			Subjects: []string{fmt.Sprintf("%s.*", "natss")},
		}); err != nil {
			log.Fatal("error adding stream:", err)
		}

	}
	defer s.Shutdown()
}
```

**Comment by derekcollison** [comment]
You can also now connect a client directly to a server without going through the network stack. Will be in 2.9 release.

**Comment by yanamg7** [comment]
> In case anyone requires a ready to run example with nats-server/v2
> 
> ```go
> import (
> 	"fmt"
> 	"log"
> 	"testing"
> 
> 	"github.com/nats-io/nats-server/v2/server"
> 	natsserver "github.com/nats-io/nats-server/v2/test"
> 	"github.com/nats-io/nats.go"
> )
> 
> const TEST_PORT = 4222
> 
> func RunServerOnPort(port int) *server.Server {
> 	opts := natsserver.DefaultTestOptions
> 	opts.Port = port
> 	return RunServerWithOptions(&opts)
> }
> 
> func RunServerWithOptions(opts *server.Options) *server.Server {
> 	return natsserver.RunServer(opts)
> }
> 
> func TestServerRestart(t *testing.T) {
> 	s := RunServerOnPort(TEST_PORT)
>         s.EnableJetStream(&server.JetStreamConfig{})
> 	go func() {
> 		s.Start()
> 	}()
> 	time.Sleep(time.Second * 5)
> 
>         // use nats as normal
> 	sUrl := fmt.Sprintf("nats://127.0.0.1:%d", TEST_PORT)
> 	if nc, err := nats.Connect(sUrl); err != nil {
> 		panic(err)
> 	} else {
> 		js, err := nc.JetStream()
> 		if err != nil {
> 			log.Fatal("error creating jetstream context:", err)
> 		}
> 		if _, err = js.AddStream(&nats.StreamConfig{
> 			Name:     "natss",
> 			Subjects: []string{fmt.Sprintf("%s.*", "natss")},
> 		}); err != nil {
> 			log.Fatal("error adding stream:", err)
> 		}
> 
> 	}
> 	defer s.Shutdown()
> }
> ```

I tried this code, but got the rice condition error:

WARNING: DATA RACE
Write at 0x00c00026a558 by goroutine 27:
  github.com/nats-io/nats-server/v2/server.(*Server).startGWReplyMapExpiration()
      /builds/d3347dec/1/mbip/components/f5-eesv-vault/build/vendor/github.com/nats-io/nats-server/v2/server/gateway.go:3149 +0x6a
  github.com/nats-io/nats-server/v2/server.(*Server).Start()
      /builds/d3347dec/1/mbip/components/f5-eesv-vault/build/vendor/github.com/nats-io/nats-server/v2/server/server.go:1733 +0x166d

Please help

**Comment by derekcollison** [comment]
What version?
Do you see the issue running from top of main branch?

**Comment by logrusorgru** [comment]
It's about `go s.Start()`.

I did something like this few years ago
```go
package natsbroker

import (
	"context"
	"testing"
	"time"

	server "github.com/nats-io/nats-server/v2/server"
	"github.com/nats-io/nats.go"

	// "github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Timeout for request/response.
const Timeout = 2 * time.Second

func startServer(t *testing.T) (s *server.Server) {
	t.Helper()

	s = server.New(&server.Options{
		Host:           "127.0.0.1",
		Port:           server.RANDOM_PORT,
		NoLog:          true,
		NoSigs:         true,
		MaxControlLine: 2048,
	})

	go server.Run(s) // nolint:errcheck

	if !s.ReadyForConnections(Timeout) {
		t.Fatal("starting nats server: timeout")
	}
	return
}

func waitConnected(t *testing.T, c *nats.Conn) {
	t.Helper()

	timeout := time.Now().Add(Timeout)
	for time.Now().Before(timeout) {
		if c.IsConnected() {
			return
		}
		time.Sleep(25 * time.Millisecond)
	}
	t.Fatal("client connecting timeout")
}

func Test_requests(t *testing.T) {

	var server = startServer(t)
	defer server.Shutdown()

	var serverAddress = "nats://" + server.Addr().String() // use server address

	// TODO: setup client

	waitConnected(t, clientConn) // wait connection if not connected yet

	// TODO: subscribe, send requests, etc

```
And with
```
go test -cover -race ./
```
I have no data race panic. But it doesn't guarantee anything.

**Comment by yanamg7** [comment]
I figured out the problem: the function natsserver.RunServer(opts) calls go s.Start(), so I removed s.Start(), it works properly.

**Comment by pwntr** [comment]
> You can also now connect a client directly to a server without going through the network stack. Will be in 2.9 release.

@derekcollison I was trying to figure that out - how would one go about that? Is it mentioned in the docs?

**Comment by pwntr** [comment]
Thanks for the instant (!) reply, unfortunately I can't join that slack group to checkout the example you linked. It seems restricted when I try to join:

> You can use any account with the domain:
synadia.com
urbdyn.com
rivitt.io
harperdb.io
winfinity.live
appsteer.io
suse.com
ranchergovernment.com
Don’t have an email address from one of those domains?
Contact the workspace administrator at nats for an invitation.

**Comment by ripienaar** [comment]
```go
package main

import (
	"time"

	natsserver "github.com/nats-io/nats-server/v2/server"
	natsclient "github.com/nats-io/nats.go"
)

func main() {
	server, err := natsserver.NewServer(&natsserver.Options{
		ServerName: "monolith",
		DontListen: true, // Set this if you don't want a listening TCP socket
	})
	if err != nil {
		panic(err)
	}
	server.Start()

	if !server.ReadyForConnections(time.Second * 5) {
		panic("NATS server didn't start")
	}

	client, err := natsclient.Connect("", natsclient.InProcessServer(server))
	if err != nil {
		panic(err)
	}

	_ = client.Publish("foo", []byte("bar"))
}```


Have notified someone about the slack issues thanks

**Comment by pwntr** [comment]
Great, thx a ton!

**Comment by bruth** [comment]
@pwntr Can you try going through https://slack.nats.io to signup and then try that link above again?

**Comment by a-h** [comment]
Thanks, I was able to turn the example into a helper function to make sure that each server is starting from empty instead of restoring existing streams etc.

I also got my test helper to create connections and a jetstream client, so I can use them without adding extra lines to my test code.

```go
package natsjson

import (
	"errors"
	"fmt"
	"os"
	"time"

	natsserver "github.com/nats-io/nats-server/v2/server"
	natsclient "github.com/nats-io/nats.go"
	"github.com/nats-io/nats.go/jetstream"
)

func NewInProcessNATSServer() (conn *natsclient.Conn, js jetstream.JetStream, cleanup func(), err error) {
	tmp, err := os.MkdirTemp("", "nats_test")
	if err != nil {
		err = fmt.Errorf("failed to create temp directory for NATS storage: %w", err)
		return
	}
	server, err := natsserver.NewServer(&natsserver.Options{
		DontListen: true, // Don't make a TCP socket.
		JetStream:  true,
		StoreDir:   tmp,
	})
	if err != nil {
		err = fmt.Errorf("failed to create NATS server: %w", err)
		return
	}
	// Add logs to stdout.
	// server.ConfigureLogger()
	server.Start()
	cleanup = func() {
		server.Shutdown()
		os.RemoveAll(tmp)
	}

	if !server.ReadyForConnections(time.Second * 5) {
		err = errors.New("failed to start server after 5 seconds")
		return
	}

	// Create a connection.
	conn, err = natsclient.Connect("", natsclient.InProcessServer(server))
	if err != nil {
		err = fmt.Errorf("failed to connect to server: %w", err)
		return
	}

	// Create a JetStream client.
	js, err = jetstream.New(conn)
	if err != nil {
		err = fmt.Errorf("failed to create jetstream: %w", err)
		return
	}

	return
}
```

I can then write a test.

```go
func TestBatchProcessor(t *testing.T) {
	// Arrange.
	conn, js, shutdown, err := NewInProcessNATSServer()
	if err != nil {
		t.Fatal(err)
	}
	defer shutdown()
	ctx := context.Background()

	// Create a stream.
	streamName := "test_stream"
	_, err = js.CreateOrUpdateStream(ctx, jetstream.StreamConfig{
		Name:     streamName,
		Subjects: []string{"*"},
		Storage:  jetstream.MemoryStorage, // For speed in tests.
	})
	if err != nil {
		t.Fatalf("failed to create stream: %v", err)
	}
	// Create a durable consumer.
	consumer, err := js.CreateOrUpdateConsumer(ctx, streamName, jetstream.ConsumerConfig{
		Durable:       "testBatchProcessor",
		MemoryStorage: true, // For speed in tests.
	})
	if err != nil {
		t.Fatalf("unexpected failure creating or updating consumer: %v", err)
	}

	t.Run("if no messages are present in the stream, the processor function is not called", func(t *testing.T) {
		p := func(ctx context.Context, msgs []BatchMessage) []error {
			t.Errorf("unexpected call to process function")
			return make([]error, len(msgs))
		}
		bp := NewBatchProcessor[BatchMessage](consumer, 10, p, jetstream.FetchMaxWait(time.Millisecond))
		if err := bp.Process(ctx); err != nil {
			t.Fatalf("unexpected error processing batch: %v", err)
		}
	})
}
```
