### ISSUE TITLE
request/subscribe handles incoming messages synchronously

### ISSUE THREAD

**Issue by tehsphinx** [nats-io/nats.go#468]
Just found out (after hours of searching for the issue) that `Subscribe` seems to handle incoming messages in a synchronous fashion.

**Is that the expected behaviour?** If so, why is there a function called `SubscribeSync`?

Following a test that fails because `Subscribe` is synchronous.

```go
// WARNING! Subscribe calls its handler synchroneously! Except the first request they will all time out.
func TestSubcribe(t *testing.T) {
	con, err := gonats.Connect(address)
	if err != nil {
		t.Fatal(err)
	}
	subj := "subj1"

	if _, err := con.Subscribe(subj, func(msg *nats.Msg) {
		// go func() {
		fmt.Println("got message", string(msg.Data))
		time.Sleep(300 * time.Millisecond)
		if err := con.Publish(msg.Reply, msg.Data); err != nil {
			t.Error(err)
		}
		// }()
	}); err != nil {
		t.Fatal(err)
	}

	chDone := make(chan struct{})
	go func() {
		count := 10
		wg := &sync.WaitGroup{}
		wg.Add(count)
		for i := 0; i < count; i++ {
			go func(i int, wg *sync.WaitGroup) {
				data := []byte(fmt.Sprintf("some data %d", i))
				msg, err := con.Request(subj, data, 500*time.Millisecond)
				if err != nil {
					t.Error(err)
					return
				}
				fmt.Println("got answer", string(msg.Data))
				assert.Equal(t, data, msg.Data)
				wg.Done()
			}(i, wg)
		}
		wg.Wait()
		close(chDone)
	}()

	select {
	case <-chDone:
	case <-time.After(1 * time.Second):
		t.Fatal("timeout")
	}
}
```

If we wrap the handlers functionality into a go function (simulating an async `Subscriber` function) the test will pass.

```go
	if _, err := con.Subscribe(subj, func(msg *nats.Msg) {
		go func() {
			fmt.Println("got message", string(msg.Data))
			time.Sleep(300 * time.Millisecond)
			if err := con.Publish(msg.Reply, msg.Data); err != nil {
				t.Error(err)
			}
		}()
	}); err != nil {
		t.Fatal(err)
	}
```

Keep up the good work! `NATS` is an awesome tool!

**Comment by kozlovic** [comment]
With Subscribe(), the message callback that you provide is invoked by a library go routine.
With the SubscribeSync(), you need to call sub.NextMsg() in order to get the next message. This is synchronous behavior as opposed to Subscribe(). Messages are dispatched serially, that's what lots of people want: be able to process messages in order. It is easy (as you did) to have them process concurrently (say by executing go-routine), it would be "impossible" for an application that wants to process messages in order to do so if the library was executing message callback of a given subscription concurrently.

**Comment by derekcollison** [comment]
Each async subscription handles the message stream for that subscription serially, not synchronously.

If you want messages to be handled in parallel I would suggest a buffered channel and N Go routines, were N is based on the processing behavior of the function.

**Comment by tehsphinx** [comment]
Thank you for the clarification. I just didn't expect that as other handlers are usually called async. (like http.Handler).

**Comment by derekcollison** [comment]
Fair, but easy to assume HTTP requests are mutually exclusive. Semantically we can not assume that with messages on a subscription that may form a stream where order is important. So, we guarantee order and you can process in parallel if you chose to. We even have a channel subscription that makes this easier in Go.

**Comment by tehsphinx** [comment]
Totally makes sense, yes!
