### ISSUE TITLE
After adding a node to the cluster, will the publisher's content be automatically sent to the newly added node?

### ISSUE THREAD

**Issue by ayaya118** [nats-io/nats.go#469]
After adding a node to the cluster, will the publisher's content be automatically sent to the newly added node?

**Comment by ripienaar** [comment]
Yes

**Comment by ayaya118** [comment]
Can published content be balanced on new nodes ?

**Comment by ripienaar** [comment]
No one connection is to a specific server only. If you reconnect it will know about new servers but to spread your producers on initial connect I believe you need to know the server list and have the randomise option set

**Comment by ayaya118** [comment]
So publishers need to reconnect to the server cluster?

**Comment by ayaya118** [comment]
The cluster cannot automatically assign content to latest nodes ?

**Comment by ayaya118** [comment]
hi , Do nats support master-slave synchronization ?

**Comment by ayaya118** [comment]
Oh, I see. Thanks very much！
