### ISSUE TITLE
Does it have a copy of the message

### ISSUE THREAD

**Issue by ayaya118** [nats-io/nats.go#470]
hi , Do nats support master-slave synchronization ?Does it have a copy of the message?
If one machine in the cluster goes down, then all messages in that machine are gone?

**Comment by ripienaar** [comment]
And if no-one is there to receive a delivery its deleted.  No data is stored.  Only NATS Streaming support that

**Comment by ayaya118** [comment]
OK,THANKS VERY MUCH!
