### ISSUE TITLE
Build failures observed with MinIO

### ISSUE THREAD

**Issue by harshavardhana** [nats-io/nats.go#477]
```
go: github.com/nats-io/go-nats@v1.8.0: parsing go.mod: unexpected module path "github.com/nats-io/nats.go"
go: error loading module requirements
```

Did this repo change in anyway?

**Comment by kozlovic** [comment]
Yes, repository was renamed from `go-nats` to `nats.go`.
Try `github.com/nats-io/nats.go/@v1.8.0` (notice the `/` after `nats.go`).

**Comment by wallyqs** [comment]
hi @harshavardhana thanks for the report, one change is that the client repo has changed from 
`github.com/nats-io/go-nats` to `github.com/nats-io/nats.go`, could you share the link to the project where this happened?

**Comment by harshavardhana** [comment]
We have a fix we were making a new release and observed the build failures we had to rename go-nats to nats.go and go-streaming-server to stan.go 

The project is https://github.com/minio/minio

**Comment by kozlovic** [comment]
Check my comment and try please. It should work.

**Comment by kozlovic** [comment]
To recap, we have changed the repo name, so replace nats or go-nats with nats.go. In some cases, nats.go is problematic (because of directory ending with `.go`) and it helps to have the `/` at the end.

**Comment by wallyqs** [comment]
thanks @harshavardhana looking at the go.mod file from minio/minio I notice the following entries which feels like there might still be some issues: 
https://github.com/minio/minio/blob/master/go.mod#L65-L70

```
    github.com/nats-io/gnatsd v1.4.1 // this one should be github.com/nats-io/nats-server 
    github.com/nats-io/go-nats-streaming v0.4.2 // github.com/nats-io/stan.go
    github.com/nats-io/nats v1.7.2 // should be instead replaced by nats.go
    github.com/nats-io/nats.go v1.8.0 // should replace nats-io/nats entry above
```

So I think that the resulting dependencies listed in the go.mod should look something like this:

```
    github.com/nats-io/nats-server v1.4.1
    github.com/nats-io/stan.go v0.4.2
    github.com/nats-io/nats.go v1.8.0
```

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/commit/ff7799452bf95b0706194896278aef7cc8034076 fixes this, we will do the next fixes later.

**Comment by harshavardhana** [comment]
> thanks @harshavardhana looking at the go.mod file from minio/minio I notice the following entries which feels like there might still be some issues:

@wallyqs it's not that simple in `go mod` world, unfortunately. We seem to have other deps which depend on gnatsd which is still being referenced cyclically which is bring in other deps also. 

We will have live with that until they fix their repos.

**Comment by mzukowski-reef** [comment]
@harshavardhana it seems that is caused by bad imports in nats.go and stan.go tests - namely `nats-server/*` and `nats-streaming-server/*` instead of `nats-server/v2/*` and  `nats-streaming-server/v2/*` - without `v2` old versions are downloaded with imports using old repo names and then you end up with 
```
go: github.com/nats-io/go-nats@v1.8.0: parsing go.mod: unexpected module path "github.com/nats-io/nats.go"
```

**Comment by kozlovic** [comment]
@mzukowski-reef I think you may be right. I can work on that, but I am not 100% sure, so to test it means that I need to create a new tag to test the theory, which if prove wrong means I will have to delete the tag. What do you think?

**Comment by kozlovic** [comment]
I have made several updates to various nats-io repos and it seems that things are getting slowly resolved. Sorry for the trouble.
