### ISSUE TITLE
disconnected client publish does not occur error 

### ISSUE THREAD

**Issue by coolyrat** [nats-io/nats.go#484]
I have the following steps, and expected the client occur an error during publish:
1. I have a client connected to the Nats server;
2. Manually shut down the Nats server;
3. Let the client publish to the Nats server;
4. expected an error occurs and try to log it.

Or should I just set the ReconnectBufSize, and let the client wait for the server to start up and flush to the Nats server?

**Comment by wallyqs** [comment]
depends on your use case but that’s right the default is to let the client accumulate pending data during the reconnect and then let it flush, also if the reconnect buffer is very small or disabled you would get an error right away

**Comment by derekcollison** [comment]
The client by default will try for a period of time to reconnect.

https://nats-io.github.io/docs/developer/reconnect/intro.html

If you disable that behavior you will get an error right away. Or if you want you can register a handler for events to tell you what is happening.

https://nats-io.github.io/docs/developer/events/events.html
