### ISSUE TITLE
Is request-reply concurrent?

### ISSUE THREAD

**Issue by alifpay** [nats-io/nats.go#485]
Hi 
I have question about request-reply in nats.go
is it concurrent? does it process the requests in parallel?

`
// Requests
msg, err := nc.Request("help", []byte("help me"), 10*time.Millisecond)

// Replies
nc.Subscribe("help", func(m *Msg) {
    nc.Publish(m.Reply, []byte("I can help!"))
})`

**Comment by wallyqs** [comment]
`Request` blocks until receiving a response, and the callback registered via `Subscribe` processes the messages sequentially in the order that they were delivered, though you can have multiple subscriptions processing messages concurrently.  If want to process messages more messages concurrently, you can also spin a goroutine in the async callback for example:

```
nc.Subscribe("help", func(m *Msg) {
  go func() {
    // ... do work ...
    nc.Publish(m.Reply, []byte("I can help!")) 
  }()
})`
```

**Comment by alifpay** [comment]
thank you
