### ISSUE TITLE
Low number of messages consumed

### ISSUE THREAD

**Issue by marcoroganovic** [nats-io/nats.go#496]
Hi there,

I have one question regarding client performance.

Right now I'm sending 45kb messages to NATS server, but I have really low consumption rate, for instance I've sent around 5856 messages to server, and consumed just about 500.

To clarify what I'm doing in a consumer, I receive bunch of endpoints and I issue outgoing request for each endpoint.

So, does anyone have some advice how I should try to solve this problem?

I've tried with bigger number of clients, and of course there is some improvement, but not as much as I need, so I want to try to maximise work of one client atm.

**Comment by derekcollison** [comment]
If you could post some code that would be the most helpful.

Alternatively please better describe your setup, how many servers, how many producers and consumers. What you are trying to achieve. Happy to help. Also be good to have you jump on the [NATS Slack Channel](https://join.slack.com/t/natsio/shared_invite/enQtMzE2NDkxNDI2NTE1LTc5ZDEzYTkwYWZkYWQ5YjY1MzBjMWZmYzA5OGQxMzlkMGQzMjYxNGM3MWYxMjNiYmNjNzIwMTVjMWE2ZDgxZGM) which usually has a healthy amount of people hanging out willing to help.

**Comment by derekcollison** [comment]
Closing for now without further information, but feel free to re-open.
