### ISSUE TITLE
go mod tidy [micro]

### ISSUE THREAD

**Issue by liuwangchen** [nats-io/nats.go#501]
![image](https://user-images.githubusercontent.com/25526033/62267188-e648ce00-b45d-11e9-82cf-b849b9675e34.png)
![image](https://user-images.githubusercontent.com/25526033/62267252-227c2e80-b45e-11e9-82a5-4ee98494f286.png)

**Comment by wallyqs** [comment]
See: https://github.com/nats-io/nats.go/issues/493

**Comment by liuwangchen** [comment]
3q~~

**Comment by wallyqs** [comment]
np :)
