### ISSUE TITLE
nats.UserCredentials doesn't support tilde character

### ISSUE THREAD

**Issue by variadico** [nats-io/nats.go#509]
I was reading the tutorial at https://synadia.com/ngs/signup. One of the steps in that tutorial is to call `UserCredentials` like this.

```
nats.UserCredentials("~/.nkeys/synadia/accounts/ngs/users/ngs.creds")
```

However, `UserCredentials` doesn't expand `~/` to the users home directory. So running that code gives you this error.

```
nats: open ~/.nkeys/synadia/accounts/ngs/users/ngs.creds: no such file or directory
```

We could add support to expand `~/` here https://github.com/nats-io/nats.go/blob/master/nats.go#L4018-L4025.

Or we could just update the code example on the signup page. Kinda leaning towards just updating the example.

**Comment by derekcollison** [comment]
I like adding in expand support myself.

**Comment by sasbury** [comment]
We use a go lib in ncs and ngs to help with that, Alberto will recall the
name it eludes me while on my phone

**Comment by aricart** [comment]
https://github.com/mitchellh/go-homedir is the library you are looking for.
Also, that is not sufficient, usually the path has to be converted to an
absolute path after ~ expansions, and to eliminate other '.' or '..'.

**Comment by variadico** [comment]
What do you guys think of updating the example?

```
nats.UserCredentials(homedir.Expand("~/.nkeys/synadia/accounts/ngs/users/ngs.creds"))

or even just

nats.UserCredentials("ngs.creds")
```

Reasoning:
* nats.go doesn't have to depend on go-homedir, 1 less dependency, less download, less code
* not sure if tilde paths are common for this project, maybe it's not worth it to users?
* library users can decide if they want to use go-homedir or not

**Comment by sasbury** [comment]
ok as an example to me

**Comment by derekcollison** [comment]
We can't just make the path correct with the tilde? Seems like should be quite doable, no?

**Comment by variadico** [comment]
Well, looks like we already have a number of deps nats pulls in. So we could just add homedir. homedir seems to handle a bunch of edge cases. So seems like it would be easiest and least surprising to users.
