### ISSUE TITLE
Client calling `Close()` should not execute callbacks

### ISSUE THREAD

**Issue by aricart** [nats-io/nats.go#513]
On go the close/disconnect handlers are called when the client performs a close(). This is non-sensical as the application called `Close()` so it knows that it called it itself.

On other conditions, the notification is completely valid - as the application is not expecting the connection to have gone away. 

The main issue is:
```
// Close will close the connection to the server. This call will release
// all blocking calls, such as Flush() and NextMsg()
func (nc *Conn) Close() {
    if nc != nil {
        nc.close(CLOSED, true, nil)
    }
}
```
This should have the `doCBs` argument set to `false`, and internal uses by `doReconnect()`, `drainConnectino()`, `processErr()`, `processOpErr()` should be calling the internal `close()` with the correct arguments for the situation.

**Comment by derekcollison** [comment]
I think behavior is correct. In arbitrarily complex app you may not "know" that you called close TBH. Would leave as is.

**Comment by derekcollison** [comment]
You could wrap close with func() that turns off callbacks by setting them to nil.
