### ISSUE TITLE
  Can we  see the number of published messages for a topic?

### ISSUE THREAD

**Issue by ayaya118** [nats-io/nats.go#519]
hello,
Can we see the number of published messages for a topic?

**Comment by kozlovic** [comment]
You mean from a given connection? A connection has a `Statistics` object that can be returned that will give you the number of out messages (https://github.com/nats-io/nats.go/blob/master/nats.go#L3883 which returns https://github.com/nats-io/nats.go/blob/master/nats.go#L476). However, there is no information "per topic", it is an aggregate. If you really need per "topic" and assuming that you have a small set, then you may use a different connection per subject. Again, assuming that the number of subjects is reasonable.

**Comment by ayaya118** [comment]
thanks
