### ISSUE TITLE
go get fail

### ISSUE THREAD

**Issue by uudashr** [nats-io/nats.go#522]
Trying to `go get` but fail
```
$ go get github.com/nats-io/nats.go
stat github.com/nats-io/nats.go: no such file or directory
```
Try to use the `latest` but no luck
```
$ go get github.com/nats-io/nats.go/@latest
go get github.com/nats-io/nats.go/@latest: malformed module path "github.com/nats-io/nats.go/": trailing slash
```

For version 1.8.1, also failed
```
$ go get github.com/nats-io/nats.go/@v1.8.1
go: finding github.com v1.8.1
go: finding github.com/nats-io v1.8.1
go get github.com/nats-io/nats.go/@v1.8.1: malformed module path "github.com/nats-io/nats.go/": trailing slash
```

My go version: `go version go1.13 darwin/amd64`

Any idea why?

**Comment by derekcollison** [comment]
https://github.com/golang/go/issues/32483

Need to wait for 1.13.1

Fix is on master for golang already.

**Comment by sweetgiorni** [comment]
Updated to 1.13.1 and I still see this issue:

```
bash-4.2# go version
go version go1.13.1 linux/amd64

bash-4.2# go get github.com/nats-io/nats.go
stat github.com/nats-io/nats.go: no such file or directory
```

**Comment by derekcollison** [comment]
Yes, 1.13.1 was only a security release. 1.13.2, hopefully this week, will fix all of the projects that use a .go extension for the repo name.

**Comment by sweetgiorni** [comment]
Bah, I was excited to try out NATS :)
Guess I'll wait

**Comment by derekcollison** [comment]
We recommend waiting for 1.13.2 for all Go stuff TBH.

**Comment by kozlovic** [comment]
But I guess you could clone right? You don't have to do `go get` to have a try :-)

**Comment by sweetgiorni** [comment]
That is an astute observation.
`Bytes/Sec: 416.8M`
Oooweee that's fast!
