### ISSUE TITLE
Remote NATs server dropping slow consumer

### ISSUE THREAD

**Issue by Kannaj** [nats-io/nats.go#524]
Hello,

I tried asking this over on stack  overflow but dint have much luck. I have a NATs instance running on a remote server with a go script which listens for UDP packets on a particular port and publishes to NATS.

On my local machine, i establish an ssh tunnel to this remote server and have a go script running which subscribes to this NATS instance and gets the UDP packets. The problem i'm currently facing is that after a couple of messages sent - i get the below error on the NATS instance

```
Oct 10 06:26:27 ip-10-0-100-71 gnatsd[32499]: [32499] 2019/10/10 06:26:27.381048 [INF] 127.0.0.1:54664 - cid:13 - Slow Consumer Detected: WriteDeadline of 2s Exceeded
Oct 10 06:29:48 ip-10-0-100-71 gnatsd[32499]: [32499] 2019/10/10 06:29:48.847658 [INF] 127.0.0.1:54666 - cid:14 - Slow Consumer Detected: WriteDeadline of 2s Exceeded
```

It looks like my subscriber script is reading packets slow - so i tried spawning multiple goroutines to circumvent this issue but still see the same problem. Heres a code snippet of my script

```
func LocalConnectToRemoteNats() {
    natsConn, err := connectNatsWithRetry()

    if err != nil {
        fmt.Printf("Connection to NATS failed : %+v \n", err)
    }

    defer natsConn.Close()
    fmt.Println("Established connection to nats")

    s, err := net.ResolveUDPAddr("udp4", "localhost:8975")
    if err != nil {
        fmt.Println(err)
        return
    }
    c, err := net.DialUDP("udp4", nil, s)

    if err != nil {
        fmt.Println(err)
        return
    }

    fmt.Printf("The UDP server is %s\n", c.RemoteAddr().String())
    defer c.Close()
    for i := 1; i < 11; i++ {
        wg.Add(i)
        go spawnSubscribers(&wg, natsConn, c)
    }
    wg.Wait()
}

func spawnSubscribers(wg *sync.WaitGroup, natsConn *nats.Conn, c *net.UDPConn) {
    for {
        natsConn.QueueSubscribe("udp-packets", "test", func(m *nats.Msg) {
            _, err := c.Write(m.Data)
            if err != nil {
                fmt.Printf("Error writing UDP packet: %+v", err)
                wg.Done()
                return
            }
        })
    }
    wg.Done()
}
```

This issue still seems to persist though and i'm running out of ideas - is there anything im missing? Any guidance would be appreciated

Thanks

**Comment by kozlovic** [comment]
The slow consumer from a server perspective means that the *connection* is not reading data out of the socket fast enough (https://nats-io.github.io/docs/developer/events/slow.html). So adding more queue subs is not going to help.

What NATS Server version are you using, and what Go client library version? You may want to upgrade to see if you get better performance.

You may also want to check the network link between your client application and the server. This link may be too slow or having issues that causes the server to hit the write deadline (default 2s). If there is nothing you can do there, you could increase the write deadline in the server configuration (https://nats-io.github.io/docs/nats_admin/slow_consumers.html#server-configuration).

**Comment by derekcollison** [comment]
The slow consumer is per connection, so running more go routines won't help per se. 

The first thing that jumps out at me is how long does the c.Write(m.Data) take? I would measure that call.

And all of what Ivan said.

**Comment by Kannaj** [comment]
Thanks for the response guys - will have a look 

I'm currently on gnatsd-v1.3.0 and go version is 1.11

@derekcollison  - regarding `c.Write(m.Data)` - while i'm not sure how long it takes - i considered that could be the bottleneck and spawned that off to its own goroutine - but that didnt solve the issue

I'll look into increasing the write deadline and see if that solves the issue.

Thanks again

**Comment by derekcollison** [comment]
To find out how "far" you are from the server. In the client after the connection is established just measure the time for a nc.Flush() as well.

```go
start := time.Now()
nc.Flush()
rtt := time.Since(start)
log.Printf("[%s] = %v\n", nc.ConnectedUrl(), rtt)
```

**Comment by Kannaj** [comment]
Guys it looks like i made an error 

instead of
```
for {
        natsConn.QueueSubscribe("udp-packets", "test", func(m *nats.Msg) {
            _, err := c.Write(m.Data)
            if err != nil {
                fmt.Printf("Error writing UDP packet: %+v", err)
                wg.Done()
                return
            }
        })
    }
```

i only subscribe once and started an empty for loop below - seems to work fine for now.

Thanks for your help

**Comment by wallyqs** [comment]
@Kannaj an empty for loop may still give you issues, you may want to try with an empty `select {}` instead (for example purposes):

```go
        natsConn.QueueSubscribe("udp-packets", "test", func(m *nats.Msg) {
            _, err := c.Write(m.Data)
            if err != nil {
                fmt.Printf("Error writing UDP packet: %+v", err)
                wg.Done()
                return
            }
        })
        select {}
```

**Comment by kozlovic** [comment]
Yes, the infinite for loop will starve cause CPU starvation. But I see what was wrong now - sorry for missing this - you were creating queue subs in a loop...
