### ISSUE TITLE
webassembly nats client over websocket

### ISSUE THREAD

**Issue by derfbn** [nats-io/nats.go#530]
Hi all,
I have written a http server which forwards a raw tcp nats connection to websocket.
The client is written in go, compiled to webassembly, running inside the browser.
I created a nats.CustomDialer and try to connect.
The result is something like this: 'nats: expected PONG, got ?PONG' [error origin](https://github.com/nats-io/nats.go/blob/8782052c0c269348d8148d79060b4834749ec6ab/nats.go#L1707)

So there is an unwanted symbol inside the PONG message. I added a few lines of code in [func (nc *Conn) readProto()](https://github.com/nats-io/nats.go/blob/8782052c0c269348d8148d79060b4834749ec6ab/nats.go#L1717)

```go
func (nc *Conn) readProto() (string, error) {
	var (
		_buf     = [10]byte{}
		buf      = _buf[:0]
		b        = [1]byte{}
		protoEnd = byte('\n')
	)

	for {
		if n, err := nc.conn.Read(b[:1]); err != nil {
			// Do not report EOF error
			if err == io.EOF {
				return string(buf), nil
			}
			return "", err
		} else if n == 0 { //if read count is zero, dont add it to the buf
			continue
		}
		buf = append(buf, b[0])
		if b[0] == protoEnd {
			return string(buf), nil
		}
	}
}
```
Now i can use the nats client inside the browser and it works like a charm. I am not sure but I think this should be added to the nats client? If read length is zero, do not add it to the buffer.

**Comment by kozlovic** [comment]
Thanks, will have a look asap.

**Comment by derfbn** [comment]
nice, thanks. I think there is a reason why conn.Read returns 'n', should not be be ignored.  :blush:

**Comment by kozlovic** [comment]
Yes, but returning 0 with err==nil is strange..

**Comment by derfbn** [comment]
yeah, I guess its related to the websocket connection. As I said, I was not sure if its worth to change nats-client code. I ll upload my code soon to github.

**Comment by derfbn** [comment]
`Implementations of Read are discouraged from returning a zero byte count with a nil error, except when len(p) == 0. Callers should treat a return of 0 and nil as indicating that nothing happened; in particular it does not indicate EOF. `[link](https://tip.golang.org/pkg/io/#Reader)

it is strange...
[discussion](https://github.com/golang/go/issues/27531)

**Comment by derekcollison** [comment]
We are close to having our own websocket support right in the server. Will close for now but feel free to re-open.

**Comment by oderwat** [comment]
This is related to #1146 because "wasm websocket" is not "js websocket".

I add my wrapper code here for people which end up here:

```go
func (cw *ConnectionWrapper) Dial(network, address string) (net.Conn, error) {
	dbg.Logf("Got Request for Network: %q / Address: %q", network, address)
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()

	// The address we get has to be a string without a protocol. We will
	// always connect throught wss though!
	dbg.Logf("Dialing Address: wss://%s", address)
	c, _, err := websocket.Dial(ctx, "wss://"+address, nil)
	if err != nil {
		return nil, fmt.Errorf("websocket.Dial failed %w", err)
	}
	CW.WS = c
	CW.NetConn = websocket.NetConn(context.Background(), c, websocket.MessageBinary)
	return CW.NetConn, nil
}

func Connect() error {
   var err error
   // Here we do not specify wss because if we do specify one with "wss://" it
   // wants to handle the TLS by itself, but our CustomDialer does that already.
   // That way it seems to work flawlessly.
   NC, err = nats.Connect("local.metatexx.de:5222,local.metatexx.de:5223,local.metatexx.de:5224",
      UserCredentialsFromContent(CW.CredsFileContent),
      nats.SetCustomDialer(&CW),
      nats.SetSkipTLSWrapper(true))
   if err != nil {
      return fmt.Errorf("Native Go Connect did fail: %w", err)
   } else {
      return nil
   }
}
```

This is the "magic" code in my Wasm frontend. The CustomDialer and the Connect(). This is from proprietary code. But I guess I could make an example for a simplified go-app client that uses NATS. People always wonder how to connect to the backend and I think NATS would be a wonderful solution because a go-app "app" is always a backend and the frontend in Go and embedding the server in the backend code is trivial

NOTICE: There may be another implementation for the part which disables the TLSWrapper in the future.
