### ISSUE TITLE
error declares nats.go

### ISSUE THREAD

**Issue by xxxmailk** [nats-io/nats.go#534]
it's my error message when I used go get to get nats client

$ go get -u  github.com/nats-io/nats
go get: github.com/nats-io/nats@v1.9.1: parsing go.mod:
        module declares its path as: github.com/nats-io/nats.go
                but was required as: github.com/nats-io/nats

**Comment by derekcollison** [comment]
Try the following. You can just use it as nats in your go program, e.g. `nats.Connect`

$ go get -u github.com/nats-io/nats.go
