### ISSUE TITLE
nats.NkeyOptionFromSeed() using os.Getenv() instead of ioutil.ReadFile()

### ISSUE THREAD

**Issue by bh90210** [nats-io/nats.go#535]
Hello all

I am finding myself hacking `nats.NkeyOptionFromSeed()` to `nats.NkeyOptionFromSeedEnv()` because I'd like to avoid creating a file and rather load the seed from an environment variable.

Is there a particular reason a real file and `ioutil.ReadFile()` are used?

Would an even more generic solution make more sense? for example a `[]byte`

Thanks,
Byron

```go
func NkeyOptionFromSeedEnv(seedEnv string) (Option, error) {
	kp, err := nkeyPairFromSeedEnv(seedEnv)
	if err != nil {
		return nil, err
	}
	// Wipe our key on exit.
	defer kp.Wipe()

	pub, err := kp.PublicKey()
	if err != nil {
		return nil, err
	}
	if !nkeys.IsValidPublicUserKey(pub) {
		return nil, fmt.Errorf("nats: Not a valid nkey user seed")
	}
	sigCB := func(nonce []byte) ([]byte, error) {
		return sigHandlerEnv(nonce, seedEnv)
	}
	return Nkey(string(pub), sigCB), nil
}

func nkeyPairFromSeedEnv(seedEnv string) (nkeys.KeyPair, error) {
	contents := []byte(os.Getenv("seedEnv"))
	defer wipeSlice(contents)
	return jwt.ParseDecoratedNKey(contents)
}

func sigHandlerEnv(nonce []byte, seedEnv string) ([]byte, error) {
	kp, err := nkeyPairFromSeedEnv(seedEnv)
	if err != nil {
		return nil, err
	}
	// Wipe our key on exit.
	defer kp.Wipe()

	sig, _ := kp.Sign(nonce)
	return sig, nil
}
```

**Comment by derekcollison** [comment]
We have others comment on this as well. Most are presented as secrets via volumes and read as files, and allow for updates to the app/container during runtime. For instance during expiration and renewal. This pattern is not possible with environment variables which only have the startup value when a process is started.

**Comment by bh90210** [comment]
thanks a lot! I will try doing things this way too :+1:

**Comment by nkhalasi** [comment]
@derekcollison Isn't it an anti-pattern to bake secrets into your images? We follow a practice in our containerized deployments that the apps are responsible for fetching their secrets at startup time from a vault service and use them appropriately. Keeping seeds, private keys in volumes is definitely not recommended especially when these are in plain text. Further if we bake them into images, then everytime one rotates these values, new images have to be published. Next the images themselves become more vulnerable and targets for attacks.

We were thinking of contributing a pull-request along the same lines as https://github.com/nats-io/nats.go/commit/893829b0a20518b08693c8f348aa4b87b977a98d for the respective functions that handle Nkeys/Seed and Client Cert/Privatekey for TLS.
However this response was contradicting and hence opening up the query again.

**Comment by derekcollison** [comment]
The Go client lib gives you quite a bit of flexibility. It was designed such that you do not even need to every access the private key or seed. It could be on a hardware device like a YubiKey etc.

We are always open to making updates that make life easier.

**Comment by nkhalasi** [comment]
IIUC we are open to the idea of having e.g. a function like `NkeysFromSeedValue(value string)`  so that as a consumer of NATS client library it will be my responsibility to ensure that my raw values are protected (either encrypted in my server or coming from valut service). But I pass on decrypted values to such functions to achieve the desired behavior.

In that case we are happy to create a fork, add those functions + test cases + documentation updates and submit a PR.
