### ISSUE TITLE
where will Async callback msg handler be called?

### ISSUE THREAD

**Issue by MohanGyara** [nats-io/nats.go#540]
My application publish the message to a subscriber subject called subject-1 and also registers a async subscription called subject-2 with a call back handler, Now when thread-1  publish message to subject-1, and after when there is a message for the subject-2, where does this call back msg handler will be called, is it like nat library maintain a different thread or?

**Comment by kozlovic** [comment]
When you create an asynchronous subscription, the library has its own go routine to dispatch messages to the provided callback. Messages are dispatched sequentially, that is, even if 10 messages are available to be dispatched, the callback will be invoked with the first message, then when the callback returns, the next is presented, etc...

**Comment by MohanGyara** [comment]
I have one thread with in my application that is publishing the message, is it the same thread that this call back calls? What I did was I have put a sleep for 100 ms after publish message and then msg handler call back gets called in the same thread. Is this the way?

**Comment by kozlovic** [comment]
You are in the Go client repo here, so I assume you are using Golang. If not, let me know. But again, regardless, as I mentioned, the library is invoking the user callback from a library's internal go routine.
I am not sure I understand what you are asking or trying to do. If you would like to send some code example to illustrate better?

**Comment by MohanGyara** [comment]
am using nats io c library. 
I have only main thread, then I call publish message on a subject, then sleep 100 ms, then my call back will be called from the same thread. is it like after publish message this call back will be called when there is a message on my subject?

**Comment by kozlovic** [comment]
You should have opened on the NATS C client repo (https://github.com/nats-io/nats.c), but that's ok :-)
Again, the library has its own thread to dispatch the messages for asynchronous subscriptions. Please have a look at the FAQ: https://github.com/nats-io/nats.c#faq. Some points that may be of interest:
- What is the threading model of the library?
- Is the data sent in place or from a different thread?
- Are messages from an asynchronous subscription dispatched in parallel?
