### ISSUE TITLE
Feature request: Default subject prefix

### ISSUE THREAD

**Issue by sammy007** [nats-io/nats.go#544]
An option to specify default subject prefix would be convenient for isolation of development and staging environments for instance.

**Comment by derekcollison** [comment]
We recommend using accounts for this. You can have the same subjects but the account will define if its  development or staging or prod. Happy to discuss more if you would like but definitely look into accounts.

https://docs.nats.io/whats_new_20#accounts
https://docs.nats.io/nats-server/configuration/securing_nats/auth_intro/accounts

**Comment by wallyqs** [comment]
Closing since accounts would be the right way to support this, can reopen as an issue on at https://github.com/nats-io/nats-architecture-and-design
