### ISSUE TITLE
Go Channels - Guaranteed send?

### ISSUE THREAD

**Issue by moon-bits** [nats-io/nats.go#552]
First of all, I'm astonished by the API design of the nats.go library. It really feels like a native Go standard library!

The documentation states that NATS' design is based on a "Fire and forget" concept. So I was wondering what the best way would be to send 10K msg/sec (via the BindSendChan API) and also make sure that those messages are also received at the nats-server (and of course the consumer-applications).

To make it clear: If I send messages via:

`
sendChan := make(chan *Message, 1000)
`
...
`sendChan <- myMessage`

**Is that guaranteed to be arrived on the nats-server/comsumer-applications?**

Another question: What would be a wise choice for the size of the buffered channel? Should it be buffered at all? I made some experiments, but the results were not really satisfying in regards to _msg/sec_ rate.

Thanks in advance!

**Comment by ripienaar** [comment]
It is not guaranteed, if you need a guaranteed delivery to a remote you need to use a acknowledged method - either have your subscribers acknowledge receipt or use a intermediate store like NATS Streaming Server or our upcoming [NATS JetStream](https://github.com/nats-io/jetstream) service - JetStream for example can acknowledge receiving your message and consumers are tracked again via acknowledgements.

**Comment by moon-bits** [comment]
Thanks,  for the quick response!

From what I read so far, JetStream will be the successor of the NATS Streaming Server?

**Comment by ripienaar** [comment]
That's correct yes

**Comment by moon-bits** [comment]
Great, thank you very much! 

Any idea regarding my question on the number of channels (buffered/unbuffered)?

**Comment by wallyqs** [comment]
@moon-bits definitely not unbuffered as that will make the subscription become a slow consumer with a very small burst of messages. I think the size of the channel you choose would depend on how much memory you are ok to use and the rate of traffic you are expecting to receive.  By the way the default for async nats subscriptions is that they can receive around 64K before you get a slow consumer error, internally those are not using Go channels but it is a default that you can use to have similar behavior as asyns subs just using more memory.

**Comment by moon-bits** [comment]
Super, thanks for your detailed response!

Thanks guys!
