### ISSUE TITLE
Add jitter during reconnect

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.go#563]
## Defect

Some jitter needs to be added during reconnect.  One option would be waiting for a duration that is a percentage of Reconnect wait - it'd be easy for users to configure.

**Comment by derekcollison** [comment]
We need jitter in all of our clients. I could have swore I had it in here to avoid thundering heard problems already.

**Comment by ripienaar** [comment]
Have wanted this many times :)

**Comment by derekcollison** [comment]
Maybe I am having a senior moment but could have swore I had it in there.

**Comment by ColinSullivan1** [comment]
I remember something in there too at one point.
