### ISSUE TITLE
Support WebSocket communication

### ISSUE THREAD

**Issue by agrimmer** [nats-io/nats.go#577]
## Feature Request
The [nats-server](https://github.com/nats-io/nats-server/) supports [WebSocket connections](https://github.com/nats-io/nats-server/issues/315). 
This issue proposes to extend the go-client for nats to also allow connecting via a WebSocket.

#### Use Case:
In our use case, we would like to expose NATS via a standard Kubernetes ingress (a k8s Ingress only allows HTTP(s) traffic!). Then, we would like to connect an external service written in Go to the NATS server using this Kubernetes ingress (i.e. make an HTTP(s) request and upgrade to a WebSocket connection).

**Comment by joe-getcouragenow** [comment]
I would like to be able to cross compile the NATS clients to WASM using the standard or Tinygo compiler.
The NATS golang client code just needs a compiler flags.

This golang websocket code one can cross compile to WASM: https://godoc.org/nhooyr.io/websocket

**Comment by tomghuang** [comment]
It's important to add WebSocket support in the client libraries other then the JavaScript client library. The NATS server port is usually blocked by enterprise firewalls, so we need to use WebSocket to access a NATS server outside the browser environment.

**Comment by noam09** [comment]
Are there any plans to implement this in the near future? Thanks!

**Comment by kozlovic** [comment]
Done with PR #719. Available now in main branch and will be soon in the upcoming v1.11.0 release.

**Comment by kozlovic** [comment]
Closing now since we have released [v1.11.0](https://github.com/nats-io/nats.go/releases/tag/v1.11.0) with Websocket support.
