### ISSUE TITLE
Question: Any plans when to release the next minor with the new RetryOnFailedConnect option?

### ISSUE THREAD

**Issue by hbobenicio** [nats-io/nats.go#583]
This pull request added a new interesting option (RetryOnFailedConnect):
https://github.com/nats-io/nats.go/pull/581

Any plans on the next minor release? It would be awesome to use it =)

**Comment by derekcollison** [comment]
We were probably waiting til next server release. You can build with go.mod to any position on the main branch of course. Will that suffice or does it need to be a released version?

**Comment by hbobenicio** [comment]
I can wait until next release without any issues. I was just wondering if it would take some time or if it would be available soon, so I could be aware checking it periodically or not. It's nothing blocking/critical though, it would just clean some boilerplates of my code.

thanks for the quick feedback.

**Comment by bethrezen** [comment]
> We were probably waiting til next server release. You can build with go.mod to any position on the main branch of course. Will that suffice or does it need to be a released version?

Hi! 
There were several releases of nats-server if that what you mean. While there were no releases in nats.go client.
Can you please tag a release with something stable? I think this will prevent users confusion while they are looking to readme with this feature and not seeing it in any of versions

**Comment by mogazy** [comment]
Hi, 
as @bethrezen said, you included `RetryOnFailedConnect` in the README but the most recent release `1.10.1` doesn't support it, if you could please tag a new release.

**Comment by wallyqs** [comment]
Closing since included in v1.11.0 release
