### ISSUE TITLE
Can't install with go get 

### ISSUE THREAD

**Issue by Vowan** [nats-io/nats.go#595]
I am trying to install client but get the following 
go get github.com/nats-io/nats.go/
# github.com/nats-io/nats.go
../github.com/nats-io/nats.go/nats.go:4454:9: undefined: nkeys.ParseDecoratedJWT
../github.com/nats-io/nats.go/nats.go:4503:9: undefined: nkeys.ParseDecoratedNKey

**Comment by kozlovic** [comment]
You need to update the dependencies. Have you tried:
```
go get -u github.com/nats-io/nats.go/
```
Also, make sure you are using a recent version of Golang. Older ones had issues with the name of our repo (since it ends in `.go`).

**Comment by Vowan** [comment]
Thanks. With go1.15.2 and -u flag that worked
