### ISSUE TITLE
OutMsgs is smaller than InMsgs

### ISSUE THREAD

**Issue by gowxw** [nats-io/nats.go#600]
I am using request/reply mode with nats.go : 
publisher send msg to a subject， and the subscriber respond to the publisher.

I print the stats of publish connection by using  nats.Conn.Stats()  

the result is like this:

      _"result": {
                "InMsgs": 2689,
                "OutMsgs": 2685,
                "InBytes": 490317,
                "OutBytes": 692866,
                "Reconnects": 0
                }_

which OutMsgs is small than InMsgs

is the result reasonable if there is only exact one subscriber listen on a subject?

**Comment by derekcollison** [comment]
Is this for the requestor? Yes its possible, you could run the server with `-DV` flag and watch the interactions exactly with the application.

Or if you want to share a simple code snippet we could look. In general we trust the account of `Stats()`.

**Comment by kozlovic** [comment]
Also note that if the application is actively working, it is possible that numbers are "off" because the InMsgs is atomically incremented without the connection lock, while in Stats(), the connection lock is acquired and the InMsgs count is atomically retrieved and OutMsgs is updated only under the connection lock. What I am trying to say is that InMsgs could be incrementing since it is done without connection lock while OutMsgs is "frozen" while Stats() executes.

**Comment by gowxw** [comment]
yes , the requestor Stas() show  OutMsgs is smaller than InMsgs .  Also i trust Stats(), and i noticed Stats() has the same result as  http://_$nast-server-addr:_8222/connz?cid=_$publisher_cid_    

my product scenario is：the publisher connects nats-server intranet ， and the subscribers connect nats-server  at remote across everywhere

it's  one request and one reply,    i think the OutMsgs is bigger than ( in case of remote subscribers disconnect  ) or equal to the InMsgs.

on test enviroment  , i never reproduce the result
but, on product enviroment, this result happened， and why this happened？ 

the code snippet is almost the same as nats.go/examples/nats-req/   ,  as below

the requestor:
`_publisher.Request("sub", msg, time.Second*3)_`

and the responder:
```
_func processMsg(m *nats.Msg) {
    m.Respond("response msg")
}_
```

**Comment by gowxw** [comment]
> Also note that if the application is actively working, it is possible that numbers are "off" because the InMsgs is atomically incremented without the connection lock, while in Stats(), the connection lock is acquired and the InMsgs count is atomically retrieved and OutMsgs is updated only under the connection lock. What I am trying to say is that InMsgs could be incrementing since it is done without connection lock while OutMsgs is "frozen" while Stats() executes.


thank you for your answer @kozlovic 

but i still think differently :
InMsgs could be incremented without  connection lock  when doing Stats(),  but it is incremented only on receiving respond msg which is triggered by a request msg sent first  with OutMsgs is incremented before

**Comment by kozlovic** [comment]
> InMsgs could be incremented without connection lock when doing Stats(), but it is incremented only on receiving respond msg which is triggered by a request msg sent first with OutMsgs is incremented before

Technically, no, since it is well possible that the reply is received and InMsgs incremented while still in the Publish call where the OutMsg is incremented last. But unless you have multiple request/reply happening in parallel in your application, that should not show more than +1 difference at a time "t".

If this number difference stays the same, even after a while without activity, then my only explanation is that you have more responders than you think, or for some requests, it could be that 2 replies or more are sent. You could run a subscriber on ">" (or _INBOX.>) close to your producer and try to find if that is the case.

**Comment by gowxw** [comment]
> > InMsgs could be incremented without connection lock when doing Stats(), but it is incremented only on receiving respond msg which is triggered by a request msg sent first with OutMsgs is incremented before
> 
> Technically, no, since it is well possible that the reply is received and InMsgs incremented while still in the Publish call where the OutMsg is incremented last. But unless you have multiple request/reply happening in parallel in your application, that should not show more than +1 difference at a time "t".
> 
> If this number difference stays the same, even after a while without activity, then my only explanation is that you have more responders than you think, or for some requests, it could be that 2 replies or more are sent. You could run a subscriber on ">" (or _INBOX.>) close to your producer and try to find if that is the case.

**Comment by gowxw** [comment]
> Technically, no, since it is well possible that the reply is received and InMsgs incremented while still in the Publish call where the OutMsg is incremented last. But unless you have multiple request/reply happening in parallel in your application, that should not show more than +1 difference at a time "t".


thank you really.

after reading the code nats.go , i understand this : when receiving a respond ,  the InMsgs incremented , but the publish() is still there unfinished, that makes  InMsgs > OutMsg

the difference stays the same for a couple of hours  , i  believe there is  a bug in my system: more than one subscriber listen on a same subject 


last dispute i want to discuss：
if no bug in my system，
InMsgs > OutMsg  could not be showed by calling Stats(),  because Stats() only  be executed by acquiring  the nats.Conn.mu  ,  which is Unlock by publish() returned with OutMsg incremented .    may be  i got something wrong .      plz point  me the code  snippet i missed with nats.go .

**Comment by gowxw** [comment]
> > InMsgs > OutMsg could not be showed by calling Stats(), because Stats() only be executed by acquiring the nats.Conn.mu , which is Unlock by publish() returned with OutMsg incremented . may be i got something wrong . plz point me the code snippet i missed with nats.go .
> 
> You are right. Although OutMsg is incremented after the actual publish and even if the reply is received and InMsg atomically incremented (without the need for the lock), Stats() does need the connection lock, so you would not see a difference between In and Out msgs. Again, my guess is that either your app has a subscription that receives data from time to time, or there may be multiple instances of the responder (in some cases) causing a "double" reply that is ignored because Request() returns the first reply, but may be counted because it was processed in processMsg().

**Comment by gowxw** [comment]
> > > InMsgs > OutMsg could not be showed by calling Stats(), because Stats() only be executed by acquiring the nats.Conn.mu , which is Unlock by publish() returned with OutMsg incremented . may be i got something wrong . plz point me the code snippet i missed with nats.go .
> > 
> > 
> > You are right. Although OutMsg is incremented after the actual publish and even if the reply is received and InMsg atomically incremented (without the need for the lock), Stats() does need the connection lock, so you would not see a difference between In and Out msgs. Again, my guess is that either your app has a subscription that receives data from time to time, or there may be multiple instances of the responder (in some cases) causing a "double" reply that is ignored because Request() returns the first reply, but may be counted because it was processed in processMsg().


thank you for your explanation.
