### ISSUE TITLE
processNextMsgDelivered lock itself twice, does it matter?

### ISSUE THREAD

**Issue by jsgusi** [nats-io/nats.go#602]
new goer here.

in function processNextMsgDelivered, before calling "nc.removeSub(s)", it call "nc.mu.Lock". thenin removeSub, "	s.mu.Lock()". lock itself twice, does it matter?

		if delivered == max {
			nc.mu.Lock()
			nc.removeSub(s)
			nc.mu.Unlock()
		}

**Comment by kozlovic** [comment]
The `s.mu.Lock()` is for the subscription object, not the connection object. So those are different locks.
