### ISSUE TITLE
Nats EOF error

### ISSUE THREAD

**Issue by mixmind** [nats-io/nats.go#628]
## Defect

Hi, we are using nats in our go tool.
After couple of hours that tool is running, nats starting to fail and after tool restart in start to work for another couple of hours.
Code that I have provided runs every minute or two to connect and after that send data. But it fails on connection. Can you help?
 - [ 1.10 ] Included nats.go version
 - [ 2.1.7 ] included nats server version

#### OS/Container environment:
CentOS 7.7.1908 , kernel:3.10.0-1062.4.1.el7.x86_64
#### Steps or code to reproduce the issue:

> 1   nc, err := nats.Connect(Nats.NatsEndpoint,Nats.CredsFile,Nats.RootCA, config.DefaultNatsConnectTimeout)
> 2   if err != nil {
> 3		log.Error(err)
> 4		return nil, err	
> 5   }

#### Expected result:
Without error
#### Actual result:
[error] connect.go:2 - EOF

**Comment by derekcollison** [comment]
So you are creating new connections all the time versus just creating one on startup and using that one throughout the lifetime of the app?

Do you close the old connections? Could it be the app runs out of file descriptors? What does `ulimit -a` report as the limit for FDs?

**Comment by mixmind** [comment]
I am creating new connection every minute, and closing it after that. I already received open files error in ubuntu 20(too many open files), thought in centos 7 it must be the same error.. Refactored code and testing it write now..

**Comment by derekcollison** [comment]
You can simply keep the connection open, no need to keep opening and closing.

**Comment by derekcollison** [comment]
I will close for now, but if you have any further issues please let us know.
