### ISSUE TITLE
Nak and Term in pull mode don't send the proper response

### ISSUE THREAD

**Issue by acroca** [nats-io/nats.go#641]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included nats.go version
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats.go` and the `nats-server` if one was involved:
`master` branch for both, as of today:
- [nats.go](https://github.com/nats-io/nats.go/tree/58bf69ad2df848bc145d0b0f73d48be72b301c55)
- [nats-server](https://github.com/nats-io/nats-server/tree/ea2d5bc0f03a4692d60fc892c7f9bec50a747cad)

#### OS/Container environment:
Linux with docker

#### Steps or code to reproduce the issue:

This example uses the stream and consumer from the examples
```go
package main

import (
	"fmt"
	"math/rand"
	"time"

	"github.com/nats-io/nats.go"
)

func main() {
	nc, err := nats.Connect("nats://localhost:4222")
	noerr(err)
	defer nc.Close()

	js, err := nc.JetStream()
	noerr(err)

	_, err = js.Publish("ORDERS.received", []byte("Hello world"))
	noerr(err)

	subs, err := js.SubscribeSync("ORDERS.received", nats.PullDirect("ORDERS", "NEW", 30))
	noerr(err)

	for {
		msg, err := subs.NextMsg(5 * time.Second)
		if err == nats.ErrTimeout {
			continue
		}
		noerr(err)
		msg.Nak() // or msg.Term()
	}
}

func noerr(err error) {
	if err != nil {
		panic(err)
	}
}
```

#### Expected result:

Using `.Nak()` should send `-NAK`, and using `.Term()` should send `+TERM`

#### Actual result:

 both `msg.Nak()` and `msg.Term` are sending `+NEXT {"batch": 1}` to the acknowledgement subject, instead of the expected `-NAK` or `+TERM`.

Reference code: https://github.com/nats-io/nats.go/blob/58bf69ad2df848bc145d0b0f73d48be72b301c55/js.go#L838-L840

Note that the server also don't handle this well: https://github.com/nats-io/nats-server/issues/1844

**Comment by wallyqs** [comment]
This should work now that the API was changed to PullSubscribe and calling Fetch to get a set of messages.  For example:

```go
js, _ := nc.JetStream()
sub, _ := js.PullSubscribe("ORDERS.received", nats.Durable("NEW"), nats.AckWait(200*time.Millisecond))

msgs, _ := sub.Fetch(1)
msg := msgs[0]

// Next message will be redelivered
msg.Nak()

// Should be the same sequence
msgs, _ = sub.Fetch(1)
msg = msgs[0]

// Ack so that it is not redelivered for the consumer.
msg.Ack()
```
