### ISSUE TITLE
Add StartWithLast (somehow) in jetstreamcontext.AddConsumer

### ISSUE THREAD

**Issue by tpihl** [nats-io/nats.go#700]
## Feature Request
I cannot find how to create a consumer starting with Last message using jetstreamcontext.AddConsumer, but would really like to be able to :)

**Comment by wallyqs** [comment]
Hi @tpihl, this is great feedback. So currently there is `nats.DeliverLast()` which you can use as `js.SubscribeSync("foo", nats.DeliverLast())`, and with `js.AddConsumer` it would mean to do:

```go
ci, err := js.AddConsumer("foo", &nats.ConsumerConfig{Durable: "dlc", DeliverPolicy: nats.DeliverLastPolicy})
```

We could alias to `nats.DeliverLast()` to `nats.StartWithLast()` maybe 🤔

**Comment by tpihl** [comment]
No, it's fine

More fluent would perhaps be 
DeliveryPolicy: nats.DeliverLastPolicy() 
and 
DeliveryPolicy: nats.DeliverByStartSequencePolicy(startseq)

but i guess it works as it is with some good documentation
