### ISSUE TITLE
Examples for Jetstream

### ISSUE THREAD

**Issue by alifpay** [nats-io/nats.go#708]
I can not find jetstream examples..

**Comment by wallyqs** [comment]
Hi, you can find examples in the Go Docs: 
- https://godocs.io/github.com/nats-io/nats.go#example-JetStream
- https://github.com/nats-io/nats.go/blob/master/example_test.go#L282

**Comment by alifpay** [comment]
this line have error can not find func

https://github.com/nats-io/nats.go/blob/1a653a70336d723429c59725521f1612b4a0c825/example_test.go#L315

**Comment by variadico** [comment]
Are you using the latest commit of the library?
https://pkg.go.dev/github.com/nats-io/nats.go@master#Msg.Metadata

**Comment by alifpay** [comment]
Yes, last one

github.com/nats-io/nats.go v1.10.1-0.20210330225420-a0b1f60162f8

**Comment by variadico** [comment]
Aah, a0b1f60162f8 is a little old.

To use the latest version, try running this command.

```
go get github.com/nats-io/nats.go@master
```

This is the version I got

```
github.com/nats-io/nats.go v1.10.1-0.20210412203207-1a653a70336d
```
