### ISSUE TITLE
Suggestion: release current client 

### ISSUE THREAD

**Issue by tpihl** [nats-io/nats.go#715]
It would help a lot to have the current client released in a .0 version and have this tweaks cuntiously added. Even with a disclaimer that api may change. 

We’re currently trying to handle things with refs to master and similar but things get a lot simpler when the normal mod versioning kicks in

**Comment by kozlovic** [comment]
Done, we have now released [v1.11.0](https://github.com/nats-io/nats.go/releases/tag/v1.11.0). Closing this issue now.
