### ISSUE TITLE
[need help] Can someone help to figure out how to use jetstream to subscribe a wildcard topic.

### ISSUE THREAD

**Issue by zhwei820** [nats-io/nats.go#725]
hi, I want to use jetstream to subscribe a wildcard topic, like "foo.*" => "foo.bar".
here is my minimal code.

```
package main

import (
	"fmt"
	"math/rand"
	"strconv"
	"time"

	"github.com/nats-io/nats.go"
)

func randString() string {
	source := rand.NewSource(time.Now().Unix())
	r := rand.New(source)
	return strconv.Itoa(r.Intn(10000))
}

func main() {

	nc, _ := nats.Connect(nats.DefaultURL)

	js, _ := nc.JetStream()

	js.AddStream(&nats.StreamConfig{
		Name:     randString(),
		Subjects: []string{"ORDERS.scratch"},
	})

	js.Subscribe("ORDERS.scratch", func(m *nats.Msg) {
		fmt.Printf("ORDERS.scratch: %s\n", string(m.Data))
	}, nats.DeliverLast())

	// ======>  Subscribe to a wildcard not work.
	js.Subscribe("ORDERS.*", func(m *nats.Msg) {
		fmt.Printf("ORDERS.*: %s\n", string(m.Data))
	}, nats.DeliverLast())

	js.Publish("ORDERS.scratch", []byte("hello"))

	fmt.Println("wait......")
	select {}
}

```

```
result output:  (wildcard subscription not work...)

go run . 
ORDERS.scratch: hello
ORDERS.scratch: hello
wait......
```

os: ubuntu 18.04
sdk:   github.com/nats-io/nats.go v1.10.1-0.20210419223411-20527524c393
nats-server: nats:alpine3.13  (docker, Version:  2.2.2)

many thanks~

**Comment by wallyqs** [comment]
`js.Subscribe("ORDERS.*"` has to match to exactly to the subject from a stream, so in order to make it work you could do instead:

```
	js.AddStream(&nats.StreamConfig{
		Name:     randString(),
		Subjects: []string{"ORDERS.*"},
	})
```

**Comment by derekcollison** [comment]
You can have consumers take only a subset of the total subject space and messages from a stream, but not a superset. The consumer needs to be bound to the stream.

You could create the stream with the wildcard of `ORDERS.*` and then have the consumer do `ORDERS.scratch`.

Streams can be composed of messages from multiple subjects, all can include wildcards or other streams.

**Comment by zhwei820** [comment]
> `js.Subscribe("ORDERS.*"` has to match to exactly to the subject from a stream, so in order to make it work you could do instead:
> 
> ```
> 	js.AddStream(&nats.StreamConfig{
> 		Name:     randString(),
> 		Subjects: []string{"ORDERS.*"},
> 	})
> ```

thanks. it works~

**Comment by zhwei820** [comment]
> You can have consumers take only a subset of the total subject space and messages from a stream, but not a superset. The consumer needs to be bound to the stream.
> 
> You could create the stream with the wildcard of `ORDERS.*` and then have the consumer do `ORDERS.scratch`.
> 
> Streams can be composed of messages from multiple subjects, all can include wildcards or other streams.

 Thanks, I may take a deeper look into Jetstream later.  Hope this link can help more new comers~
