### ISSUE TITLE
invalid jetstream publish response

### ISSUE THREAD

**Issue by materia2021** [nats-io/nats.go#732]
Simple jetstream publish

```
ack, err := js.Publish("foo",[]byte("HELLO"))
log.Println(ack)
if err != nil {
    log.Println(err)
}
```
returns
```
2021/05/24 16:14:54 <nil>
2021/05/24 16:14:54 nats: invalid jetstream publish response
```

github.com/nats-io/nats-server/v2 v2.2.1-0.20210330155036-61cbd74e213d // indirect
github.com/nats-io/nats.go v1.11.0
using synadia/jsm:latest nats-server version 2.2.0-beta.15

works properly when using nats java client

**Comment by ripienaar** [comment]
How do you create the stream?

**Comment by materia2021** [comment]
> How do you create the stream?

using the cli - nats str add FOO 
my consumer / subscriber works.

**Comment by materia2021** [comment]
tried using the latest official release of nats-server and it worked.
