### ISSUE TITLE
js: Make NextMsg alias of Fetch(1) for PullSubscribe

### ISSUE THREAD

**Issue by wallyqs** [nats-io/nats.go#747]
## Feature Request

Currently `NextMsg` is disabled for pull subscribers since there is a `Fetch` API which can be used instead.

#### Proposed Change:

 Instead of disabling maybe NextMsg could be aliased to `Fetch(1)`.

#### Alternative Approaches

Using `sub.Fetch(1)`

**Comment by Jarema** [comment]
I can take it.
