### ISSUE TITLE
 js.AddConsumer call blocked

### ISSUE THREAD

**Issue by carr123** [nats-io/nats.go#762]
1. create a stream

	_, err = js.AddStream(&nats.StreamConfig{
		Name:      "ORDERS",
		Subjects:  []string{"ORDERS.*"},
		Storage:   nats.FileStorage,
		Replicas:  1, // if this is 3, everything is all right
		Retention: nats.WorkQueuePolicy,
		Discard:   nats.DiscardNew,
		MaxMsgs:   -1,
		MaxAge:    time.Hour * 24 * 365,
	})
	if err != nil && !strings.Contains(err.Error(), "already in use") {
		log.Println("AddStream fail:", err)
		return
	}

2. add consumer
        call next function more than one time.

       durableName := "consume_created"
	if _, err := js.AddConsumer("ORDERS", &nats.ConsumerConfig{
		Durable:       durableName,
		DeliverPolicy: nats.DeliverAllPolicy,
		AckPolicy:     nats.AckExplicitPolicy,
		ReplayPolicy:  nats.ReplayInstantPolicy,
		FilterSubject: "ORDERS.created",
		AckWait:       time.Second * 10, 
	}); err != nil {
		fmt.Println("AddConsumer fail:", err)
		return
	}

if Replicas=1,  then AddConsumer API call blocked, after a while, print : "AddConsumer fail: context deadline exceeded"
i expect it non-block, and report error : "consumer name already in use" like  Replicas=3 does.

**Comment by carr123** [comment]
bug disapper in version 2.3.0

**Comment by wallyqs** [comment]
oh nice thanks for the report 👍🏾
