### ISSUE TITLE
message consume too slow

### ISSUE THREAD

**Issue by carr123** [nats-io/nats.go#763]
i created a stream in `Retention=WorkQueuePolicy`, and published 1 million messages.
then i start to consume it.

```go
for {
  msgs, err := sub.Fetch(10000, nats.Context(ctx))
 for _, msg := range msgs {
	msg.AckSync()
 }
}
```
the first batch fetched fast enough, after a few loops, Fetch( )  becomes too slow (> 10 seconds), and the whole batch ack time become too slow also.

**Comment by carr123** [comment]
don't you think it is a bug ?   publishing  1 million messages takes some seconds, while consuming them takes hours.

**Comment by derekcollison** [comment]
There are lots of ways to increase the throughput.

In your case above for each 1000 messages you are doing 1000+1 request + wait for reply. The AckSync waits for the reply. If you make that just an Ack() that will improve things.

Then you can run as many of those sub.Fetch calls as you want, either as other Go routines or separate applications/processes.

If you want to go even fast I would suggest moving to a flow controlled push based consumer which can run at line speed.

**Comment by carr123** [comment]
> There are lots of ways to increase the throughput.
> 
> In your case above for each 1000 messages you are doing 1000+1 request + wait for reply. The AckSync waits for the reply. If you make that just an Ack() that will improve things.
> 
> Then you can run as many of those sub.Fetch calls as you want, either as other Go routines or separate applications/processes.
> 
> If you want to go even fast I would suggest moving to a flow controlled push based consumer which can run at line speed.

a. it seems push based consumer does not work in WorkQueuePolicy,
b. i created 100 goroutines to fetch messages concurrently, each fetch call has a batch size 100,  use msg.Ack(),   
   the result is 38800 messages are fetched in 120 seconds, which seems still not fast enough.
c. if i created 500 goroutines to fetch, use msg.Ack(),  error reported: "nats: Exceeded MaxAckPending"

**Comment by derekcollison** [comment]
Possible to make a small repo that shows the 38k fetched in 2minutes? They should be able to be fetched much faster unless you are fetching one at a time. Each fetch is a round trip. You also had AckSync which is also a full round trip.

**Comment by carr123** [comment]
sub, err := js.PullSubscribe(subjectName, durableName, nats.Bind(streamName, durableName))
	if err != nil {
		fmt.Println("PullSubscribe:", err)
		return
	}

	for k := 0; k < 100; k++ {
		go func() {
			for {
				t1 := time.Now()
				msgs, err := sub.Fetch(100, nats.Context(context.Background()))
				t2 := time.Now()

				nTotal := atomic.AddInt32(&nCount, int32(len(msgs)))
				log.Println("fetch timecost:", t2.Sub(t1), " msgs:", len(msgs), " total:", nTotal)
				if err != nil {
					log.Println(" Fetch fail:", err, " msgs:", len(msgs))
					continue
				}

				for _, msg := range msgs {
					//msg.AckSync()
					msg.Ack()
				}
			}
		}()
	}

 //my code above, consuming messages not fast enough, is there any bug ?

**Comment by wallyqs** [comment]
This will block forever because there is no cancellation:

```go
			msgs, err := sub.Fetch(100, nats.Context(context.Background()))
```

instead you can do:

```go
			msgs, err := sub.Fetch(100, nats.MaxWait(3*time.Second))
```

**Comment by carr123** [comment]
> This will block forever because there is no cancellation:
> 
> ```go
> 			msgs, err := sub.Fetch(100, nats.Context(context.Background()))
> ```
> 
> instead you can do:
> 
> ```go
> 			msgs, err := sub.Fetch(100, nats.MaxWait(3*time.Second))
> ```

that doesn't help.   "nats: timeout" and "nats: Exceeded MaxAckPending"  reported.

**Comment by derekcollison** [comment]
I will take a look later today.

**Comment by derekcollison** [comment]
So here is a program I wrote that might help. I did a multiple Go routine version but performance is about the same since we do no real work. But hopefully this can be a starting point.

When I run this I get the following results.

```
2021/06/29 08:04:39 Took 2.570184331s to send 500000 messages, ~194539 msgs/sec
2021/06/29 08:04:39 Single batched fetch
2021/06/29 08:04:43 Took 3.22199787s to fetch all 500000 messages, ~155183 msgs/sec
2021/06/29 08:04:43 Multiple go routines of batched fetch
2021/06/29 08:04:48 Took 3.189032594s to fetch all 500000 messages, ~156787 msgs/sec
```

Program

```go
package main

import (
	"log"
	"sync"
	"time"

	"github.com/nats-io/nats.go"
)

func main() {
	conn, err := nats.Connect("127.0.0.1")
	if err != nil {
		log.Fatalf("Could not connect to local server\n")
	}

	js, err := conn.JetStream(
		nats.MaxWait(10*time.Second),
		nats.PublishAsyncMaxPending(16*1024),
	)
	if err != nil {
		log.Fatalf("Could not create jetstream context: %v\n", err)
	}

	// Delete any old one.
	if err := js.DeleteStream("FETCH"); err != nil {
		log.Fatalf("Error deleting stream: %v\n", err)
	}
	// Add new one.
	_, err = js.AddStream(&nats.StreamConfig{
		Name:      "FETCH",
		Subjects:  []string{"foo"},
		Retention: nats.WorkQueuePolicy,
	})
	if err != nil {
		log.Fatalf("Unexpected error: %v\n", err)
	}

	// Put in 500_000 messsages.
	n, start, msg := 500_000, time.Now(), []byte("FASTER PLS")
	for i := 0; i < n; i++ {
		if _, err := js.PublishAsync("foo", msg); err != nil {
			log.Fatalf("Unexpected publish error: %v\n", err)
		}
	}
	select {
	case <-js.PublishAsyncComplete():
	case <-time.After(5 * time.Second):
		log.Fatalf("Did not receive async publish completion signal\n")
	}
	tt := time.Since(start)
	log.Printf("Took %v to send %d messages, ~%.0f msgs/sec\n", tt, n, float64(n)/tt.Seconds())

	// Make sure they are all there.
	si, err := js.StreamInfo("FETCH")
	if err != nil {
		log.Fatalf("Unexpected error getting stream info: %v\n", err)
	}
	if si.State.Msgs != uint64(n) {
		log.Fatalf("Expected to have %d messages, got %d\n", n, si.State.Msgs)
	}

	// Now do the pull subscriber part.

	////////////////////////////////////////////////////////
	// Do single fetch first.
	////////////////////////////////////////////////////////
	log.Println("Single batched fetch")
	sub, err := js.PullSubscribe("foo", "d22", nats.AckWait(2*time.Minute), nats.MaxAckPending(n))
	if err != nil {
		log.Fatalf("Unexpected error creating pull subscriber: %v\n", err)
	}
	ci, err := sub.ConsumerInfo()
	if err != nil {
		log.Fatalf("Unexpected error getting consumer info: %v", err)
	}
	if ci.NumPending != uint64(n) {
		log.Fatalf("Expected to have %d messages pending, got %d\n", n, ci.NumPending)
	}

	r, start := 0, time.Now()
	for {
		msgs, err := sub.Fetch(500, nats.MaxWait(5*time.Second))
		if err != nil { // Timeout is ok normally, but here we should not see any errors.
			log.Fatalf("Error fetching messages: %v\n", err)
		}
		for _, msg := range msgs {
			msg.Ack()
			r++
		}
		if r >= n {
			break
		}
	}
	tt = time.Since(start)
	log.Printf("Took %v to fetch all %d messages, ~%0.f msgs/sec\n", tt, n, float64(n)/tt.Seconds())
	sub.Unsubscribe()

	////////////////////////////////////////////////////////
	// Do multiple go routines.
	////////////////////////////////////////////////////////
	log.Println("Multiple go routines of batched fetch")
	// Need to load messages again.
	for i := 0; i < n; i++ {
		if _, err := js.PublishAsync("foo", msg); err != nil {
			log.Fatalf("Unexpected publish error: %v\n", err)
		}
	}
	select {
	case <-js.PublishAsyncComplete():
	case <-time.After(5 * time.Second):
		log.Fatalf("Did not receive async publish completion signal\n")
	}

	sub, err = js.PullSubscribe("foo", "d33", nats.AckWait(2*time.Minute), nats.MaxAckPending(n))
	if err != nil {
		log.Fatalf("Unexpected error creating pull subscriber: %v\n", err)
	}
	ci, err = sub.ConsumerInfo()
	if err != nil {
		log.Fatalf("Unexpected error getting consumer info: %v", err)
	}
	if ci.NumPending != uint64(n) {
		log.Fatalf("Expected to have %d messages pending, got %d\n", n, ci.NumPending)
	}

	ngr, startCh := 10, make(chan bool)
	var wg sync.WaitGroup
	localSend := n / ngr

	for i := 0; i < ngr; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			<-startCh
			lr := 0
			for {
				msgs, err := sub.Fetch(500, nats.MaxWait(0))
				if err != nil { // Timeout is ok normally, but here we should not see any errors.
					log.Fatalf("Error fetching messages: %v\n", err)
				}
				for _, msg := range msgs {
					msg.Ack()
				}
				lr += len(msgs)
				if lr >= localSend {
					return
				}
			}
		}()
	}
	// Wait a bit for Go routines.
	time.Sleep(100 * time.Millisecond)
	start = time.Now()
	close(startCh)
	wg.Wait()

	tt = time.Since(start)
	log.Printf("Took %v to fetch all %d messages, ~%0.f msgs/sec\n", tt, n, float64(n)/tt.Seconds())
}

```

**Comment by carr123** [comment]
thanks derekcollison, i run your code on my server, the consuming is still too slow. 

my results:
2021/06/30 08:45:03 Took 5.58237049s to send 500000 messages, ~89568 msgs/sec
2021/06/30 08:45:03 Single batched fetch
^C

i terminated the program, the single fetch runs too long.
from the http endpoint, i notice the "total_messages" value decreses at a speed of about 500/s.
-------------------------------------------------------------------------------------------------------------------
i test it on a single server, config as follows.

#client talk to this address
listen: 10.91.26.225:7221

server_name : server225

jetstream {
    store_dir: /home/nats/demo/jetstreamdata
    max_mem: 2G
    max_file: 100G
}


accounts {
    APP: {
         jetstream: enabled
         users: [
          {
            user: admin
            password: abcd1234
            permissions: {
                publish: {
                    allow: [">"]
                }, 
                subscribe: {
                    allow: [">"]
                }
                allow_responses: true
            }
            allowed_connection_types: ["STANDARD"]
          }
        ]
    },
    SYS: { 
        users: [
            {user: root, password: root789, allowed_connection_types: ["STANDARD"]}
        ]
    },
}
system_account: SYS


max_connections: 1000

max_payload : 64MB

http: 10.91.26.225:8223


debug:   false
trace:   false
logtime: true
logfile_size_limit: 100MB
log_file: "/home/nats/demo/logs/nats-server.log"

**Comment by carr123** [comment]
thanks derekcollison, i run your code on my server, the consuming is still too slow. 

my results:
2021/06/30 08:45:03 Took 5.58237049s to send 500000 messages, ~89568 msgs/sec
2021/06/30 08:45:03 Single batched fetch
^C

i terminated the program, the single fetch runs too long.
from the http endpoint, i notice the "total_messages" value decreses at a speed of about 500/s.
-------------------------------------------------------------------------------------------------------------------
i test it on a single server, config as follows.

#client talk to this address
listen: 10.91.26.225:7221

server_name : server225

jetstream {
    store_dir: /home/nats/demo/jetstreamdata
    max_mem: 2G
    max_file: 100G
}


accounts {
    APP: {
         jetstream: enabled
         users: [
          {
            user: admin
            password: abcd1234
            permissions: {
                publish: {
                    allow: [">"]
                }, 
                subscribe: {
                    allow: [">"]
                }
                allow_responses: true
            }
            allowed_connection_types: ["STANDARD"]
          }
        ]
    },
    SYS: { 
        users: [
            {user: root, password: root789, allowed_connection_types: ["STANDARD"]}
        ]
    },
}
system_account: SYS


max_connections: 1000

max_payload : 64MB

http: 10.91.26.225:8223


debug:   false
trace:   false
logtime: true
logfile_size_limit: 100MB
log_file: "/home/nats/demo/logs/nats-server.log"

**Comment by derekcollison** [comment]
What result do you get  just running a 2.3.1 release server with -js flag and the program from above?

**Comment by carr123** [comment]
hi， derekcollison。 if i just run nats-server 2.3.1 with -js flag, and 100% use your code.
here are the results:
2021/06/30 12:09:34 Took 5.846983265s to send 500000 messages, ~85514 msgs/sec
2021/06/30 12:09:34 Single batched fetch
2021/06/30 12:09:44 Took 9.899456287s to fetch all 500000 messages, ~50508 msgs/sec
2021/06/30 12:09:44 Multiple go routines of batched fetch
2021/06/30 12:10:03 Took 13.691991873s to fetch all 500000 messages, ~36518 msgs/sec

looks better this time.

**Comment by carr123** [comment]
hi， derekcollison。 if i just run nats-server 2.3.1 with -js flag, and 100% use your code.
here are the results:
2021/06/30 12:09:34 Took 5.846983265s to send 500000 messages, ~85514 msgs/sec
2021/06/30 12:09:34 Single batched fetch
2021/06/30 12:09:44 Took 9.899456287s to fetch all 500000 messages, ~50508 msgs/sec
2021/06/30 12:09:44 Multiple go routines of batched fetch
2021/06/30 12:10:03 Took 13.691991873s to fetch all 500000 messages, ~36518 msgs/sec

looks better this time.

**Comment by carr123** [comment]
if a use a config file to start up nats-server, and set jetstream store_dir to "/tmp/nats/jetstream" like -js does.
the fetch time becomes too slow.
where am i wrong ?

**Comment by derekcollison** [comment]
We would need to look more closely at your config to be sure. Best to try eliminating certain things to corner what is causing the slowdown.

**Comment by carr123** [comment]
> We would need to look more closely at your config to be sure. Best to try eliminating certain things to corner what is causing the slowdown.

hi, derekcollison. I think i find the problem. if i set allow_responses=true in the config file, then message consuming becomes very slow. otherwise it's fast.

**Comment by carr123** [comment]
i find another issue,  when a client program  is fetching message , i kill it,  restart it, it resumes fetching and acking,  but it runs much slower than before.
i noticed when the  consumer's "NumAckPending" is zero, it fetches messages very fast, otherwise when NumAckPending is positive number(after restart the client program), it fetches very slowly and never become fast until all messages are consumed and  NumAckPending returns to zero. after that, newly published messages can be fetched fast again, performance recovered.

**Comment by derekcollison** [comment]
Can you show me the simplest config for the server that shows the slowdown?

On the second issue, most likely you have pending requests that need to clear properly from the last app?

**Comment by carr123** [comment]
accounts {
    APP: {
         jetstream: enabled
         users: [
          {
            user: "usr001"
            password: "hello"
            permissions: {
                publish: {
                    allow: [">"]
                }, 
                subscribe: {
                    allow: [">"]
                }
                allow_responses: true  //this cause the fetching action slow
            }
            allowed_connection_types: ["STANDARD"]
          }
        ]
    }
}

**Comment by carr123** [comment]
accounts {
    APP: {
         jetstream: enabled
         users: [
          {
            user: "usr001"
            password: "hello"
            permissions: {
                publish: {
                    allow: [">"]
                }, 
                subscribe: {
                    allow: [">"]
                }
                allow_responses: true  //this cause the fetching action slow
            }
            allowed_connection_types: ["STANDARD"]
          }
        ]
    }
}

**Comment by derekcollison** [comment]
What if you remove the allow [">"] which are non-sensical? Within an account by default everyone can send and receive from any subject by default.

**Comment by carr123** [comment]
> What if you remove the allow [">"] which are non-sensical? Within an account by default everyone can send and receive from any subject by default.

thanks for your advice, i have removed it.  the server runs well.

**Comment by carr123** [comment]
> What if you remove the allow [">"] which are non-sensical? Within an account by default everyone can send and receive from any subject by default.

thanks for your advice, i have removed it.  the server runs well.
