### ISSUE TITLE
Does the message of JetStream support protobuff encoding and decoding?

### ISSUE THREAD

**Issue by lx-world** [nats-io/nats.go#764]
Does the message of JetStream support protobuff encoding and decoding?

**Comment by lx-world** [comment]
***JetStream***  support  json or protobuff ?

**Comment by ripienaar** [comment]
You can put any bytes into the stream we do not care what format they are. So encode/decide in your own code before publishing and after receiving. 

So any serialisation format you choose.

**Comment by lx-world** [comment]
> You can put any bytes into the stream we do not care what format they are. So encode/decide in your own code before publishing and after receiving.
> 
> So any serialisation format you choose.

thanks!
Can it be used in combination with ***nats.NewEncodedConn***？

**Comment by ripienaar** [comment]
I have not used those really so not sure. But that seems to be their purpose.

**Comment by lx-world** [comment]
> I have not used those really so not sure. But that seems to be their purpose.

ok,  thank you.
