### ISSUE TITLE
Jetsream breaks nats Request Reply

### ISSUE THREAD

**Issue by aperrot42** [nats-io/nats.go#772]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [X] Included nats.go version
 - [X] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats.go` and the `nats-server` if one was involved:

nats.go : github.com/nats-io/nats.go v1.11.0
nats server : 2.2.5

#### OS/Container environment:

OS :
    Linux antonin-laptop 5.11.11-051111-generic #202103310025 SMP Thu Apr 1 01:54:13 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Container engine :
    Docker version 20.10.6, build 370c289

#### Steps or code to reproduce the issue:

Create a stream for all subject beginning by jetstream :

    $ nats str add MYSTREAM --subjects "jetstream.>" --ack --max-msgs=-1 --max-bytes=-1 --max-age=1y --storage file --retention limits --max-msg-size=-1 --discard=old

Using Go client make a request expecting a reply :

```golang
func SendAndReceive() {
  nc, err := nats.Connect("localhost", nats.Name("API PublishBytes Example"))
  if err != nil {
    log.Fatal(err)
  }
  defer nc.Close()
  resp, err := nc.Request("jetstream.mysubject", []byte("Hi Responder"), 1*time.Second)
  if string(resp.Data) != "Hello" {
    panic(fmt.Errorf("response is not from our responder %s", resp.Data))
  }
  fmt.Println("received correct message from reply")
}
```

Watch the subject and reply to incoming message with a simple "Hello" :

```golang
func Reply(w *sync.WaitGroup) {
  nc, err := nats.Connect("localhost")
  if err != nil {
    log.Fatal(err)
  }
  defer nc.Close()

  // Subscribe
  sub, err := nc.SubscribeSync("jetstream.mysubject")
  if err != nil {
    log.Fatal(err)
  }
  
  // Read a message
  msg, err := sub.NextMsg(10 * time.Second)
  if err != nil {
    log.Fatal(err)
  }

  // Send the time as the response.
  msg.Respond([]byte("Hello"))
}
```

#### Expected result:

I expect to receive the reponse from my Reply function ( from `nc.Request`) and see on my terminal :

    received correct message from reply

#### Actual result:

I revceive a different message certainly from jetstream engine that breaks the usual request/reply interface of nats go client :

    panic: response is not from our responder {"stream":"MYSTREAM","seq":1}

**Comment by aperrot42** [comment]
Here is a peice of code to try it home :


```golang
package main

import (
	"fmt"
	"github.com/nats-io/nats.go"
	"log"
	"sync"
	"time"
)

func main() {
	wait := sync.WaitGroup{}
	wait.Add(1)
	go Reply(&wait)
	wait.Wait()

	SendAndReceive()
}

func SendAndReceive() {
	nc, err := nats.Connect("localhost", nats.Name("API PublishBytes Example"))
	if err != nil {
		log.Fatal(err)
	}
	defer nc.Close()

	resp, err := nc.Request("jetstream.mysubject", []byte("Hi Responder"), 1*time.Second)
	if string(resp.Data) != "Hello" {
		panic(fmt.Errorf("response is not from our responder %s", resp.Data))
	}
	fmt.Println("Received correct message from Reply")
}

func Reply(w *sync.WaitGroup) {
	nc, err := nats.Connect("localhost")
	if err != nil {
		log.Fatal(err)
	}
	defer nc.Close()

	// Subscribe
	sub, err := nc.SubscribeSync("jetstream.mysubject")
	if err != nil {
		log.Fatal(err)
	}
	w.Done()

	// Read a message
	msg, err := sub.NextMsg(10 * time.Second)
	if err != nil {
		log.Fatal(err)
	}

	// Send the time as the response.
	msg.Respond([]byte("Hello"))
}
```

You can run it before and after running 

    nats str add MYSTREAM --subjects "jetstream.>" --ack --max-msgs=-1 --max-bytes=-1 --max-age=1y --storage file --retention limits --max-msg-size=-1 --discard=old

to see the difference.

**Comment by ripienaar** [comment]
JetStream does not store the reply subject - request/reply is inherintly about coupled real time requests where a stream is for uncoupled operations.

I dont think it breaks it as much as its a different concpet all together.  Specifically I'd avoid using a `nc` to subscribe to any subjects JetStream is also listening on.

**Comment by aperrot42** [comment]
exactly the thing is there is no indication that a subject may not be usbable for simple request/reply messaging.

So it is the client user's responsiblity whe using nats go client to check that a subject is not yet "managed" by jetstream before using it ?

**Comment by ripienaar** [comment]
At present I think so yes, I agree thats an unfortunate restriction.  If you did want to have a stream on that subject - perhaps to capture a audit trail of requests while also have request/reply work - you need to set the stream to not do acks.

**Comment by aperrot42** [comment]
thanks for your answer @ripienaar I will do so and add a client wrapper for our devs for this matter. Just wanted to point out the situation that may arise in some systems using jetstream AND nats client request on the same nats cluster. Do you think that this behaviour can be documented somewhere ?

**Comment by derekcollison** [comment]
We thought about this from the outset of the JetStream design.

First, for the most part request/reply does not need persistence, I feel its almost an anti-pattern. Mostly.
That being said, we do realize there are situations that may require a request/reply pattern and JetStream, whether that is for audit, governance, what have you.

So you have two options.

1. Form a response barrier, I think this was what was being considered above. You need to account for multiple responses.
2. If you are using JetStream more for analytics, soft audit etc. You can create the stream and tell the system not to produce pubAcks regardless of the presence of the reply subject.

https://github.com/nats-io/nats-server/blob/main/server/stream.go#L53
