### ISSUE TITLE
JS: Library possibly removes a consumer when it should not

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats.go#776]
I think it is dangerous to delete (js.DeleteConsumer) a consumer when user calls sub.Unsubscribe(). Users may be used to call this function as a good practice when being done with a subscription.

The issue here is that if a user subscribes to a consumer that it does not "own" (meaning that the library did not create it), then Unsubscribe() will delete it: https://github.com/nats-io/nats.go/blob/c7fc3c7fdf53ba0fef1a28400253d7f8d2c1a037/js.go#L928

I believe that the library should ONLY delete JS consumer if it has created it for an ephemeral consumer (called AddConsumer inside js.subscribe()) and that there is a guarantee that no other subscription is using it (so not queue sub, or when AddConsumer returned an error meaning that someone else called AddConsumer()).

**Comment by aricart** [comment]
I would propose that magic subscribe be limited to ephemerals. Durables are important contract for applications that need to be explicitly created and lifecycled.

**Comment by ripienaar** [comment]
I think someone should take a stab of documenting the overall behavior of subscribe in a adr :)

**Comment by philkuz** [comment]
Do you recommend any work arounds? Running into an issue after converting old QueueSubscribe durable STAN Channel to a corresponding JetStream durable QueueSubscribe. `Unsubscribing` will kill the durable consumer. Not Unsubscribing seems like it will leak state in NATS.

**Comment by wallyqs** [comment]
@philkuz in current nats.go client you can use `Drain()` instead to detach, but we will remove the current behavior of deleting the consumer as well

**Comment by philkuz** [comment]
will try that out. Thanks @wallyqs !
