### ISSUE TITLE
Nats Go client using HTTP transport

### ISSUE THREAD

**Issue by tamalsaha** [nats-io/nats.go#777]
## Feature Request
A Go version of https://github.com/nats-io/nats.js so that only http/https is used to communicate with nats server.

#### Use Case:
Use nats-go in an environment that only allows http/https connections.

**Comment by ripienaar** [comment]
Nats.is use the same protocol as this client. A pure TCP socket or websockets. Both supported by nats.go also.

**Comment by tamalsaha** [comment]
Cool! Could you please point to any sample code that shows how to use websocket with nats-go client?

**Comment by kozlovic** [comment]
Simply use `ws` or `wss` as the prefix:
```
nats.Connect("ws://myHost:8080", ..)
```

**Comment by tamalsaha** [comment]
Thanks!

**Comment by kozlovic** [comment]
You would need to configure the server to accept websocket connections: https://docs.nats.io/nats-server/configuration/websocket

**Comment by tamalsaha** [comment]
Is there any performance implication in using nats TCP vs ws connection?

**Comment by kozlovic** [comment]
Probably since there is additional websocket framing/unmasking, or even more if using compression. You can bench it with regular `nats` tool since having websocket is simply using `ws://` scheme.

**Comment by alexellis** [comment]
That is great.. I just asked @tamalsaha a similar question - for using NATS to report app usage behind firewalls / proxies etc, where outgoing TCP connections are not possible.

**Comment by derekcollison** [comment]
For setups where solicitation of a connection, be it client or server, can only be one way then ws is the way to go especially when there is a network security element in play like firewalls etc.
