### ISSUE TITLE
jetstream fail to subscribe

### ISSUE THREAD

**Issue by carr123** [nats-io/nats.go#780]
I create a stream using Retention=nats.WorkQueuePolicy,  then i subscribe to receive messages, everything is ok.

```go
js.Subscribe("ORDERS.*", func(msg *nats.Msg) {
  log.Println( " recv data:", string(msg.Data))
  msg.Ack()
})
```

but, if i kill my program rudely, without calling Unsubscribe, the folder on my server representing the randomly named consumer still there, then i restart my program, error reported : "nats: filtered consumer not unique on workqueue stream".

 is there any best practice to code jetstream that can survice an unexpected program restart ?

**Comment by derekcollison** [comment]
WorkQueues can have only 1 JetStream consumer, but as many of them as you want can pull from that consumer. So when you apps restarts it is trying to recreate it again.

You may also want to do a pull subscriber which aligns better with work queues.
