### ISSUE TITLE
JetStream unable to Pub/Pull messages from stream if consumer/stream leader node is down

### ISSUE THREAD

**Issue by rleiwang** [nats-io/nats.go#781]
I started a 3 nodes JetStream cluster via docker compose. Publish to and pull messages from stream are working as designed. But if I shutdown stream or consumer raft leader container, client is unable to publish/pull message to/from the stream. After leader node comes back, existing subscribers need to reconnect in order to receive new messages. Is this by design? Meta node leader is re-elected, but not stream or consumer leader.

The version of server/client is following:
```
github.com/nats-io/nats-server/v2 v2.3.2
github.com/nats-io/nats.go v1.11.1
```

**Comment by derekcollison** [comment]
How big is your cluster?

How big was the Replication for the stream?
Was the consumer durable or ephemeral?

In general if say you said R2 for your stream, durables will inherit the R factor and with R=2 if you have a single loss quorum would be lost and not able to make progress. There is an advisory that will go out reporting so. You can move peers within an asset like a stream or consumer, and we will be re-enabling auto-remediation in a future release. It was not totally stable in all outage scenarios so for now is disabled but an operator can do these operation manually.

**Comment by rleiwang** [comment]
Thanks @derekcollison for the quick response. I've got it working. Initially, I didn't specify stream's replication value, it created only one raft node. The consumer is a durable Pull subscriber. After reading your reply, I set the replication value to 3. It elected a new consumer leader afterwards and there is no service disruption if consumer leader node is down.
