### ISSUE TITLE
how can I find the publisher

### ISSUE THREAD

**Issue by carr123** [nats-io/nats.go#784]
if there's a lot of publisher and one subscriber. how can i find which publisher(by its id or something ?) send a specific message ?
normal, client info can be included in the message body ,  but sometimes  subscriber received malformated contents and could not find the client info in the message body.

**Comment by ripienaar** [comment]
We do not share information about publishers along with messages so in general it’s not possible. 

Maybe set a header on the publisher

**Comment by carr123** [comment]
thanks

**Comment by derekcollison** [comment]
We do have this information for exported services iff the importer shares their client information.

We use this for JetStream and others can use it as well, need to get better docs.

**Comment by derekcollison** [comment]
Use subject transform to move the import to the real subject and use a more generic one for publishers.

**Comment by derekcollison** [comment]
Apologies - did you figure this out or still need a working example?

**Comment by phanmn** [comment]
Hi @derekcollison , it would be great if you show us a working example, many thanks, but I wonder why dont we have an simple option so that if an user can choose to share information when publish like the share option between accounts !?

**Comment by phanmn** [comment]
> Apologies - do you still need an example here?

Thank you for your attention, it would be great if you show us a working example, many thanks, so I can compare with my solution and other guys can see if they need
