### ISSUE TITLE
Subscription subject interning

### ISSUE THREAD

**Issue by moredure** [nats-io/nats.go#819]
## Feature Request
Reduce allocation by interning subjects using predefined map of subjects or just by utilising intern.Bytes
#### Use Case:
Subscriptions
#### Proposed Change:
```go
import "github.com/josharian/intern"
subj := intern.Bytes(nc.ps.ma.subject)
```
or some predefined map
```go
subj := nc.subjects[string(nc.ps.ma.subject)]
```
#### Who Benefits From The Change(s)?
Users of subscriptions

**Comment by derekcollison** [comment]
We either copy or send to a socket any message (with subject) that is given to us, so internal to the library not sure this would help too much, but could be used above the NATS lib.

**Comment by moredure** [comment]
I am talking about processMsg in Subscribe* methods

**Comment by derekcollison** [comment]
Do we have any measurable results?

**Comment by moredure** [comment]
I also started reusing Msg container (since my application using fixed size messages) and gotten rid of allocations for subscriptions in my use case. I will check if there is any benchmarks I will be able to run them on processMsg.

**Comment by derekcollison** [comment]
If it has a definitive impact I am all for that for sure. Thanks!

**Comment by moredure** [comment]
What about this https://github.com/nats-io/nats.go/pull/824 ?

**Comment by moredure** [comment]
Regarding message container reuse I am using smth like this and totaly ok with because of fixed message sizes
```go

var msgPool = &sync.Pool{
	New: func() interface{} {
		return new(Msg)
	},
}

func (m *Msg) Release() {
	m.Subject = ""
	m.Reply = ""
	m.Header = nil
	m.Data = m.Data[:0]
	m.Sub = nil
	m.next = nil
	m.barrier = nil
	m.ackd = 0
	msgPool.Put(m)
}

m := msgPool.Get().(*Msg)

	if !nc.ps.msgCopied {
		if cap(m.Data) < len(data) {
			m.Data = m.Data[:cap(m.Data)]
			m.Data = append(m.Data, make([]byte, len(data) - cap(m.Data))...)
			copy(m.Data, data)
		} else {
			m.Data = m.Data[:len(data)]
			copy(m.Data, data)
		}
	} else {
		m.Data = data
	}
```
