### ISSUE TITLE
StartSequence and Ack

### ISSUE THREAD

**Issue by biskit** [nats-io/nats.go#820]
Hi,
I'm trying to figure how to do deliver once. 
In this example, I have messages manually Ack() and I start from the same durable stream. I would assume the same message will not show up twice as it's been Ack()'d.

```go
package main

import (
        "fmt"
        "os"
        "time"

        "github.com/nats-io/nats.go"
)

func main() {
        timeout := 5 * time.Second
        // Connect to NATS
        nc, err := nats.Connect("nats://localhost:4222")
        if err != nil {
                fmt.Println("--->>>error", err)
                os.Exit(-1)
        }

        // Create JetStream Context
        js, err := nc.JetStream(nats.PublishAsyncMaxPending(256))
        if err != nil {
                fmt.Println("--->>>1error", err)
                os.Exit(-1)
        }

        err = js.DeleteStream("ORDERS")
        err = js.DeleteStream("ORDERS") // test
        if err != nil {
                fmt.Println("--->>>10aerror", err)
        }

        _, err = js.AddStream(&nats.StreamConfig{
                Name:     "ORDERS",
                Subjects: []string{"scratch"},
        })
        if err != nil {
                fmt.Println("--->>>11aerror", err)
                os.Exit(-1)
        }
        _, err = js.UpdateStream(&nats.StreamConfig{
                Name:     "ORDERS",
                Subjects: []string{"scratch", "bar"},
        })
        if err != nil {
                fmt.Println("--->>>11aerror", err)
                os.Exit(-1)
        }

        // Simple Stream Publisher -- publish to "bar"
        _, err = js.Publish("bar", []byte("hellobar"))
        if err != nil {
                fmt.Println("--->>>1aerror", err)
                os.Exit(-1)
        }

        // Simple Async Stream Publisher -- publish to "scratch"
        for i := 0; i < 500; i++ {
                js.PublishAsync("scratch", []byte(fmt.Sprintf("%s-%d", "hello", i)))
        }
        select {
        case <-js.PublishAsyncComplete():
                fmt.Println("Publish complete")
        case <-time.After(5 * time.Second):
                fmt.Println("Did not resolve in time")
        }

        // Simple Sync Durable Consumer (optional SubOpts at the end)
        sub, err := js.QueueSubscribeSync("scratch", "foo", nats.Durable("MONITOR"), nats.MaxDeliver(3), nats.AckExplicit())
        m, err := sub.NextMsg(timeout)
        if err != nil {
                fmt.Println("--->>>2error", err)
                os.Exit(-1)
        }
        fmt.Println("---->>>m", string(m.Data))
        m.Ack()
        sub.Unsubscribe()

        // Simple Pull Consumer
        sub, err = js.PullSubscribe("*", "MONITOR")
        msgs, err := sub.Fetch(10)
        if err != nil {
                fmt.Println("--->>>3error", err)
                os.Exit(-1)
        }
        for i, m := range msgs {
                fmt.Println("---->>>msg", i, string(m.Data))
        }

        // Unsubscribe
        sub.Unsubscribe()

        // Drain
        sub.Drain()
}
```

output:
``` 
--->>>10aerror nats: stream not found
Publish complete
---->>>m hello-0
---->>>msg 0 hellobar
---->>>msg 1 hello-0
---->>>msg 2 hello-1
---->>>msg 3 hello-2
---->>>msg 4 hello-3
---->>>msg 5 hello-4
---->>>msg 6 hello-5
---->>>msg 7 hello-6
---->>>msg 8 hello-7
---->>>msg 9 hello-8
```

I would have thought `hello-0` would not show up second time as it has been manually Ack()'d

**Comment by kozlovic** [comment]
@biskit The first time you call js.QueueSubscribeSync() with durable name "MONITOR", and assuming that you did not create a JetStream consumer outside of this call, the library created the JS consumer internally, and since it "owns" it, it will be deleted on Unsubscribe().

When later you call js.PullSubscribe() on "MONITOR", you are creating a new JS consumer again.

To avoid this confusion, I would recommend that you create the consumer the same way you have created your stream, using js.AddConsumer(). If you had done so, the first js.QueueSubscribe() would have bound to it, and on Unsubscribe() would not have been deleted. That is, only if you use the latest server and client. See detailed "Breaking Changes" in the release notes of Go client v1.12.0: https://github.com/nats-io/nats.go/releases/tag/v1.12.0

So if you created the JS Consumer to be for a queue group, you would have to specify `DeliverGroup` when creating the consumer with js.AddConsumer(). If that was the case, the call to js.PullSubscribe() will have likely failed telling you that the JetStream consumer was created for a queue group.

**Comment by biskit** [comment]
Thank you. Some of my confusion arises from looking at the Basic Usage sample https://github.com/nats-io/nats.go/tree/eb89c8a458bfc60401dbc0aa14f7a8b35598406d#jetstream-basic-usage

Here a `Publish` happens without an `AddStream` but my trying here fails with `nats: no response from stream`

So, is an `AddStream` call a must before operating on it.

**Comment by kozlovic** [comment]
@biskit Ok, we could maybe improve this by making then separate (not part of the same "code" block), but not sure if it would have made a difference. The README is simply showing some of the API calls, does not mean that it is valid to do them all in the shown sequence.

**Comment by biskit** [comment]
@kozlovic understood. it does help someone like me to have a working example. Also, it helps people posting replies on SO from writing replies like this. eg: https://stackoverflow.com/questions/67452921/nats-no-response-from-stream

what adds the confusion is the example shown in SO seems to work then, but will not anymore. As an aside, was this a breaking change somewhere down the line?

thanks again for your patience.

**Comment by biskit** [comment]
What I was trying to say is in the `examples` dir a couple of JetStream examples will be very helpful. Like https://github.com/nats-io/stan.go/tree/main/examples

**Comment by kozlovic** [comment]
> Also, it helps people posting replies on SO from writing replies like this. eg: https://stackoverflow.com/questions/67452921/nats-no-response-from-stream

If the link above is correct, it is not related to subscribe, but to the fact that the stream was either not created, or as the person answering suggested, that you need to publish on the subject that the stream is handling, not the name of the stream.

> what adds the confusion is the example shown in SO seems to work then, but will not anymore. As an aside, was this a breaking change somewhere down the line?

Not sure what you are asking here.

> What I was trying to say is in the examples dir a couple of JetStream examples will be very helpful. Like https://github.com/nats-io/stan.go/tree/main/examples

There are some examples (that compile, not necessarily the bests at showing proper usage): https://github.com/nats-io/nats.go/blob/main/example_test.go#L282

But I am not arguing with you: we need to be better at doc, no question about it.

**Comment by biskit** [comment]
> There are some examples (that compile, not necessarily the bests at showing proper usage): https://github.com/nats-io/nats.go/blob/main/example_test.go

is extremely helpful.
