### ISSUE TITLE
nats.DisconnectErrHandler seems to be passing empty connection

### ISSUE THREAD

**Issue by gobwas** [nats-io/nats.go#836]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included nats.go version
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats.go` and the `nats-server` if one was involved:

nats.go: v1.12.2
nats-server: v2.5.0

#### OS/Container environment:
Fedora 32; Linux 5.11.19-100.fc32.x86_64

#### Steps or code to reproduce the issue:

1. Start the `nats-server -js`
2. Setup `nats.DisconnectErrHandler()` option to log `conn.ConnectedUrl()` or `conn.ConnectedAddr()`
3. Connect using `nats.Connect()`
3. Stop the `nats-server -js` process from step (1)
4. Connection doesn't provide url nor addr in the disconnection handler

#### Expected result:

`conn.ConnectedUrl()` and `conn.ConnectedAddr()` return non-empty strings.

#### Actual result:

`conn.ConnectedUrl()` and `conn.ConnectedAddr()` return empty strings.

----

The reason of this behaviour is that both mentioned getters return actual values only if connection has state`CONNECTED`.
The URL used to connect as well as its resolved address might be useful even after connection is in `CONNECTED` state. At least to follow up the connection history in the logs.

**Comment by kozlovic** [comment]
@gobwas This is not a bug. As the name indicates, these APIs return the URL/Address of the server the connection is currently connected to. If you invoke them in the disconnected handler (and assuming that the connection is still disconnected at this point), then it is normal that they return the empty string.
I would recommend that you print the connect url/addr (if you need) after a successful connect and in the `ReconnectHandler`.

**Comment by gobwas** [comment]
@kozlovic do you have any suggestion how to log the message about what (url or addr) connection has been disconnected? The name can also be read as "the url used at the moment this connection was actually established".

**Comment by gobwas** [comment]
I mean I want to see something like this in the logs:
```
connection to `nats://127.0.0.1:4222` has been established
connection to `nats://127.0.0.1:4222` has been disconnected
connection to `nats://127.0.0.1:4222` has been reconnected
```

But instead I see this:
```
connection to `nats://127.0.0.1:4222` has been established
connection to `` has been disconnected
connection to `nats://127.0.0.1:4222` has been reconnected
```

Also, ideally it would be nice to have proxied `LocalAddr()` as well, to unequivocally match connections in case of using multiple connections to a single nats-server to see something like this:
```
connection to `nats://127.0.0.1:4222` (127.0.0.1:57555->127.0.0.1:4222) has been established
connection to `nats://127.0.0.1:4222` (127.0.0.1:57555->127.0.0.1:4222) has been disconnected
connection to `nats://127.0.0.1:4222` (127.0.0.1:57555->127.0.0.1:4222) has been reconnected
```

**Comment by kozlovic** [comment]
@gobwas I don't feel comfortable changing ConnectedUrl()/Addr() to return the last know url. The API was meant to return the current connected server url/addr. We even have a test that checks that the empty string is returned after a close.
We could add API to return the last know, or have a Connect() option to change the behavior so that the last know value is returned, even when disconnected/closed.

> Also, ideally it would be nice to have proxied LocalAddr() as well, to unequivocally match connections in case of using multiple connections to a single nats-server to see something like this:

You mean a `ConnectedLocalAddr()` (as opposed to ConnectedAddr() which returns the RemoteAddr().String())?

But not sure what you mean by "unequivocally match connections in case of using multiple connections to a single nats-server". How is that helping to identify a given connection in your code? Is that that you want this port so that you can check about the port in the server log? If not, simply printing the connection pointer is enough to make sure that you have unique traces in the handler, or you can "name" those connections as part of setting the handler:
```
func disconnectFunc(connName string) ConnErrHandler {
    return func(nc *nats.Conn, err error) {
        fmt.Printf("Connection %s has been disconnected: %v\n", connName, err)
    }
}
...
nats.Connect(.., nats.DisconnectHandler(disconnectFunc("my_connection")))
```

**Comment by gobwas** [comment]
Hey @kozlovic,

Thanks for your reply.

I see that changing the `Connected{Url,Addr}()` may break something in already existing applications.
Do we have a `Connect()` option to be called right after connection become established? I we had this, then we would be able to store anything related to the connection somewhere in a user application using connection pointer as a key (as you mentioned before). In my case, I would be able to store needed url/addr in some `map[*nats.Conn]string` in my code and then consult the map for other callbacks related to runtime of the connection.

Regarding `ConnectedLocalAddr()` yes, I meant the local port. But I agree, using connection pointer as an identifier for logs will be useful as well. It still could be theoretically useful if you want to tcpdump something for debugging purproses or something like that, but again, for my case pointer is enough. Thanks!

Also, adding a comment about intentions for returning empty strings for disconnected conns to `Connected{Url,Addr}()` would save some time spent on similar issues in the future :)

**Comment by sdkim81** [comment]
In my case `err` is always `EOF` when `DisconnectErrHandler` is called.

I set `nats.DisconnectErrHandler(func(conn *nats.Conn, err error)` and print out `err` but it only shows `EOF`

I've tested two cases. 
 1. Shutdown server
 2. authentication expired.

go client version : 1.11
go server version : 2.2.2

I wanted to know the reason of disconnect, so I tried to re-issue a credential for authentication expired case but no way to know the reason.

Somebody help me?

**Comment by gobwas** [comment]
@sdkim81 I'm not sure that from client's connection perspective the error should be different?

**Comment by sdkim81** [comment]
@gobwas 

I think it's nice if error message give some useful information to handle the disconnection error. 

When I test authentication expired error,  retry handler tries to connect only 2 times and stop retrying even though I set 1hr for retrying connection.

How I can handle a disconnection by `authentication expired error` ?
I thought  `DisconnectErrHandler` will pass a useful error but it's EOF. 

My idea was like below but it didn't work!

```
nats.DisconnectErrHandler(func(conn *nats.Conn, err error) {
    if err is authentication expired {
       ask  new credential file and store.
    }
})
```

**Comment by kozlovic** [comment]
@sdkim81 Please use the `ErrorHandler` to be notified of those errors. But note that the callbacks are invoked asynchronously, but if you have a reasonable reconnect wait, etc.. then your application should have enough time to do the things it wants to do based on the error before the next reconnect attempt.
