### ISSUE TITLE
[TLS termination] frequent timeout error on connection 

### ISSUE THREAD

**Issue by sdkim81** [nats-io/nats.go#850]
Hello,

To initiate a TLS  on connection,  I'm testing it with websocket scheme in Go client.
(ref : https://github.com/nats-io/nats-server/issues/291#issuecomment-942310904 )

Connection flow is like below and TLS termination  works.
`NATS GO Client    <--- TLS ---> Network Load balancer (with ACM)  <---- No TLS ---> NATS Server (2.6.2).`

By this way, I can establish a secure connection without TLS configuration in NATS server.
But I've faced an issue that frequently error on connection. 

Client code base: 
https://github.com/nats-io/nats.go/commit/0fdad3d17145a8b4ff73be395423d5deb0365615

Test with :
https://github.com/nats-io/nats.go/tree/main/examples/nats-sub

Normal case : 
```
nats-sub -s wss://host-domain:8080 topic
Connection :  takes +1.200104218s
Listening on [topic]
```

Error Case 1. Default time out (2sec)
```
nats-sub -s wss://host-domain:8080 topic
read tcp xxxxxx:41246->xxxxxxx:80: i/o timeout
```

Error Case 2.  With  timeout (10 sec)
 In this case, error is `unexpected EOF` not  read tcp timeout.

Error comes from https://github.com/nats-io/nats.go/blob/main/ws.go#L596 but 
I can't figure out which part is a root cause of this problem until now. 

Where should I check to solve this issue?

**Comment by sdkim81** [comment]
@kozlovic  Thank you for prompt answer for my question. 

Here is what I checked till now. 

> Next, you post the error case 1 with default timeout of 2sec. Can you clarify what timeout you are referring to here? Have you measure the time around the connect itself (like you did in the success case).

Timeout is the client timeout set by `nats.Timeout` API. AFAIK default timeout is 2 sec.
It seems nats.go client reference this value some places.  (i.e : wsInitHandshake)
```
opts = append(opts, nats.Timeout(10 * time.Second))
```

And the connection time itself for `net.Dial`  is around 200ms and `tls.Dial` is 400~500ms


> The unexpected EOF happens during the read of the HTTP response. I have no idea if this is the LB cutting the connection, etc.. Do you see any connection passed to the NATS Server at all? As a debug step, please run the server with -DV and see if the connection makes it passed the LB.

I've tested with below code and it seems server doesn't send a INFO message to client.

Test code <--- TLS ---> Network Load balancer (with ACM) <---- No TLS ---> NATS Server (2.6.2).

```
func tls_test() {
	log.SetFlags(log.Lshortfile)

	conf := &tls.Config{
	}

	now := time.Now()
	conn, err := tls.Dial("tcp", "host address", conf)
	if err != nil {
		log.Println(err)
		return
	}

	log.Printf("Dial done : %+v" , time.Since(now))
	defer conn.Close()

	n, err := conn.Write([]byte("hello\n"))
	if err != nil {
		log.Println(n, err)
		return
	}

	log.Println(n)

	buf := make([]byte, 4096)
	n, err = conn.Read(buf)
	if err != nil {
		log.Println(n, err)
		return
	}

	println(string(buf[:n]))
}
```

(Fail)
main.go:42: Dial done : 505.3949ms
main.go:54: 6
main.go:59: 0 EOF


(Pass)
main.go:42: Dial done : 495.3949ms
main.go:54: 6
main.go:59: 
`INFO {"server_id":"NCCD42LTTNOL72CD5MXXCMCVWUPVSKPY2HMCCT7JIHO4VHZILYS2NBZP","server_name":"NCCD42LTTNOL72CD5MXXCMCVWUPVSKPY2HMCCT7JIHO4VHZILYS2NBZP","version":"2.6.2" .....}`


In the server side log, I can see the protocol violoation error about sending "hello" message to server.

```
Client connection created
->> [-ERR Unknown Protocol Operation]
Client parser ERROR, state=18, i=1: proto='"ello"...'
Client connection closed: Protocol Violation
```

So I think connection is fine and read & write loop is created well but it's not sure server sends an INFO protocol or not because there is no debug for this. 

Let me know where should I add a log to check the server send an INFO protocol. 

Then I'll check. 
 1. Whether server sends an INFO protocol or not.
 2 INFO message is cut by NLB.

**Comment by kozlovic** [comment]
@sdkim81 You can't use "raw" connection and write to it, this is going to cause protocol violations. Please use actual nats.go APIs. I asked to measure the time it takes before and after the Connect() regardless of error, you did not have to try with raw connection.
The protocol is that after a TCP connection, the server will send an INFO. When you write "hello" to the raw connection, the server may receive and close the connection prior to be able to send the INFO, so this is not a good test. If anything, your "raw" connection test should not write, simply read waiting for the INFO.

If you want to trace in the server side, there would be several places you could do that. The first would be the websocket upgrade entrypoint here: https://github.com/nats-io/nats-server/blob/3fbf9ddcbc6a8c40d278aec1e65981299febbad3/server/websocket.go#L682. You could print something there and if there is no print, then clearly the server is not receiving the connection attempt from the LB.
You asked where to trace the INFO, and that would be here: https://github.com/nats-io/nats-server/blob/3fbf9ddcbc6a8c40d278aec1e65981299febbad3/server/websocket.go#L1192. But really, if you run the server with -DV, or at least -D, then you see that you should see the "Client connection created" debug trace already. The function createWSClient (which the referenced code belongs to) is invoked after the wsUpgrade() function (which I linked to first) returns, as seen here: https://github.com/nats-io/nats-server/blob/3fbf9ddcbc6a8c40d278aec1e65981299febbad3/server/websocket.go#L1098. If there is a failure in wsUpgrade(), it should be logged (see few line above the last link).
