### ISSUE TITLE
Unexpected Request timeout

### ISSUE THREAD

**Issue by KnBrBz** [nats-io/nats.go#852]
When developing application using Nats, for events and request managing, we have some issues with request timeout.
Created a snippet code, that imitates our code behavior [natsrequest](https://github.com/KnBrBz/natsrequest)

## Problem

Program fails with message like Source.NNNN.N request: *Request.Publish: nats: timeout.

Number of iterations that succeeds may vary.

## Program structure

- Events - imitates events every 100ms.
- Sources - imitates requests from up to 2000 sources, starts from 200 with step 200. Each source sends a request every 500ms.
- Destinations - every destination subscribes for all 100 events and one source request. One goroutine for events processing, other for requests.

There is two Nats connection instances for Events, Sources and one encoded connection for Destinations.

Server version 2.6.2

Code was tested first on Win10, used a release binary. Timeout was set to 5 seconds and was exceeded. After that it was decreased to 1 second, just for time economy.

After that it was tested also in WSL Ubuntu 20.04.2 LTS. Nats was installed via docker.

Some program log for WSL:
```
2021/10/17 15:50:54.784505 Source.919 answer `Source.919.8 response` time 948.380228ms
2021/10/17 15:50:55.987874 Source.606.9 request: *Request.Publish: nats: timeout
2021/10/17 15:50:55.987891 Source.69.9 request: *Request.Publish: nats: timeout
2021/10/17 15:50:55.987907 Source.1173.9 request: *Request.Publish: nats: timeout
2021/10/17 15:50:55.987943 Source.1098.9 request: *Request.Publish: nats: timeout
```
## Question

Is it something wrong with code, or this is just hardware issue, or maybe we should use different connection for request processing?

## Reasoning

We experienced such error in our development process - our program send request timeout error after some time under stress test. After inspecting some logs, we saw that the most time delay was between moments
- request answer publish
- getting answer in source

**Comment by derekcollison** [comment]
It would be helpful if you could share the client code, or something that shows the issue.
Also, what does `nats account report connections` return in your setup when you see the timeouts?

**Comment by KnBrBz** [comment]
We cannot show real client code. But link to above [snippet](https://github.com/KnBrBz/natsrequest) actually corresponds our architecture and we can reproduce behavior when run it.

`nats account report connections` - do not know what it is. It is something related to monitoring Nats server?

**Comment by KnBrBz** [comment]
Thank you for tool link.
We don't use queue groups, beaucase in our scenario one destination should process all triggered events and requests.

**Comment by wallyqs** [comment]
Hi @KnBrBz I took a quick look at the code and I'd suggest doing the couple of things to investigate the problem:

- Add an error callback handler when making the connection, this would help make sure that it is not a client side slow consumer issue 
https://github.com/KnBrBz/natsrequest/blob/d3b90b7c9dbcf779d9af19fefa7f005a8464d03a/main.go#L26

- Noticed that using BindRecvChan and encoders, when using this API need to make sure that the size of the channel is big enough to avoid the clients dropping the messages due to maxing out the size of the buffer. In this case if the channel is 1000 then with enough sustained traffic might be easy to make it drop requests and run into `nats: timeout` errors:
https://github.com/KnBrBz/natsrequest/blob/9cf5c28f37c3319fbbd66b7bedf3551c0ed1e0d7/destination/answer/answer.go#L25

Plain `Subscribe` works much better since uses less memory than the channel based APIs, but as a workaround I'd try to make the channels bigger, for example regular Subscribe uses a 65536 msgs buffer size by default.

**Comment by KnBrBz** [comment]
- added error handler for connection https://github.com/KnBrBz/natsrequest/blob/5fe0c18b3a3228029335ef35517b28284501c16d/main.go#L32
- using plain `Subscribe`, but writing message data to events channel https://github.com/KnBrBz/natsrequest/blob/main/destination/answer/answer.go#L40
- added check for events channel length https://github.com/KnBrBz/natsrequest/blob/main/destination/destination.go#L51 - because none of the checks were not triggered, events channel length was not changed

Still got same timeout error. 
`nats account report connections` before timeout
![изображение](https://user-images.githubusercontent.com/36660977/137706168-d6dc50d3-74d0-44a1-b596-e565121cc513.png)

Will try to use one more connection for request in `Source`

**Comment by KnBrBz** [comment]
On powerful computer snippet finished without errors. There was only warnings in Nats server
```
[1] 2021/10/18 18:45:05.266171 [WRN] 172.17.0.1:46830 - cid:9 - "v1.13.0:go" - Readloop processing time: 4.885427818s
[1] 2021/10/18 18:45:09.845934 [WRN] 172.17.0.1:46830 - cid:9 - "v1.13.0:go" - Readloop processing time: 4.579573534s
[1] 2021/10/18 18:45:14.568379 [WRN] 172.17.0.1:46830 - cid:9 - "v1.13.0:go" - Readloop processing time: 4.722339674s
[1] 2021/10/18 18:45:19.594573 [WRN] 172.17.0.1:46830 - cid:9 - "v1.13.0:go" - Readloop processing time: 5.026116222s
[1] 2021/10/18 18:45:23.837969 [WRN] 172.17.0.1:46830 - cid:9 - "v1.13.0:go" - Readloop processing time: 4.243307224s
[1] 2021/10/18 18:45:28.254241 [WRN] 172.17.0.1:46830 - cid:9 - "v1.13.0:go" - Readloop processing time: 4.416183771s
[1] 2021/10/18 18:45:32.669213 [WRN] 172.17.0.1:46830 - cid:9 - "v1.13.0:go" - Readloop processing time: 4.414876667s
```

Does this warnings mean, that it takes several seconds for some messages to reach subscribers?

**Comment by derekcollison** [comment]
That warning is a hint that the system may need more resources.

Also we do not really suggest using messages that are larger than 1MB. You can chunk them and we actually are starting to provide easy ways to use what we have built to automate that with JetStream.
