### ISSUE TITLE
More meaningful message when trying to ack message that was already acknowledged

### ISSUE THREAD

**Issue by Berreek** [nats-io/nats.go#857]
## Feature Request
Currently when you ack the message that was already acknowledged you get following [error](https://github.com/nats-io/nats.go/blob/5c4ad1696c20507cd78d07f6003580651821ca03/js.go#L2555):
``
nats: invalid jetstream publish response
``

Recently I got quite a lot of this in our application and it turned out that we performed double ack'ing since we did not have `ManualAck` option enabled. However we had to debug it trough to discover the root of this issue since it was not possible to understand it from the message above.

#### Proposed Change:
Change error message to something that will give you a actual context of the error. For example:
``
nats: message was already acknowledged
``

Don't mind doing a PR for it if you are fine with the change.

**Comment by wallyqs** [comment]
This sounds good to me, feel free to make the PR.  Thanks.

**Comment by wallyqs** [comment]
Fixed via #862
