### ISSUE TITLE
add js#GetLastMsg to the JetStreamManager interface

### ISSUE THREAD

**Issue by ogermann** [nats-io/nats.go#861]
## Feature Request
add js#GetLastMsg to the JetStreamManager interface

#### Use Case:
I would like to create an in-memory copy of all msgId's belonging to a specific subject so I can add idempotency to an existing method. Therefore it would be nice to have the GetLastMsg by subject method available in the JetStreamManager interface.

#### Alternative Approaches

If this is by intention feel free to close the request. Thanks in advance.

**Comment by wallyqs** [comment]
Closing since already part of the JetStreamManager interface: https://github.com/nats-io/nats.go/blame/4af26aae252213fd14cdddd1aa401829060ed6d0/jsm.go#L63
