### ISSUE TITLE
Is message decoded once, for several subscribers?

### ISSUE THREAD

**Issue by KnBrBz** [nats-io/nats.go#863]
Several subscribers subscribed the same subject, using `*nats.EncodedConn.BindRecvChan`.

When message comes, will it be decoded once, or number of times equal to subscribers count?

**Comment by ripienaar** [comment]
each subscriber will decode it

**Comment by KnBrBz** [comment]
Even, if using the same connection?

**Comment by ripienaar** [comment]
Yes, every subscription gets a unique message which requires unique decoding.

**Comment by KnBrBz** [comment]
OK, thanks for help!
