### ISSUE TITLE
Error 'no responders available for request' instead of `ErrJetStreamNotEnabled`

### ISSUE THREAD

**Issue by mprimi** [nats-io/nats.go#866]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included nats.go version
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats.go` and the `nats-server` if one was involved:
`nats.go v1.13.1-0.20211018182449-f2416a8b1483`
`nats-server v2.6.2 linux-arm64` or `nats-server v2.6.5 darwin-arm64` both behave the same in this respect

#### OS/Container environment:
Ubuntu 20.04 x86_64 or macOS 11.5.1
(probably not relevant; the issue is likely OS/Arch independent)

#### Steps or code to reproduce the issue:
Start a server, making sure JS is NOT enabled
```
$ nats-server
```

Attempt a JS operation, for example:
```
$ nats stream ls
```

(`nats.go` code that attempts JS operations produces the same error, but the CLI command above is simpler to repro)

#### Expected result:
```
error: nats: jetstream not enabled
```
(a.k.a. [ErrJetStreamNotEnabled](https://github.com/nats-io/nats.go/blob/d7c1d78a50fc9cded3814ae7d7176fa66b73a4b0/nats.go#L138))

#### Actual result:

```
nats: error: could not list Streams: nats: no responders available for request
```

(In some cases,  I get a different error: `context deadline exceeded`, I have not figured out a way to reliably reproduce this)

**Comment by wallyqs** [comment]
This is more of a natscli issue, follow up is here: https://github.com/nats-io/natscli/issues/460

**Comment by ripienaar** [comment]
> This is more of a natscli issue (since uses a different wrapper for nats for some actions), follow up is here: [nats-io/natscli#460](https://github.com/nats-io/natscli/issues/460)

OP says ```(nats.go code that attempts JS operations produces the same error, but the CLI command above is simpler to repro)``` though, so not sure its purely cli.

**Comment by derekcollison** [comment]
We dabbled a bit with this yes, and I think my mistake was taking a more server based approach, which suffered a bit with our mixed mode direction for NGS. But I do think we could do something on an account level to respond that JS is, or is not enabled per account. That might bear fruit.
