### ISSUE TITLE
Missing purge options

### ISSUE THREAD

**Issue by delaneyj** [nats-io/nats.go#870]
## Feature Request
[Support enhanced purge options](https://github.com/nats-io/nats-architecture-and-design/issues/4)

#### Use Case:
Specifically want the behavior found in `nats s purge --seq=1234` that  

> _purge up to but not including a specific message sequence_

#### Proposed Change:
Add purge options found in other clients

#### Who Benefits From The Change(s)?
Anyone trying to do snapshots in a Go base Jetstream application

**Comment by josephwoodward** [comment]
If I'm not mistake, this was added in #988 so this issue can be closed?

**Comment by kozlovic** [comment]
Agree with @josephwoodward. Closing this now.
