### ISSUE TITLE
Test Failure due to conn_test.go error

### ISSUE THREAD

**Issue by saurabhghumnar** [nats-io/nats.go#871]
Testing the nats.go@v1.10.0 
Golang version 1.16
Linux/ppc64le

Testing Command : **go test -v  ./...**

Errors:
 FAIL: TestGetClientID (5.05s)
 **conn_test.go:2175: Did not reconnect**

Error Snap :

Testing  with v1.10.0
go: /home/tester/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/go.mod already exists
ok      github.com/nats-io/nats.go      5.597s
ok      github.com/nats-io/nats.go/bench        0.005s
?       github.com/nats-io/nats.go/encoders/builtin     [no test files]
?       github.com/nats-io/nats.go/encoders/protobuf    [no test files]
?       github.com/nats-io/nats.go/examples/nats-bench  [no test files]
?       github.com/nats-io/nats.go/examples/nats-echo   [no test files]
?       github.com/nats-io/nats.go/examples/nats-pub    [no test files]
?       github.com/nats-io/nats.go/examples/nats-qsub   [no test files]
?       github.com/nats-io/nats.go/examples/nats-req    [no test files]
?       github.com/nats-io/nats.go/examples/nats-rply   [no test files]
?       github.com/nats-io/nats.go/examples/nats-sub    [no test files]
**--- FAIL: TestGetClientID (5.06s)
    conn_test.go:2175: Did not reconnect
FAIL**
FAIL    github.com/nats-io/nats.go/test 42.078s
?       github.com/nats-io/nats.go/util [no test files]
FAIL

Any pointers about why this test fails and a possible solution will be helpful
Thanks

**Comment by saurabhghumnar** [comment]
Any updates on this, please ?

**Comment by wallyqs** [comment]
Hi, could you try running with this instead:

`go test -modfile=go_test.mod -v -run=TestNoRace -p=1 ./...`

**Comment by saurabhghumnar** [comment]
Hi, Im working with version v1.10.0 which does not have the go_test.mod file
Although I ran **go test -v -run=TestNoRace -p=1 ./...** and I get no errors.
The output is as below:
Testing  with v1.10.0
go: /home/tester/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/go.mod already exists
=== RUN   TestNoRaceParseStateReconnectFunctionality
--- PASS: TestNoRaceParseStateReconnectFunctionality (0.13s)
PASS
ok      github.com/nats-io/nats.go      0.136s
testing: warning: no tests to run
PASS
ok      github.com/nats-io/nats.go/bench        0.005s [no tests to run]
?       github.com/nats-io/nats.go/encoders/builtin     [no test files]
?       github.com/nats-io/nats.go/encoders/protobuf    [no test files]
?       github.com/nats-io/nats.go/examples/nats-bench  [no test files]
?       github.com/nats-io/nats.go/examples/nats-echo   [no test files]
?       github.com/nats-io/nats.go/examples/nats-pub    [no test files]
?       github.com/nats-io/nats.go/examples/nats-qsub   [no test files]
?       github.com/nats-io/nats.go/examples/nats-req    [no test files]
?       github.com/nats-io/nats.go/examples/nats-rply   [no test files]
?       github.com/nats-io/nats.go/examples/nats-sub    [no test files]
=== RUN   TestNoRaceOnLastError
--- PASS: TestNoRaceOnLastError (0.40s)
PASS
ok      github.com/nats-io/nats.go/test 0.403s
?       github.com/nats-io/nats.go/util [no test files]
------------------github.com/nats-io/nats.go:install_&_test_both_success-------------------------


Can you please share pointers on why the error exists on not using race option. And how does using NoRaceOnLastError helps ?

Thanks for your help !

**Comment by wallyqs** [comment]
The -p=1 is what helps reducing the parallelism if tests running at the same time

**Comment by kozlovic** [comment]
Yes, but I can reproduce with running single server. With latest (main or v1.13.1), I can't, so I am curious as to why it happens with v1.10.0 and will investigate. That being said, once we get the reason, the answer will be: upgrade to the latest.

**Comment by kozlovic** [comment]
Ok, I got it. It is because the servers now use a "cluster name", which when not explicitly set will be randomly picked, but then need to be negotiated, which will cause route to be disconnected.
If you set the same cluster name on both server, it will work, this is what we do in the latest release: https://github.com/nats-io/nats.go/blob/e5a5689559295cf893a399fe9e9aa0d5da7d1e19/test/conn_test.go#L2213

**Comment by saurabhghumnar** [comment]
Hi,
Was testing with the **go test -v -run=TestNoRace -p=1 ./...** command on a fresh container.
I encountered a new error while doing so

Testing  with v1.10.0
go: /home/tester/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/go.mod already exists
=== RUN   TestNoRaceParseStateReconnectFunctionality
--- FAIL: TestNoRaceParseStateReconnectFunctionality (10.02s)
panic: Unable to start NATS Server in Go Routine [recovered]
        panic: Unable to start NATS Server in Go Routine

goroutine 6 [running]:
testing.tRunner.func1.2(0x106eb240, 0x108dd600)
        /usr/bin/go/src/testing/testing.go:1144 +0x280
testing.tRunner.func1(0xc000001e00)
        /usr/bin/go/src/testing/testing.go:1147 +0x3d4
panic(0x106eb240, 0x108dd600)
        /usr/bin/go/src/runtime/panic.go:965 +0x18c
github.com/nats-io/nats-server/v2/test.RunServerCallback(0xc0001f0000, 0x0, 0x10a1ee00)
        /home/tester/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.6.6/test/test.go:105 +0x164
github.com/nats-io/nats-server/v2/test.RunServer(...)
        /home/tester/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.6.6/test/test.go:75
github.com/nats-io/nats%2ego.RunServerWithOptions(...)
        /home/tester/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats_test.go:234
github.com/nats-io/nats%2ego.RunServerOnPort(...)
        /home/tester/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats_test.go:230
github.com/nats-io/nats%2ego.TestNoRaceParseStateReconnectFunctionality(0xc000001e00)
        /home/tester/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/norace_test.go:24 +0xb4
testing.tRunner(0xc000001e00, 0x1082ee90)
        /usr/bin/go/src/testing/testing.go:1194 +0xd8
created by testing.(*T).Run
        /usr/bin/go/src/testing/testing.go:1239 +0x264
FAIL    github.com/nats-io/nats.go      10.028s
testing: warning: no tests to run
PASS
ok      github.com/nats-io/nats.go/bench        (cached) [no tests to run]
?       github.com/nats-io/nats.go/encoders/builtin     [no test files]
?       github.com/nats-io/nats.go/encoders/protobuf    [no test files]
?       github.com/nats-io/nats.go/examples/nats-bench  [no test files]
?       github.com/nats-io/nats.go/examples/nats-echo   [no test files]
?       github.com/nats-io/nats.go/examples/nats-pub    [no test files]
?       github.com/nats-io/nats.go/examples/nats-qsub   [no test files]
?       github.com/nats-io/nats.go/examples/nats-req    [no test files]
?       github.com/nats-io/nats.go/examples/nats-rply   [no test files]
?       github.com/nats-io/nats.go/examples/nats-sub    [no test files]
=== RUN   TestNoRaceOnLastError
--- FAIL: TestNoRaceOnLastError (10.01s)
panic: Unable to start NATS Server in Go Routine [recovered]
        panic: Unable to start NATS Server in Go Routine

goroutine 6 [running]:
testing.tRunner.func1.2(0x10720160, 0x10924050)
        /usr/bin/go/src/testing/testing.go:1144 +0x280
testing.tRunner.func1(0xc000001e00)
        /usr/bin/go/src/testing/testing.go:1147 +0x3d4
panic(0x10720160, 0x10924050)
        /usr/bin/go/src/runtime/panic.go:965 +0x18c
github.com/nats-io/nats-server/v2/test.RunServerCallback(0xc0001f0000, 0x0, 0x10d83830)
        /home/tester/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.6.6/test/test.go:105 +0x164
github.com/nats-io/nats-server/v2/test.RunServer(...)
        /home/tester/go/pkg/mod/github.com/nats-io/nats-server/v2@v2.6.6/test/test.go:75
github.com/nats-io/nats.go/test.RunServerWithOptions(...)
        /home/tester/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/test/helper_test.go:117
github.com/nats-io/nats.go/test.RunServerOnPort(...)
        /home/tester/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/test/helper_test.go:112
github.com/nats-io/nats.go/test.RunDefaultServer(0x10bfb070)
        /home/tester/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/test/helper_test.go:105 +0xd0
github.com/nats-io/nats.go/test.TestNoRaceOnLastError(0xc000001e00)
        /home/tester/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/test/conn_test.go:1308 +0x34
testing.tRunner(0xc000001e00, 0x1086b8e0)
        /usr/bin/go/src/testing/testing.go:1194 +0xd8
created by testing.(*T).Run
        /usr/bin/go/src/testing/testing.go:1239 +0x264
FAIL    github.com/nats-io/nats.go/test 10.018s
?       github.com/nats-io/nats.go/util [no test files]
FAIL

**Comment by kozlovic** [comment]
I can't reproduce that. It indicates that the server cannot be started. It may be that the server is not even allowed to start a TCP listener? (or that another process is running listening on the same port)

**Comment by saurabhghumnar** [comment]
Yeah, that might be the case. I tried clearing all processes and ran again. The tests pass successfully. These tests seem to fail only when other processes are using the ports.
Thanks for your help.
