### ISSUE TITLE
Assume port 80/443 for ws:// and wss:// connection URIs if not specified instead of 4222.

### ISSUE THREAD

**Issue by cbrake** [nats-io/nats.go#876]
#### Use Case:

Currently, you must specify the port in websocket URIs, as the client assumes 4222 if the port is not specified.

#### Proposed Change:

Assume port 80/443 for ws:// and wss:// connection URIs if not specified instead of 4222.

#### Who Benefits From The Change(s)?

For any nats server with websocket ports on standard 80/443 ports, the user does not have to specify port in the in the URL. For NATS servers that are used by web frontends, this will probably be fairly standard behavior. 

If a user currently enters a URI like: wss://myserver.com, it does not connect as it tries to make a websocket connection to port 4222 -- these kinds of issues are difficult to debug.

Smart defaults make SW easier to use :-)

#### Alternative Approaches

Continue to require port to be specified in ws* URIs -- perhaps document if not already.

**Comment by derekcollison** [comment]
I am supportive of this change.

**Comment by cbrake** [comment]
thanks!
