### ISSUE TITLE
A problem with subscribing messages to the same QueueGroup

### ISSUE THREAD

**Issue by Vanlius** [nats-io/nats.go#885]
hi there,
I have a problem. I configured a stream with **WorkQueue**(Retention) mode and subscribed to the stream using the _**QueueSubscribe(subj, Queue String, CB MsgHandler, opts... )(*Subscription, error)**_    function.

1. I don't understand the meaning of setting DeliverPolicy property as NewInbox() in the new solution consumer.

2.  When consuming in the same Queuegroup, should multiple applications share the same consumer or should each application create an independent consumer with the same Queuegroup?

**Comment by derekcollison** [comment]
If the stream is in WQ mode, just create as many pull subscribers as you might need against the single consumer.
Does not make sense in this setup to use QueueSubscriber IMO.

**Comment by Vanlius** [comment]
> If the stream is in WQ mode, just create as many pull subscribers as you might need against the single consumer. Does not make sense in this setup to use QueueSubscriber IMO.

In WQ mode, all applications are bound to the same durable consumer?
In what mode do you need to bind multiple consumers?

**Comment by derekcollison** [comment]
A pull consumer can have as many applications pulling from it as needed.

**Comment by Vanlius** [comment]
thanks,I'll go over the JetStream documentation again.

**Comment by derekcollison** [comment]
We will continue to improve docs, so feedback is both welcome and appreciated.

**Comment by Vanlius** [comment]
Do you have any plans to support NATS Chinese documentation? I have sinicized Jetstream part by fork nats.docs.
I think the best way to promote NATS is to have more intuitive application examples rather than long documentation.
That's just my opinion. Thank you.

**Comment by derekcollison** [comment]
No plans at this time on doc translations, but we want to get there.

And 100% agree on examples, videos, GH repos etc to supplement documentation.

**Comment by Vanlius** [comment]
thanks for your reply, I have no more questions, so I close this issues
