### ISSUE TITLE
Websocket without auth will hang forever

### ISSUE THREAD

**Issue by wenerme** [nats-io/nats.go#925]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included nats.go version
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats.go` and the `nats-server` if one was involved:
- nats.go 1.3.0
- nats:2.7.3-alpine

#### OS/Container environment:
macos
#### Steps or code to reproduce the issue:

```bash
k -n nats port-forward svc/nats 8443:443

# hang
nats rtt -s ws://127.0.0.1:8443
# OK
nats rtt -s ws://127.0.0.1:8443 --creds /Users/wener/data/dl/nsc/nkeys/creds/KO/JS1/js-user.creds
```

server log

```
[7] 2022/03/14 11:07:36.458612 [ERR] 127.0.0.1:59596 - wid:99 - "v1.13.0:go:NATS CLI Version 0.0.30" - authentication error
```

#### Expected result:

report not authed

#### Actual result:

hang

**Comment by kozlovic** [comment]
@wenerme Thanks! Yes, I was able to reproduce and will work on a fix. Stay tuned.
