### ISSUE TITLE
Please release 1.13.1

### ISSUE THREAD

**Issue by Natureshadow** [nats-io/nats.go#946]
Hi,

Inats-server already depends on 1.13.1 in a published stable release, so this library should also be released to make systems that rely only on released versions work.

Thanks,
Nik

**Comment by wallyqs** [comment]
Hi @Natureshadow, the nats-server just relies on the nats.go client for testing purposes but not as a direct dependency for the binary.

**Comment by Natureshadow** [comment]
> Hi @Natureshadow, the nats-server just relies on the nats.go client for testing purposes but not as a direct dependency for the binary.

Ah, thanks for the heads-up!

Still, building with tests enabled would be very good.

I am currently packaging nats-server for Debian.

**Comment by derekcollison** [comment]
We will release the client soon, it's been awhile. Probably coordinated with the 2.8.0 release of the server which should be soon, maybe next week.

**Comment by kozlovic** [comment]
Closing since we have now released https://github.com/nats-io/nats.go/releases/tag/v1.14.0. The server will update the client deps later, but again, keep in mind that the server uses it only for tests.
