### ISSUE TITLE
No error is returned when trying to delete an account JWT

### ISSUE THREAD

**Issue by goku321** [nats-io/nats.go#975]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included nats.go version
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats.go` and the `nats-server` if one was involved:
`nats.go`: v1.15.0
`nats-server`: v2.8.2

#### OS/Container environment:
macOS Monterey

#### Steps or code to reproduce the issue:
```
func Delete(nc *nats.Conn, operatorKP nkeys.KeyPair) error {
	var err error

	var pubKey string
	if pubKey, err = operatorKP.PublicKey(); err != nil {
		return fmt.Errorf("error getting operator's public key: %s", err)
	}

	claims := jwt.NewGenericClaims(pubKey)
	claims.Data["accounts"] = []string{"OACI4V24AZ4B7EUUHUGTH26YVE2ZKADZAF4GC4VW27SJJ5PKH6S6OHKO"}

	var cJwt string
	if cJwt, err = claims.Encode(operatorKP); err != nil {
		return fmt.Errorf("error encoding delete account claims with operator key pair: %s", err)
	}

	if err := nc.Publish("$SYS.REQ.CLAIMS.DELETE", []byte(cJwt)); err != nil {
		return fmt.Errorf("error publishing on %s", "$SYS.REQ.CLAIMS.DELETE")
	}

	return nc.Flush()
}
```

#### Expected result:
Client should return error when server returns error.

Delete is not enabled on the server and when trying to delete, error message can be seen in the `nats-server` logs:
```
2022/05/11 12:20:12.600693 [ERR] delete accounts request by OACI4V24AZ4B7EUUHUGTH26YVE2ZKADZAF4GC4VW27SJJ5PKH6S6OHKO failed - delete must be enabled in server config
```

#### Actual result:
No error is returned from Go client and it is hard to figure out whether the operation has failed or not.

**Comment by kozlovic** [comment]
@goku321 You need to replace `nc.Publish()` with a `nc.Request()` so that you get the response for this request. The response will be JSON but I am not sure we have an actual object available in the library to decode from, but you should have something like:
```
"error":{"code":500,"description":"delete accounts request by OAVM7BMJUW7A3GY2ZAAYIRQ4YCJB3ZL4HIOOZRSJGX65QJ7FAP7NXOQ7 failed - delete must be enabled in server config"}
```
(there may be some other fields, but those are the one you want to check for error)

**Comment by goku321** [comment]
@kozlovic Thanks for you quick response. I tried using `nc.Request` and I can confirm that it still doesn't return any error while the server logs an error message

**Comment by kozlovic** [comment]
I tested before posting my answer and I do get a response back. Note, the error is not in `err`, instead you get an error in the message's response.
```
msg, err := nc.Request(...)
if err != nil {
    // this is a problem where we are not even able to send a request to the server, etc..
}
fmt.Printf("Response: %s\n", msg.Data)
```

**Comment by goku321** [comment]
My bad. I was checking `err`. I am able to see the error response in `msg`. Thanks for your patience @kozlovic 🙂
