### ISSUE TITLE
Expose error constant for `consumer name already in use`

### ISSUE THREAD

**Issue by mprimi** [nats-io/nats.go#977]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included nats.go version
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats.go` and the `nats-server` if one was involved:

`nats.go` v1.14.0

#### OS/Container environment:

N/A

#### Steps or code to reproduce the issue:

Try to add a consumer when a consumer with the same name exists
```
js.AddConsumer("some stream", consumerConfig)
js.AddConsumer("some stream", consumerConfig)
```

The error is expected, as the consumer exists! 
However, one has to do **manual string comparison** because an error constant is not provided for this case.

Here's an example [from this repo itself](https://github.com/nats-io/nats.go/blob/main/js.go#L1580-L1581):
```
				(strings.Contains(cinfo.Error.Description, `consumer already exists`) ||
					strings.Contains(cinfo.Error.Description, `consumer name already in use`)) {
```

#### Expected result:
This is what I wish I could do:
```
  consumerInfo, err := js.AddConsumer(streamName, consumerConfig)
  if err == nats.ErrConsumerExists {
    // consumer exists - do what is appropriate
  }
```

#### Actual result:
This is what I'm forced to do (brittle and ugly):
```
  consumerInfo, err := js.AddConsumer(streamName, consumerConfig)
  if err != nil && fmt.Sprintf("%s", err) == "consumer name already in use" {
    // consumer exists - do what is appropriate
  }
```

**Comment by wallyqs** [comment]
Sounds good to me to add, we could have `ErrConsumerNameAlreadyInUse ` similar to `ErrStreamNameAlreadyInUse` that already exists.

**Comment by ripienaar** [comment]
This client really should support the jetstream error codes :)
