### ISSUE TITLE
"nats: timeout" when using Request() and bad permissions

### ISSUE THREAD

**Issue by goku321** [nats-io/nats.go#978]
I have a user which is not allowed to publish on subject **test.a**. When doing a request call like:
```
 nc, _ := nats.Connect("localhost:4222", nats.UserCredentials("user.creds"))
 msg, err := nc.Request("test.a", []byte("hello"), time.Second*10)
```

I get a timeout error instead of permission violations (which I can see in nats-server logs). I was expecting that the error code (500) would be visible inside the `msg` response but in this case it is `nil`.

Is there a way that I can check for permission violation error?

**Comment by aricart** [comment]
@goku321 what version of the library are you using? Just released yesterday a feature that enables exactly this.

**Comment by aricart** [comment]
@goku321 apologies, misspoke, the feature is nats.js, not nats.go

**Comment by wallyqs** [comment]
you would be able to see the permission errors when using the Error Handler https://beta.pkg.go.dev/github.com/nats-io/nats.go#ErrorHandler but there is no way to get that as a synchronous error right now.

**Comment by goku321** [comment]
I think the error handler should do the job. I'll try it. Thanks for the suggestion :)
