### ISSUE TITLE
How to run nats client forever indefinitely just like we do with http server.Start()

### ISSUE THREAD

**Issue by khanakia** [nats-io/nats.go#984]
Right now the examples are given on the Readme file close the go application once ran. But I want to keep listening forever so how do I run nat client app indefinitely and keep listening to the messages.

Like we can do that in Python here https://github.com/nats-io/nats.py/issues/111

But how do we do that in golang?

**Comment by derekcollison** [comment]
https://github.com/nats-io/nats.go/tree/main/examples/nats-sub
